### PR TITLE
New Mesh: WC14to60kmL60E3SMv2r03

### PR DESCRIPTION
**Pull request by xylar**
Design discussion Water Cycle mesh, 14km high resolution region:
> MPAS North America and Arctic Focused Water Cycle mesh for E3SM version 2, with a focused 14-km resolution around North America and 60 vertical levels

This iteration of the `WC14` mesh is with shipping tracks (https://github.com/MPAS-Dev/geometric_features/pull/145) and the Foxe Basin Throughflow (https://github.com/MPAS-Dev/geometric_features/pull/146) open in the Arctic.

### CODE REVIEW

**Comment by xylar** [comment]
@vanroekel, would you set up the review process for this mesh on Confluence, as you have for previous revisions?

**Comment by xylar** [comment]
I am working on spinning this up on LANL IC at:
```
/lustre/scratch4/turquoise/xylar/spin_up_WC14to60kmL60E3SMv2r03/ocean/global_ocean/WC14
```
I will post some plots once it has finished initialization and will also post here when spin-up is complete.

**Comment by proteanplanet** [comment]
@xylar I'll run some visual QC over the mesh when ready, and post it here.

**Comment by vanroekel** [comment]
@xylar the confluence page is here -- https://acme-climate.atlassian.net/wiki/spaces/EWCG/pages/1492910110/WC14to60kmL60E3SMv2r03

Thanks for making the PR.  I'll dig in once @proteanplanet has a chance to make some QC figures (no rush, we are running WC14r02 with ne30 now)

**Comment by vanroekel** [comment]
also thanks for making 60 layer the default!

**Comment by xylar** [comment]
## Distribution of Resolution

This is the same as in #584 

cellWidthGlobal
mesh_construction

@proteanplanet, the mesh is available at this location:
```
/lustre/scratch4/turquoise/xylar/spin_up_WC14to60kmL60E3SMv2r03/ocean/global_ocean/WC14/init/initial_state/initial_state.nc
```
Please proceed with your quality-control plots.  The spin-up is still waiting in the queue

**Comment by proteanplanet** [comment]
### Global Scale Sectors

WC14r03_sector_1

WC14r03_sector_2

WC14r03_sector_3

WC14r03_sector_4

WC14r03_sector_5

WC14r03_sector_6

**Comment by proteanplanet** [comment]
### Regional Zooms

WC14r03_zoom_1

WC14r03_zoom_2

WC14r03_zoom_3

WC14r03_zoom_4

WC14r03_zoom_5

WC14r03_zoom_6

WC14r03_zoom_7

WC14r03_zoom_8

WC14r03_zoom_9

WC14r03_zoom_10

WC14r03_zoom_11

WC14r03_zoom_12

WC14r03_zoom_13

WC14r03_zoom_14

WC14r03_zoom_15

WC14r03_zoom_16

WC14r03_zoom_17

WC14r03_zoom_18

WC14r03_zoom_19

WC14r03_zoom_20

WC14r03_zoom_21

WC14r03_zoom_22

WC14r03_zoom_23

WC14r03_zoom_24

WC14r03_zoom_25

WC14r03_zoom_26

WC14r03_zoom_27

WC14r03_zoom_28

WC14r03_zoom_29

WC14r03_zoom_30

WC14r03_zoom_31

WC14r03_zoom_32

WC14r03_zoom_33

WC14r03_zoom_34

WC14r03_zoom_35

WC14r03_zoom_36

WC14r03_zoom_37

WC14r03_zoom_38

WC14r03_zoom_39

WC14r03_zoom_40

WC14r03_zoom_41

WC14r03_zoom_42

**Comment by vanroekel** [comment]
@milenaveneziani @lconlon @qingli411 @proteanplanet please provide your thoughts on this mesh.  Once approved we will plan on running a coupled simulation for potential finalizing into WC v2 of E3SM

**Comment by proteanplanet** [comment]
### Review and Points to Consider

- The Arctic and Antarctic are just about perfect.
- Delaware Bay, Chesapeake Bay, Gulf of Mexico and Caribbean are also as perfect as they can be at this resolution.
- Indonesian Throughflow has a sufficient number of channels at 2 cells wide or more
- Items that I think just need to be accepted at this resolution: Puget Sound and Strait of Gibraltar.

I'll post bathymetric charts in the coming day as a point of documentation.

**Comment by xylar** [comment]
@vanroekel, I ran the spin-up but it fails on the final step with:

```
ERROR: Stream 'restart' attempted to read non-existent file 'restarts/restart.0001-01-01_00.00.00.nc'
```
Based on our discussion of the r02 mesh (https://github.com/MPAS-Dev/MPAS-Model/pull/584#discussion_r436054187), I had the impression you had fixed `test_final_settings` but maybe something didn't get committed in that PR and needs to be added here?

**Comment by xylar** [comment]
The spin-up is at:
```
/lustre/scratch4/turquoise/xylar/spin_up_WC14to60kmL60E3SMv2r03/ocean/global_ocean/WC14/spin_up
```

**Comment by xylar** [comment]
@vanroekel, I think I've addressed the final spin-up step, but please verify that this is also what you did last time.

**Comment by vanroekel** [comment]
@xylar thanks, the changes are consistent with what I did and you are exactly right.  I had uncommitted changes that never propagated into the last PR.  Thanks for the fix!

**Comment by xylar** [comment]
@vanroekel, my changes didn't work in the test I ran.  I'm trying again.

**Comment by xylar** [comment]
@vanroekel, I'm going to start a branch for r04.  To make that easier, I'm going to rebase this branch onto the current `ocean/devleop`.  Is there any reason not to merge this branch at this point, once I've rebases?

**Comment by vanroekel** [comment]
@xylar I would just want to make sure @mark-petersen is okay with merging, otherwise given others approvals I think this is ready.

**Comment by mark-petersen** [comment]
Sorry for the delay. Testing now. @vanroekel please approve if you feel this is ready.

**Comment by mark-petersen** [comment]
PS: A mesh generation timing test took 18:14 on Chrysalis on one node.

**Pull request merged**
