### PR TITLE
Move LIGHT scripts to ocean COMPASS directory

### PR DESCRIPTION
**Pull request by mark-petersen**
LIGHT scripts were previously in the general directory for COMPASS scripts, but are only used for ocean simulations, so the ocean subdirectory is more appropriate.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@pwolfram and @bradyrx take a quick look. Do any other scripts list the path for these files and need to be modified?

**Comment by bradyrx** [comment]
I'm unaware of anything that calls these scripts directly within MPAS-Model. This should be fine just moving them to the new directory.

**Comment by mark-petersen** [comment]
@pwolfram this is a LIGHT directory, go ahead and merge when you want.

**Comment by mark-petersen** [comment]
@pwolfram I'm doing a python script update in E3SM. I'm guessing I can merge this in now?

**Comment by pwolfram** [comment]
Yes please

**Comment by pwolfram** [comment]
Thanks

**Pull request merged**
