### PR TITLE
E3SM Makefile name update

### LINKED ISSUE #66: Rename Makefile.in.ACME to Makefile.in.E3SM
Cleanup of naming to match E3SM project name

Pat Worley reported this in E3SM [Issue #2467](https://github.com/E3SM-Project/E3SM/issues/2467). Though it is not critical, it would be good to do at some point.

### PR DESCRIPTION
**Pull request by mark-petersen**
Change Makefile name from ACME to E3SM.
Remove Makefile.in.CESM

fixes #66

### CODE REVIEW

**Comment by mark-petersen** [comment]
This is for a few changes to the makefiles that will end up in the next E3SM PR.

Is anyone using Makefile.in.CESM? Any votes on whether to keep it or delete it?

If it is unused, my vote is to delete it.

**Comment by matthewhoffman** [comment]
@mgduda , any objections at NCAR to removing Makefile.in.CESM?

**Comment by jonbob** [comment]
My vote is to delete it as well

**Comment by mark-petersen** [comment]
Thanks! It is nearly identical to Makefile.in.E3SM, so it would be easy recreate, and we will keep that one up to date.

**Pull request merged**
