### PR TITLE
Vertical Lagrangian-remap design doc

### PR DESCRIPTION
**Pull request by cbegeman**
This design doc is for the implementation of the vertical Lagrangian-remap method. This development is motivated by the occurrence of instabilities in cases of evolving ice-shelf geometry, but should have broad advantages including higher-order accuracy and lifting the vertical CFL constraint.

### CODE REVIEW

**Comment by xylar** [comment]
@cbegeman, sorry about the confusion.  It's important that we not develop any further on this branch.  We've already got 3 emails from the developer's email list for commits to this branch so I think the only option is to close this PR and open a new one from a branch on your own fork.  Otherwise, the group is going to get pelted with nonstop emails.

Again, sorry about that.

**Comment by cbegeman** [comment]
My apologies. To make sure this doesn’t happen again, let me know if this workflow is what I should be doing

$git remote -v
MPAS-Dev           git@github.com:MPAS-Dev/MPAS-Model.git (fetch)
MPAS-Dev           git@github.com:MPAS-Dev/MPAS-Model.git (push)
origin     git@github.com:cbegeman/MPAS-Model.git (fetch)
origin     git@github.com:cbegeman/MPAS-Model.git (push)

$git worktree add ../new_branch
$cd ../new_branch
$git cherry-pick hash_for_old_commit
$git push origin new_branch

**Comment by xylar** [comment]
@cbegeman, yes, that looks right to me.  One way to avoid confusion is to make sure your remotes have pretty verbose names:
```
git remote rename origin cbegeman/MPAS-Model
git remote rename MPAS-Dev MPAS-Dev/MPAS-Model
```
Then, there's never a remote called `origin` to get confused about.

One other thing: Our branch naming convention is to add `ocean/` at the start of any branches to do with the ocean core.  You don't have to do that since you'll be working with the ocean core exclusively.  But I just thought I would mention it since you will see some of us doing that.

**Comment by xylar** [comment]
Let me know if I can delete the branch.  It hopefully won't affect you since you presumably still have your local check-out.

Speaking of which, you could just push the same branch to your fork instead of `MPAS-Dev/MPAS-Model` and you don't need to create a new branch or cherry-pick to it.

**Comment by mgduda** [comment]
To expand on what @xylar has said about branch naming conventions, I'd suggest that every PR that targets the `develop` branch should have an appropriate prefix in the branch name, regardless of whether the contributor of the PR works exclusively with a particular core or not. (I do recognize this PR targeted `ocean/develop`). One of the motivations of the branch naming convention was to make it easy for everyone to easily determine which part of the code (`framework`, `atmosphere`, `ocean`, `landice`, `seaice`) a branch is associated with. At least in principle, this convention should also discourage contributors from combining framework changes with core-specific changes in the same PR.

**Comment by mgduda** [comment]
Is it also safe to delete the [vlr_design_doc](https://github.com/MPAS-Dev/MPAS-Model/tree/vlr_design_doc) branch from the MPAS-Model repository?

**Comment by cbegeman** [comment]
@mgduda Thanks for pointing that out. It should now be deleted.

**Comment by mgduda** [comment]
@cbegeman Thanks!

**Pull request closed without merging**
