### PR TITLE
CONUS mesh update

### PR DESCRIPTION
**Pull request by sbrus89**
Adds coastal resolution around Greenland in the NAEC60to30cr8 mesh. Also incorporates two minor updates to coastal_tools.py.

### CODE REVIEW

**Comment by sbrus89** [comment]
Here is an image of what the high-resolution region around Greenland looks like now...

greenland_resolution

**Comment by sbrus89** [comment]
nCells is now 645,043 compared to 622,022 in the previous version.

**Comment by mark-petersen** [comment]
It's a bargain! This looks good to me, based on the image. @maltrud what do you think?

**Comment by maltrud** [comment]
@sbrus89 this looks great.  can you please point us to the IC file when it is ready so we can have a closer look?

**Comment by sbrus89** [comment]
@maltrud, I updated the directory: 
`/lustre/scratch4/turquoise/.mdt5/sbrus/MPAS-O_meshes/NAEC60to30cr8`
to contain the new mesh files generated with this PR. 

The previous version is now located in:
`/lustre/scratch4/turquoise/.mdt5/sbrus/MPAS-O_meshes/NAEC60to30cr8/archive/fe1019e`

**Comment by sbrus89** [comment]
Thanks @matthewhoffman!

**Comment by pwolfram** [comment]
Excellent, thanks @sbrus89!

**Comment by xylar** [comment]
> I updated the directory:
/lustre/scratch4/turquoise/.mdt5/sbrus/MPAS-O_meshes/NAEC60to30cr8
to contain the new mesh files generated with this PR.

The description of the PR suggests cr10, rather than cr8. maybe update whichever of these is incorrect to avoid confusion.

**Comment by xylar** [comment]
I'll be happy to do a more complete review of the tool updates next week when I'm back, if needed.

**Comment by sbrus89** [comment]
@xylar, thanks for catching that. It should be cr8. I edited the description to reflect this. The paths should be correct since they are copy/pasted.

**Comment by mark-petersen** [comment]
@sbrus89 we just had a major framework merge, including CONUS partial python 3 updates, so I rebased.  I also removed `jigsaw_to_MPAS` as its own path in the config file, since it is just a directory.

Please remove the `jigsaw_to_MPAS` line from your compass `general.config.ocean` file and retest your CONUS cases on the head of this PR.

**Comment by sbrus89** [comment]
@mark-petersen, thanks for making those updates. I tested and the mesh is B4B with the previous commit.

I also added a 60 layer case as requested by @maltrud, which has an identical horizontal mesh (with 20 fewer layers). The 60 layer mesh is located here:
`/lustre/scratch4/turquoise/.mdt5/sbrus/MPAS-O_meshes/NAEC60to30cr8L60`

**Comment by xylar** [comment]
@pwolfram and @maltrud, this PR is waiting on your review.  Maybe you know that already.

**Comment by pwolfram** [comment]
@mark-petersen, everyone has approved and this is ready to merge.

**Pull request merged**
