### PR TITLE
Update ISOMIP+ test case and add new parameter studies

### PR DESCRIPTION
**Pull request by xylar**
Variables are now averaged with `timeSeriesStatsMonthlyOutput` to ISOMIP+ test cases.  Evaporation rates are computed based on monthly mean melt rates.  Visualization and output for MISOMIP are computed from this output as well.

New default parameter values are used in ISOMIP+ based on redoing the Ocean0 parameter study (varying the heat and salt transfer coefficients and finding the value that gives 30 m/yr mean melt rate for `landIceDraft < -300`).

Scripts have been added for generating 3 different parameter studies that will be used in Gwyther et al., "The importance of vertical processes and resolution on simulated basal melt of an ice shelf: a multi-model study within the ISOMIP+ framework", in prep.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I've run all ISOMIP+ test cases (Ocean0, Ocean1 and Ocean2) on Cori and have prepared the results for submission to the MISOMIP project.

I am finishing up running the 4 Gwyther parameter studies:
* varying vertical resolution (`nVertLevels` = 36, 48, 72, 90, 120) with various values of boundary-layer thicknesses
* varying heat transfer coefficient with fixed tracer and flux boundary-layer thicknesses (20 m)
* varying heat transfer coefficient and tracer boundary-layer thickness with fixed flux boundary-layer thickness (2 m)
* varying heat transfer coefficient and flux boundary-layer thickness with fixed tracer boundary-layer thickness (2 m)

**Comment by xylar** [comment]
@mark-petersen, what I'm hoping you might be able to do is run the land-ice regression test suite to make sure it still works for you:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/regression_suites/land_ice_fluxes.xml
I'll do the same on Cori.  The important 3 are Ocean0, Ocean1 and Ocean2.

**Comment by xylar** [comment]
Note that, because of #145, the test suite will report needing 136 MPI tasks but it should, in fact, run on 16 (or so) and should fit on one node.

**Comment by xylar** [comment]
I need to fix the `is_periodic` attribute for all these test cases.

**Comment by mark-petersen** [comment]
I ran the `land_ice_fluxes_test_suite` on the head of ocean/develop and separately on this branch.  Both pass all tests, using gnu on grizzly:<details>  
```
 ** Running case ISOMIP 1.01 - Smoke Test
      PASS
 ** Running case ISOMIP 2.01 - Smoke Test
      PASS
 ** Running case ISOMIP+ Ocean0 - Smoke Test
      PASS
 ** Running case ISOMIP+ Ocean1 - Smoke Test
      PASS
 ** Running case ISOMIP+ Ocean2 - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - default - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Haney-number constrained - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - iterative init - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Haney-number constrained, iterative init - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Smoke Test with frazil
      PASS
 ** Running case sub-ice-shelf 2D - restart test
      PASS
 ** Running case QU 240km - Smoke Test
      PASS
 ** Running case QU 120km - Smoke Test
      PASS
```
</details>
If I _compare_ the suite between ocean/develop and this branch, there are 5 that do not match.
<details>  

```
  ** Running case ISOMIP 1.01 - Smoke Test
      PASS
 ** Running case ISOMIP 2.01 - Smoke Test
      PASS
 ** Running case ISOMIP+ Ocean0 - Smoke Test
   ** FAIL (See case_outputs/ISOMIP+_Ocean0_-_Smoke_Test for more information)
 ** Running case ISOMIP+ Ocean1 - Smoke Test
   ** FAIL (See case_outputs/ISOMIP+_Ocean1_-_Smoke_Test for more information)
 ** Running case ISOMIP+ Ocean2 - Smoke Test
   ** FAIL (See case_outputs/ISOMIP+_Ocean2_-_Smoke_Test for more information)
 ** Running case sub-ice-shelf 2D - default - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Haney-number constrained - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - iterative init - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Haney-number constrained, iterative init - Smoke Test
      PASS
 ** Running case sub-ice-shelf 2D - Smoke Test with frazil
      PASS
 ** Running case sub-ice-shelf 2D - restart test
      PASS
 ** Running case QU 240km - Smoke Test
   ** FAIL (See case_outputs/QU_240km_-_Smoke_Test for more information)
 ** Running case QU 120km - Smoke Test
   ** FAIL (See case_outputs/QU_120km_-_Smoke_Test for more information)
```
</details>
@xylar is that what you expect?

**Comment by xylar** [comment]
@mark-petersen, no I wouldn't expect the QU 240km and QU 120km to fail with these changes.  Could you give me more detail on why those fail?  The Ocean0-2 tests should fail because I changed a number of things about them.

**Comment by xylar** [comment]
@mark-petersen, I think this is finally ready to merge.  Could you re-test the `land_ice_fluxes_test_suite`?  You thought your test from earlier had been mixed up with testing for another PR.

**Comment by xylar** [comment]
Thanks @mark-petersen

**Pull request merged**
