### PR TITLE
Adds testing of aerosols with shortwave feedbacks

### PR DESCRIPTION
**Pull request by njeffery**
Corrections in Registry and mpas_seaice_column to enable vertical
aerosol implementation without other bgc tracers.  BFB in standard tests.  Standard-bgc test broke during the last merge (namelist error)  and is corrected in this PR.  With the namelist correction to seaice/develop, BGC test is BFB.

### CODE REVIEW

**Comment by njeffery** [comment]
@akturner :  Did these tests fail after merging to master or before?

**Comment by akturner** [comment]
@njeffery: After a trial merge into seaice/develop

**Comment by njeffery** [comment]
@akturner :  This should work now.

**Comment by akturner** [comment]
@njeffery: Fails a regression test:
```
Testing MPAS-Seaice
===================
Test suite:  ../development/MPAS-Model/testing_and_setup/seaice/testing/testsuites/testsuite.standard_bgc.xml

Domains directory:  /Users/akt/Work/MPAS-Seaice/Standalone_sim_configs/test_datasets/20181119/MPAS-Model/testing_and_setup/seaice/testing/DATA

Using configuration standard_bgc and domain domain_QU240km...

Test: Regression, Configuration: standard_bgc, Domain: domain_QU240km
=====================================================================
FAIL!: Test regression run incomplete

Test: Parallelism, Configuration: standard_bgc, Domain: domain_QU240km
======================================================================
multipleBlocks:  False
No non-contents errors
PASS: Test parallelism passed

Test: Restartability, Configuration: standard_bgc, Domain: domain_QU240km
=========================================================================
No non-contents errors
PASS: Test restartability passed

Summary
=======
3 tests (2 passed, 1 failed)
```

**Comment by njeffery** [comment]
@akturner :  The failure is in seaice/develop not the branch.  The namelist for the standard_bgc testcase has an error.

**Comment by akturner** [comment]
@njeffery: Can this be fixed?

**Comment by njeffery** [comment]
It's fixed in the PR.

n

________________________________

**Comment by akturner** [comment]
@njeffery: I'm confused - the PR comment says this is BFB in the BGC test

**Comment by njeffery** [comment]
It is BFB with BGC.  The standard_bgc testcase broke during the last merge.  The PR was submitted many weeks before that merge was complete.


In seaice/develop configurations/standard_bgc/namelist.seaice

@column_package has a typo


config_use_column_snow_density = false should be config_use_column_snow_tracers = false.


This is corrected in the current PR.  If you make the change above, the regression test passes.

n

________________________________

**Comment by akturner** [comment]
@njeffery: Please clarify this in the PR comment

**Comment by njeffery** [comment]
I don't know how to edit the PR comment.

**Pull request merged**
