### PR TITLE
Add a CMakeLists.txt for mpas/src

### PR DESCRIPTION
**Pull request by jgfouca**
This will allow E3SM, which is being converted to a CMake-based build
system, to build MPAS.

This is only for mpas-ocean for now. Subsequent PRs will be needed for other components.

### CODE REVIEW

**Comment by jgfouca** [comment]
@jonbob , assign reviewers etc. as appropriate.

**Comment by jonbob** [comment]
@jgfouca - can you not delete Makefile_in.E3SM? I know our developers will want to be able to build inside E3SM with something they're used to

**Comment by jgfouca** [comment]
@jonbob , yes. And, now that I think about it, it will still be needed for the other components until they are converted too.

**Comment by jonbob** [comment]
I think you'll find that some people will still want the option to use the old system. For most of us, it's easier to understand and modify

**Comment by jgfouca** [comment]
@jonbob , we may be able to keep the old system if developers want to do standalone E3SM-like MPAS builds. I don't think we'll be able to continue support for driving the MPAS builds within E3SM via Makefiles.

**Comment by jonbob** [comment]
@jgfouca - that may be a serious issue then. We have several people who need to modify the build system to develop new features, and I don't think they're fluent in cmake

**Comment by jonbob** [comment]
Is there a reason we can't support the current build system as well as cmake?

**Comment by jgfouca** [comment]
@jonbob , it should be as easy as adding files to RAW_SOURCES.

> Is there a reason we can't support the current build system as well as cmake?

Right now, at a very high level, CIME builds components as follows:
```
build.py
   for each component:
       run shell command component/cime_config/buildlib
```
Right now, the logic for what build system to invoke is in buildlib and would be easy to switch back to old Makefile system.

However, the goal of the CMake refactor is:
```
build.py
   cmake components
   make
```
In which case, it becomes much more difficult to have MPAS doing it's own thing.

**Comment by jonbob** [comment]
The problem is when we need to do something more complicated than just add new files. And we often do

**Comment by jgfouca** [comment]
@jonbob , I'd be happy to help with that.

I'm assuming that the really tricky stuff (cvmix, BGC, and the registry processing stuff) is pretty stable and that the most likely changes are adding/removing files and change CPP flags.

**Comment by mgduda** [comment]
@jgfouca I'm assuming there are no plans to modify the stand-alone builds of any of the cores, right? Also, would you mind squashing the two commits in this PR together? There doesn't seem to be a good reason to remove a file and to then commit it again in the next commit. Ultimately it doesn't matter, but I think it's nice to keep the commit history tidy.

**Comment by jgfouca** [comment]
@mgduda , that's correct, no plans to modify standalone. I do think it would be better, longterm, for both E3SM and MPAS if MPAS had a single CMake build system.

I will squash my commits.

**Comment by jgfouca** [comment]
I'm seeing a DIFF in my testing, I may need to make additional commits.

**Comment by jgfouca** [comment]
OK, the issue was just an out-of-date baseline. This PR is ready from my point of view.

**Comment by jgfouca** [comment]
Replaced by #281

**Pull request closed without merging**
