### PR TITLE
Minor clean up of NAEC60to30cr8 mesh

### PR DESCRIPTION
**Pull request by sbrus89**
This PR cleans up some resolution artifacts around the Bering Sea region.

Before:
cellarea_42029f2

This PR:
cellarea

### CODE REVIEW

**Comment by sbrus89** [comment]
@xylar, do you think we could get this one merged today as well?

**Comment by sbrus89** [comment]
Great, thanks. I appreciate your help!

**Comment by xylar** [comment]
I will put a merged branch up on my fork and ask you to test the EC60to30 and CONUS grid creation if you don't mind.  I'll take care of testing bit-for-bit under GNU and intel for our standard test cases.

**Comment by sbrus89** [comment]
Sounds good.

**Comment by xylar** [comment]
@sbrus89, could you test generation of both meshes on `ocean/develop` on my fork?  It should include all these recent fixes.  Thanks!

**Comment by sbrus89** [comment]
Sure thing. I'll let you know when I'm done.

**Comment by xylar** [comment]
##Testing

I tested the nightly regression suite on badger with GNU and this branch is bit-for-bit identical to the current `ocean/develop`

**Comment by sbrus89** [comment]
##Testing

I tested both the NAEC60to30cr8 and EC60to30 meshes and they are both BFB identical for two separate runs. 

@xylar, I think this can be merged now.

**Comment by xylar** [comment]
Great!  I'll merge all of these!

**Pull request merged**
