### PR TITLE
Remove unused cases

### PR DESCRIPTION
**Pull request by mark-petersen**
Remove these cases, which are never used. 
- QU60 (can easily recreate from QU240)
- CUSP8 (keeping CUSP12)
- ARM60to6 (keeping ARM60to10)
- SOQU60to15 (from summer work with Kevin Rosa in 2018)

Since it takes time and testing to keep these directories working, it is better to prune them. Also, when difference between cases is just the high resolution region, the init files are usually identical except for the number (8km, 12km, etc). The exception is the values for the spin-up parameters. However, we are redoing several meshes right now, so it's best to have just one resolution of each mesh type.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@xylar, I'm open to your comments here. We could also throw other clean-up or pruning in this PR.

**Comment by xylar** [comment]
@mark-petersen and @pwolfram, can you edit this comment and move the "unknown" test cases below to the proper place?  Or can you ping the appropriate people to do that?

## Actively used
```
  45: -o ocean -c baroclinic_channel -r 10km -t decomp_test
  46: -o ocean -c baroclinic_channel -r 10km -t default
  47: -o ocean -c baroclinic_channel -r 10km -t restart_test
  48: -o ocean -c baroclinic_channel -r 10km -t rpe_test
  49: -o ocean -c baroclinic_channel -r 10km -t threads_test
  50: -o ocean -c baroclinic_channel -r 1km -t rpe_test
  51: -o ocean -c baroclinic_channel -r 4km -t rpe_test
  64: -o ocean -c global_ocean -r ARM60to10 -t init
  66: -o ocean -c global_ocean -r CUSP12 -t init
  67: -o ocean -c global_ocean -r CUSP12 -t spin_up
  70: -o ocean -c global_ocean -r EC60to30 -t init
  71: -o ocean -c global_ocean -r EC60to30 -t spin_up
  72: -o ocean -c global_ocean -r EC60to30wISC -t init
  73: -o ocean -c global_ocean -r EC60to30wISC -t spin_up
  74: -o ocean -c global_ocean -r QU240 -t analysis_test
  75: -o ocean -c global_ocean -r QU240 -t init
  76: -o ocean -c global_ocean -r QU240 -t performance_test
  77: -o ocean -c global_ocean -r QU240 -t restart_test
  78: -o ocean -c global_ocean -r QU240 -t rk4_blocks_test
  79: -o ocean -c global_ocean -r QU240 -t se_blocks_test
  80: -o ocean -c global_ocean -r QU240 -t test
  81: -o ocean -c global_ocean -r QU240 -t thread_test
  82: -o ocean -c global_ocean -r QU240wISC -t init
  85: -o ocean -c global_ocean -r SO60to10wISC -t init
  86: -o ocean -c global_ocean -r SO60to10wISC -t spin_up
  96: -o ocean -c isomip -r 10km -t expt1.01
  97: -o ocean -c isomip -r 10km -t expt2.01
  98: -o ocean -c isomip_plus -r 2km -t Ocean0
  99: -o ocean -c isomip_plus -r 2km -t Ocean1
  100: -o ocean -c isomip_plus -r 2km -t Ocean2
  101: -o ocean -c isomip_plus -r 2km -t time_varying_Ocean0
  102: -o ocean -c isomip_plus -r 5km -t Ocean0
  103: -o ocean -c isomip_plus -r 5km -t Ocean1
  104: -o ocean -c isomip_plus -r 5km -t Ocean2
  129: -o ocean -c sub_ice_shelf_2D -r 5km -t Haney_number_init
  130: -o ocean -c sub_ice_shelf_2D -r 5km -t Haney_number_iterative_init
  131: -o ocean -c sub_ice_shelf_2D -r 5km -t default
  132: -o ocean -c sub_ice_shelf_2D -r 5km -t iterative_init
  133: -o ocean -c sub_ice_shelf_2D -r 5km -t restart_test
  134: -o ocean -c sub_ice_shelf_2D -r 5km -t with_frazil
```

## Remove
```
  65: -o ocean -c global_ocean -r ARM60to6 -t init
  68: -o ocean -c global_ocean -r CUSP8 -t init
  69: -o ocean -c global_ocean -r CUSP8 -t spin_up
  83: -o ocean -c global_ocean -r QU60 -t init
  84: -o ocean -c global_ocean -r QU60 -t spin_up
  87: -o ocean -c global_ocean -r SOQU60to15 -t init
  88: -o ocean -c global_ocean -r SOQU60to15 -t spin_up
```

## Move to ocean_depricated
```
```

## Unknown
```
  40: -o ocean -c Gaussian_hump -r USDEQU120cr10rr2 -t build_mesh
  41: -o ocean -c Gaussian_hump -r USDEQU120cr10rr2 -t delaware
  42: -o ocean -c Redi_verification -r SouthernOceanSlice40 -t all
  43: -o ocean -c Redi_verification -r SouthernOceanSlice40 -t se_blocks_test
  44: -o ocean -c Redi_verification -r SouthernOceanSlice40 -t thread_test
  52: -o ocean -c coastal -r Maine -t init
  53: -o ocean -c coastal -r USDEQU120cr10rr2 -t build_mesh
  54: -o ocean -c dam_break -r default -t 004m
  55: -o ocean -c dam_break -r default -t 012m
  56: -o ocean -c drying_slope -r hybrid -t 1km
  57: -o ocean -c drying_slope -r hybrid -t 250m
  58: -o ocean -c drying_slope -r meshes -t 1km
  59: -o ocean -c drying_slope -r meshes -t 250m
  60: -o ocean -c drying_slope -r sigma -t 1km
  61: -o ocean -c drying_slope -r sigma -t 250m
  62: -o ocean -c drying_slope -r zstar -t 1km
  63: -o ocean -c drying_slope -r zstar -t 250m
  89: -o ocean -c hurricane -r USDEQU120at30cr10rr2 -t build_mesh
  90: -o ocean -c hurricane -r USDEQU120at30cr10rr2 -t sandy
  91: -o ocean -c hurricane -r USDEQU60at15cr5rr1 -t build_mesh
  92: -o ocean -c hurricane -r USDEQU60at15cr5rr1 -t sandy
  93: -o ocean -c internal_waves -r 5km -t default
  94: -o ocean -c internal_waves -r 5km -t rpe_test
  95: -o ocean -c internal_waves -r 5km -t ten-day
  105: -o ocean -c lock_exchange -r 0.5km -t default
  106: -o ocean -c lock_exchange -r 0.5km -t rpe_test
  107: -o ocean -c lock_exchange -r 16km -t default
  108: -o ocean -c overflow -r 10km -t default
  109: -o ocean -c overflow -r 1km -t rpe_test
  110: -o ocean -c periodic_planar -r 20km -t default_light
  111: -o ocean -c periodic_planar -r 20km -t region_reset_light_test
  112: -o ocean -c periodic_planar -r 20km -t time_reset_light_test
  113: -o ocean -c sea_mount -r 6.7km -t default
  114: -o ocean -c single_column_model -r planar -t cvmix_test
  115: -o ocean -c single_column_model -r sphere -t cvmix_test
  116: -o ocean -c soma -r 16km -t 3layer
  117: -o ocean -c soma -r 16km -t default
  118: -o ocean -c soma -r 16km -t surface_restoring
  119: -o ocean -c soma -r 32km -t 3layer
  120: -o ocean -c soma -r 32km -t default
  121: -o ocean -c soma -r 32km -t surface_restoring
  122: -o ocean -c soma -r 32km -t time_varying_wind
  123: -o ocean -c soma -r 4km -t 3layer
  124: -o ocean -c soma -r 4km -t default
  125: -o ocean -c soma -r 4km -t surface_restoring
  126: -o ocean -c soma -r 8km -t 3layer
  127: -o ocean -c soma -r 8km -t default
  128: -o ocean -c soma -r 8km -t surface_restoring
  135: -o ocean -c surface_waves -r direct -t 1km
  136: -o ocean -c surface_waves -r thickness_source -t 1km
  137: -o ocean -c tendency_verification -r all -t Redi
  138: -o ocean -c ziso -r 10km -t default
  139: -o ocean -c ziso -r 2.5km -t default
  140: -o ocean -c ziso -r 20km -t default
  141: -o ocean -c ziso -r 20km -t with_frazil
  142: -o ocean -c ziso -r 5km -t default

**Comment by mark-petersen** [comment]
Is `ocean_depreciated` a directory or a tag?

**Comment by mark-petersen** [comment]
@xylar I need to button up these COMPASS PRs for the next E3SM PR, so I'm going to merge this so we at least remove these four unused cases. I am comfortable leaving these other cases in for now.

**Comment by xylar** [comment]
@pwolfram, if you have anything to say about the test cases with "unknown" status above, please post here.  It would still be useful to know.

**Comment by pwolfram** [comment]
@xylar, the "unknown" category above is actually actually used.  Thanks for asking!

**Comment by xylar** [comment]
@pwolfram, to be clear, everything in "unknown" is actively used?  That's fine.  This means I will continue to complain to you when any of these test cases is broken, just so you know.

**Comment by pwolfram** [comment]
I appreciate it @xylar, it is very helpful!

**Pull request merged**
