### PR TITLE
Fix role in mpas_pool_routines.F file

### PR DESCRIPTION
**Pull request by Pranay-Reddy-Kommera**
ROLE 3 includes ROLE_INTEGRATE but the role is not ROLE_INTEGRATE.

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

Enter a description of this PR. This should include why this PR was created, and what it does.

Testing and relations to other Pull Requests should be added as subsequent comments.

See the below examples for more information.
https://github.com/MPAS-Dev/MPAS/pull/930
https://github.com/MPAS-Dev/MPAS/pull/931

### CODE REVIEW

**Comment by mgduda** [comment]
Can you include an explanation in the PR description of why these changes are needed?

**Comment by cponder** [comment]
The OpenACC build (for moist DyCore only) gives a failure if we don't do this:
```
6: hostptr=0x7f77cae33cf0,stride=1,size=4705176,eltsize=4,name=array,flags=0x200=present,async=1,threadid=1
6: FATAL ERROR: data in PRESENT clause was not found on device 7: name=array host:0x7f77cae33cf0
6:  file:/workdir/Source/src/framework/mpas_dmpar.F mpas_dmpar_exch_halo_2d_real_acc line:7392
```
@raghuraj19  -- can you give the structural explanation of what this change does?
Also, you'd already submitted this request elsewhere, right?

**Comment by raghuraj19** [comment]
@Pranay-Reddy-Kommera, @cponder, @mgduda : I have not submitted this pull request. Requested Pranay to do it on my behalf. Here is the description-
"The mpas_pool_get_array functions allocate memory on GPU if and only if the executing MPI rank's role is ROLE_INTEGRATE. Hence, running dycore runs such as baroclinic instability test, which is a hybrid role, leads to failure. This commit addresses the issue by replacing the condition to allocate memory if the role includes ROLE_INTEGRATE, which is the case in hybrid roles, instead of an absolute role."
Does this look good Michael? If so, Pranay can you add the message once Michael approves?

**Comment by Pranay-Reddy-Kommera** [comment]
I am closing this PR and will open a new PR. Raghu has pointed out additional changes which are needed to be included in the same PR.

**Comment by cponder** [comment]
@Pranay-Reddy-Kommera @raghuraj19 
I need these changes merged in, I can't use the
https://github.com/MPAS-Dev/MPAS-Model/pull/887
physics updates without it. Can you get the update filed & closed?

**Comment by Pranay-Reddy-Kommera** [comment]
@cponder I have closed this PR #888 , and opened a new PR #891 with same changes from #888 + few additional changes. The PR #891 is waiting on review from Michael.

**Pull request closed without merging**
