### PR TITLE
E3SM and CESM are now using TRUE|FALSE for compile_threaded

### PR DESCRIPTION
**Pull request by jgfouca**
This change will need to be reflected in the MPAS submodule of E3SM as soon as possible.

### CODE REVIEW

**Comment by mgduda** [comment]
At some point, would it also be worth renaming `Makefile.in.ACME` to `Makefile.in.E3SM`? And, if CESM is no longer being actively tested with MPAS components, would it be worth removing `Makfile.in.CESM`?

**Comment by jgfouca** [comment]
@mgduda , yes and yes. You may want to check with the CESM folks first.

**Comment by jgfouca** [comment]
@jonbob

**Comment by jonbob** [comment]
Thanks @jgfouca

**Comment by mark-petersen** [comment]
@jgfouca please change the target branch to MPAS-Dev:develop

@mgduda and @matthewhoffman this is a framework PR, so I asked you to review. A quick glance is enough.

**Comment by jgfouca** [comment]
@mark-petersen , done.

**Pull request merged**
