### PR TITLE
Modified driver_microphysics to run on CPUs during an OpenACC run.

### PR DESCRIPTION
**Pull request by Pranay-Reddy-Kommera**
This is the 12th PR submitted in a pool of approximately 12 PRs. Might need one additional PR to make any additional changes such that the Dynamics works on GPU with Physics on CPU.
The code changes include appropriate role checks and data transfers to/from CPU and GPU. The code changes allow the 'driver_microphysics' subroutine to execute on the CPU while any other dynamics/physics schemes are executing on the GPU. These temporary changes are required to keep track of any intermediate bugs originating as part of the Physics porting efforts. As the physics porting efforts progress, these changes will be removed if the data transfers become redundant.

Code Execution Status:

1. The code compiles and executes successfully on CPU.
2. Code compiles successfully with Dynamics on GPU and Physics on CPU. Code is not executed as the arrays/variables are not yet updated appropriately (will result in NaNs or incorrect answers) in the Physics. The code should be working by the end of all the PRs.

### CODE REVIEW

**Comment by mgduda** [comment]
@Pranay-Reddy-Kommera On this an other PRs, can you please remove the template text from the PR description, specifically:
```
The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

Enter a description of this PR. This should include why this PR was created, and what it does.
```
and
```
Testing and relations to other Pull Requests should be added as subsequent comments.

See the below examples for more information.
MPAS-Dev/MPAS#930
MPAS-Dev/MPAS#931
```
I realize other projects try to keep the template text in place (and writing a PR description is almost like filling out a form), but the MPAS project prefers a simple paragraph or two to describe the purpose and impact of a PR.

**Comment by Pranay-Reddy-Kommera** [comment]
@mgduda I have removed the template text.
Can you please add others as the reviewers?

**Review by cenamiller — APPROVED** [review]

**Comment by cponder** [comment]
Code-changes look good from my end.
Also I ran the `7.x/benchmark/30km` case with these PRs
```893 895 896 902 903 904 905 906 907 908 909 910 911```
and didn't see any failure issue.

**Review by cponder — APPROVED** [review]

**Comment by cponder** [comment]
Code-changes look good from my end.
Also I ran the 7.x/benchmark/30km case with these PRs
893 895 896 902 903 904 905 906 907 908 909 910 911
and didn't see any failure issue.

**Review by raghuraj19 — APPROVED** [review]

**Review by mgduda — APPROVED** [review]

**Pull request merged**
