### PR TITLE
Add vegetation drag to hurricane case

### PR DESCRIPTION
**Pull request by sbrus89**
Use vegetation drag formula from #632 and #638 to 4km wetting/drying Hurricane Sandy test case

### CODE REVIEW

**Comment by sbrus89** [comment]
Results from 2km mesh:

**Comment by sbrus89** [comment]
Background Manning N values based on land cover classification:
bottomDrag

Mask where vegetation properties are used to compute Mannings N during simulation:
vegetationMask

**Comment by sbrus89** [comment]
@caozd999, please let me know if you have any feedback, thanks!

**Comment by sbrus89** [comment]
Results from 2km mesh:

**Comment by sbrus89** [comment]
Background Manning N values based on land cover classification:
bottomDrag

Mask where vegetation properties are used to compute Mannings N during simulation:
vegetationMask

**Comment by caozd999** [comment]
> @caozd999, please let me know if you have any feedback, thanks!

It looks good to me. Just one quick question: the results labelled by 'MPAS-O_noveg' are the results without considering vegetation drag, and the bottom drag is computed by the background Manning N, is that correct?

**Comment by sbrus89** [comment]
@caozd999, thanks for pointing that out; I should have clarified. The noveg results are using the depth-based mannings N coefficients that Phil implemented in the previous sandy cases.

**Comment by sbrus89** [comment]
Results from 2km mesh:

**Comment by sbrus89** [comment]
Background Manning N values based on land cover classification:
bottomDrag
Mask where vegetation properties are used to compute Mannings N during simulation:
vegetationMask

**Comment by sbrus89** [comment]
Fixes #648

**Comment by sbrus89** [comment]
@mark-petersen, would you mind giving this a quick look-over when you get a chance? Thanks!

**Pull request merged**
