### PR TITLE
Change word ACME to E3SM

### PR DESCRIPTION
**Pull request by mark-petersen**
Changed all remaining text from ACME to E3SM. This includes an init mode flag
`config_vertical_grid='100layerACMEv1'`
that I changed uniformly. No corresponding changes needed for init mode in E3SM.

### CODE REVIEW

**Comment by mark-petersen** [comment]
Compiled with gnu and intel/debug. Passes MPAS-Ocean nightly regression, which includes init mode tests with altered flag
`config_vertical_grid='100layerE3SMv1'`

**Comment by mark-petersen** [comment]
@jonbob this is what you requested in your office this morning. I think a visual inspection is sufficient. Then I'll merge and update the E3SM PR.

Was there anything else you wanted for this Makefile/naming update?

**Comment by jonbob** [comment]
I believe that's it -- I'll look more closely tomorrow morning and see if we can get it merged

**Comment by mark-petersen** [comment]
I ran some E3SM tests as well, passes all.  Checked with @jonbob verbally, merging in.

**Pull request merged**
