### PR TITLE
Remove unused arguments to atm_set_smlstep_pert_variables_work

### PR DESCRIPTION
**Pull request by gdicker1**
This PR removes unused arguments from the atm_set_smlstep_pert_variables_work and atm_set_smlstep_pert_variables routines.

### CODE REVIEW

**Comment by gdicker1** [comment]
Note, I structured this PR so the final two commits (that deal with arguments to the main routine) can be dropped if those changes aren't desired.

**Comment by mgduda** [comment]
In my opinion, having five commits to remove unused arguments and variables may be unnecessary. I'd suggest we consider revising this PR so that it contains just two commits: one commit to make whitespace-only changes to executable code, and a second commit to remove unused arguments and variables (but without any reordering).

**Comment by gdicker1** [comment]
> In my opinion, having five commits to remove unused arguments and variables may be unnecessary...

Agreed. I will rebase to collapse these commits and update the PR description.

**Comment by gdicker1** [comment]
@mgduda, please take another look. Despite the double force-push, the only changes are to the number of commits - no code changes.

**Review by mgduda — CHANGES_REQUESTED** [review]
The changes look good to me. I'd only suggest adding a bit more detail in the message for the whitespace-only commit. Taken on its own, the message doesn't give a good idea of what part of the code is affected in my opinion.

**Comment by gdicker1** [comment]
@mgduda, the force push now uses the commit message

> Whitespace, improve if-statement readability in atm_set_smlstep_pert_variables_work

Please let me know if there's any other adjustments needed!

**Review by mgduda — APPROVED** [review]

**Comment by gdicker1** [comment]
Sub-PRs:
- [ ] https://github.com/EarthWorksOrg/mpas-seaice/pull/19
- [ ] https://github.com/EarthWorksOrg/mpas-ocean/pull/17

**Pull request merged**
