### PR TITLE
1km Delaware Bay hurricane case with synthetic winds and vegetation

### PR DESCRIPTION
**Pull request by sbrus89**
This sets up a 1km resolution Delaware Bay hurricane run in COMPASS. It uses a parametric wind model based off of track information and the formula to calculate manning's n bottom drag from vegetation properties.

### CODE REVIEW

**Comment by sbrus89** [comment]
@mark-petersen, this is COMPASS only with the exception of a new config variable for the hurricane case init mode.

**Comment by mark-petersen** [comment]
@sbrus89 should this be merged? If so I can separate out the compass changes and make a PR to the new compass repo. The init mode changes would remain in here.

**Comment by mark-petersen** [comment]
I changed this to just the init mode piece. I'll make another PR to compass with those parts.

**Review by mark-petersen — APPROVED** [review]
Init mode only. Compiled, tested with regression suite (doesn't make this case). Approved by visual inspection.

**Pull request merged**
