### PR TITLE
Ocean: gpu loop index bug fix

### PR DESCRIPTION
**Pull request by mattdturner**
This PR is a workaround for an issue when running PGI + OpenACC.  It also reduces the number of memory fetches by extracting the max and min loop indices of an inner loop, to now be pre-computed.

Fixes https://github.com/MPAS-Dev/MPAS-Model/issues/850

### CODE REVIEW

**Comment by mattdturner** [comment]
Passes MPAS-O nightly regression suite (BFB) for Intel (Debug and Optimized).  I will test w/ GNU and within E3SM shortly.

**Review by philipwjones — APPROVED** [review]
Approve based on visual inspection and testing on Summit during the debugging of this issue.

**Comment by mattdturner** [comment]
PASSes MPAS-O nightly suite w/ GNU.  

For E3SM...
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi/master:
```

**Comment by mattdturner** [comment]
I just rebased this to `e3sm/develop` to transplant to E3SM.

**Comment by mattdturner** [comment]
Transplanted to https://github.com/E3SM-Project/E3SM/pull/4303

**Pull request closed without merging**
