### PR TITLE
add halo reuse calls to ocean btr subcycle

### PR DESCRIPTION
**Pull request by Larofeticus**
This is PR 1521 which got left behind in the old repo. It's been tested (mostly documented in old PR 1458, there was a memory leak which was found and corrected at that time)

### CODE REVIEW

**Comment by mark-petersen** [comment]
@Larofeticus , thanks for updating.  I had been meaning to move the relevant PRs and issues over.  I changed the merge branch into ocean/develop here.  

The previous memory leak was found and fixed, thanks for that.  This PR needs to be fully tested in E3SM v1.0 with a full-scale simulation for performance gain and any other potential problems.  I am out the next two weeks, not sure if others have time.

**Comment by philipwjones** [comment]
@mark-petersen I've tested this in short runs and found it to be b4b and documented performance gains similar to what @Larofeticus had reported (~13% overall at upper end of scaling curve). In the previous tests, how long did it take before problems (i.e. memory leak) showed up? I can try to set something up in E3SM.

**Comment by jonbob** [comment]
@philipwjones - we could see the memory impact fairly quickly, like a matter of days using the oEC60to30 configuration. If it's still happening, it will show up in the memory footprint printed out in the cpl log. Or I can always run it under the totalview memory debugger (if I can find my notes)....

**Comment by mark-petersen** [comment]
OK, spoke with @jonbob yesterday, and it is time to merge.

**Pull request merged**
