### PR TITLE
Update on SNICAR_AD for snow covered sea ice

### PR DESCRIPTION
**Pull request by chengdang**
This pull request updates the recently added feature snicar:
1. change the config_use_snicar to config_use_snicar_ad, which corresponds to the same config name used in ELM new feature.
2. update the aerosol treatment related to config_use_snicar_ad in ice_shortwave.F90

config_use_snicar_ad is set as false by default.

Code review doc: https://acme-climate.atlassian.net/wiki/spaces/ED/pages/976617535/C1+SNICAR-AD+Shortwave+Radiation+for+Sea+Ice+and+Land

### CODE REVIEW

**Comment by akturner** [comment]
@chengdang:
1) The changes to ice_shortwave only relate to code you added when the snicar code was added? 
2) What is the justification for the name change to _ad? This doesn't mean anything to me.

**Comment by chengdang** [comment]
@akturner 

1. Yes, the changes only relate to snicar code.

2. SNICAR is used in ELM as the default snow shortwave radiative code. The modification I made here is different from SNICAR, and we named it as SNICAR-AD. I also made some changes to ELM to include SNICAR-AD, controlled by a newly added elm namelist variable use_snicar_ad (Pull #2975). So we want to keep the namelist name consistent in both model components.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akturner** [comment]
@chengdang: The _ad addition though isn't very descriptive - what does it mean?

**Comment by chengdang** [comment]
@akturner  AD is short for adding-doubling delta-Eddington method. SNICAR-AD adopts the SNICAR snow and aerosol optical properties, band scheme, and etc, but use the Adding-Doubling method for radiative traders calculation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akturner** [comment]
@chengdang: I think we need a more descriptive name that _ad

**Comment by chengdang** [comment]
@akturner for config name? In our paper (https://doi.org/10.5194/tc-2019-22), SNICAR-AD is well defined and will be used  as the model name in the future, just like SNICAR. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akturner** [comment]
@cheng: Ah, ok, fair enough...

**Comment by akturner** [comment]
Fails the default test:

```
Testing MPAS-Seaice
===================
Test suite:  /Users/akt/Work/MPAS-Seaice/satisfy_pull_requests/pr_chengdang_seaice_cdang_SnicarAD/development/MPAS-Model/testing_and_setup/seaice/testing/testsuites/testsuite.standard.xml

Domains directory:  /Users/akt/Work/MPAS-Seaice/Standalone_sim_configs/test_datasets/20181119/MPAS-Model/testing_and_setup/seaice/testing/DATA

Using configuration standard_physics and domain domain_QU120km...

Test: Regression, Configuration: standard_physics, Domain: domain_QU120km
=========================================================================
FAIL!: Test regression run incomplete

Test: Parallelism, Configuration: standard_physics, Domain: domain_QU120km
==========================================================================
multipleBlocks:  False
FAIL!: Test parallelism run incomplete

Test: Restartability, Configuration: standard_physics, Domain: domain_QU120km
=============================================================================
FAIL!: Test restartability run incomplete

Summary
=======
3 tests (3 failed)
```

Likely you didn't update the namelists in the configurations.

**Comment by chengdang** [comment]
@akturner 
Namelist modified. Please check if it is working now. Thanks.

**Comment by akturner** [comment]
@chengdang: This fails a new test that has been added to the repository since you created your branch. You will need to merge seaice/develop into your branch, fix the issues, then push back to the repository.

```
Testing MPAS-Seaice
===================
Test suite:  ../development/MPAS-Model/testing_and_setup/seaice/testing/testsuites/testsuite.aerosol_shortwave.xml

Domains directory:  /Users/akt/Work/MPAS-Seaice/Standalone_sim_configs/test_datasets/20181119/MPAS-Model/testing_and_setup/seaice/testing/DATA

Using configuration aerosol_shortwave_physics and domain domain_QU240km...

Test: Regression, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
==================================================================================
FAIL!: Test regression run incomplete

Test: Parallelism, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
===================================================================================
multipleBlocks:  False
FAIL!: Test parallelism run incomplete

Test: Restartability, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
======================================================================================
FAIL!: Test restartability run incomplete

Summary
=======
3 tests (3 failed)
```

**Comment by chengdang** [comment]
@akturner branch updated to seaice/develop. Please check it now. Thanks.

**Comment by akturner** [comment]
@chengdang: Still fails these tests - did you test this yourself?

**Comment by chengdang** [comment]
@akturner  config name updated in the new test, please check it now

**Comment by akturner** [comment]
@chengdang: Did you run the four included tests?

**Comment by chengdang** [comment]
@akturner yes I did. This branch passed all tests except for the restartability test of testsuite.aerosol_shortwave.xml. The current seaice/develop branch also fail this test on my machine. For testsuite.aerosol_shortwave, do I need any new domain_QU240km inputs besides the released [testing dataset v1](https://zenodo.org/record/1219191#.XRFHrPlKgWo)?


```
> (py2) [cdang5@skyglow testing]$ ./test_mpas-seaice.py -d $dev_repo -b $base_repo -t ./testsuites/testsuite.aerosol_shortwave.xml
> 
> Testing MPAS-Seaice
> ===================
> Test suite:  ./testsuites/testsuite.aerosol_shortwave.xml
> 
> Domains directory:  /home/cdang5/Segate5T/MPAS/case_runfile/MPAS-Seaice_test_dataset_V1
> 
> Using configuration aerosol_shortwave_physics and domain domain_QU240km...
> 
> Test: Regression, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
> ==================================================================================
> No non-contents errors
> PASS: Test regression passed
> 
> Test: Parallelism, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
> ===================================================================================
> multipleBlocks:  False
> No non-contents errors
> PASS: Test parallelism passed
> 
> Test: Restartability, Configuration: aerosol_shortwave_physics, Domain: domain_QU240km
> ======================================================================================
> No non-contents errors
> FAIL!: Test restartability failed
> 
> Summary
> =======
> 3 tests (2 passed, 1 failed)
```

**Comment by akturner** [comment]
@chengdang: Why did this test fail?

**Comment by chengdang** [comment]
@akturner that is my question since this test fails for seaice/develop too on my machine. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akturner** [comment]
@chengdang did you look in the test run directory and study the log files?

**Comment by chengdang** [comment]
@akturner This is the log file under the testing folder restartability_1.aerosol_shortwave_physics.domain_QU240km

```
...
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
 IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Return code: 0
Arrays uVelocity differ!
Arrays iceVolumeCategory differ!
Arrays iceSalinity differ!
Arrays mobileFraction differ!
Arrays surfaceTemperature differ!
Arrays stress12var differ!
Arrays levelIceArea differ!
Arrays snowVolumeCategory differ!
Arrays pondSnowDepthDifference differ!
Arrays pondArea differ!
Arrays oceanStressCellV differ!
Arrays oceanStressCellU differ!
Arrays snowEnthalpy differ!
Arrays iceEnthalpy differ!
Arrays levelIceVolume differ!
Arrays iceAreaCategory differ!
Arrays verticalAerosolsConc differ!
Arrays pondLidThickness differ!
Arrays brineFraction differ!
Arrays pondDepth differ!
Arrays vVelocity differ!
Arrays airOceanDragCoefficientRatio differ!
Arrays stress11var differ!
Arrays stress22var differ!
Arrays shortwaveScalingFactor differ!
Arrays iceAge differ!
Arrays seaSurfaceTemperature differ!
No non-contents errors
Test restartability failed
```

**Comment by akturner** [comment]
If you do a trial merge of your branch into seaice/develop do you still get this test fail? NB do a local trial merge and DO NOT push that anywhere. Throw it away after

**Comment by chengdang** [comment]
Yes. With either current seaice/develop, or seaice/develop + SNICAR_AD merge, this test fails with the same log information.

**Comment by akturner** [comment]
@chengdang: Are there any error messages in the MPAS log file?

**Comment by chengdang** [comment]
@akturner  there is no error message in both /restartability_1.aerosol_shortwave_physics.domain_QU240km**/base/log.seaice.0000.out**
 and
/restartability_1.aerosol_shortwave_physics.domain_QU240km**/restart/log.seaice.0000.out**
```
 -----------------------------------------
 Total log messages printed:
    Output messages =                 1163
    Warning messages =                   5
    Error messages =                     0
    Critical error messages =            0
 -----------------------------------------
```

I did this test again just now, and it fails with the same information.

**Comment by akturner** [comment]
@chengdang: Can you send me the MPAS log files?

**Pull request merged**
