### PR TITLE
Update threading in ocean EOS

### PR DESCRIPTION
**Pull request by amametjanov**
Update threading in ocean EOS to fix issues in multi-threaded runs. Tested with `SMS_P12x2.ne4_oQU240.A_WCYCL1850.anvil_intel.allactive-mach_mods`.

[BFB]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@amametjanov Thanks for adding code. Before this PR, does the code potentially cause an incorrect answer, or just slower performance with threading?

@philipwjones how does this overlay with your performance work on EOS - any preferred order for merging?

**Comment by philipwjones** [comment]
@mark-petersen This is fixing a bug in my new EOS version. I had placed allocates of some temps within an omp single construct when shared allocated arrays must be allocated by the master thread. For some reason, a lot of machines were fine with the version I had committed, but it correctly failed on the sandiatoss machine during testing.  This should fix that issue while still retaining the performance improvement. @amametjanov can correct any misstatement or add any additional detail.  I reviewed the mods - they simply replace the single directive with a master directive and add the required barriers that were implicit in single - and this should be merged after my earlier (reverted) PR for the EOS change.

**Comment by amametjanov** [comment]
Yes, it should go after Phil's PR.

**Comment by mark-petersen** [comment]
These are next in line:
Remerge https://github.com/MPAS-Dev/MPAS-Model/pull/69
Merge this PR.
Test in MPAS-O, then E3SM. Is there anything I should know, or is it all ready to go?

**Comment by philipwjones** [comment]
Should all be good to go.

**Comment by mark-petersen** [comment]
Sorry for the delay. https://github.com/E3SM-Project/E3SM/pull/2843 got higher priority. I will do all the threading-related PRs after that, so if you have other changes or potential PRs to add for threading, now is a good time to make them.

**Comment by mark-petersen** [comment]
@amametjanov this PR is on top of https://github.com/MPAS-Dev/MPAS-Model/pull/69 which was reverted. I'd like to make this PR the re-merge of the #69 commits and your commit on top of it, since they are all related.  May I do that, and then push to this branch?
You need to change the target branch of this PR to `ocean/develop`.

**Comment by amametjanov** [comment]
No problem. Done.

**Comment by mark-petersen** [comment]
OK, I rebased, added #69, and put the 'fix' commit after that. @philipwjones and @amametjanov please browse the code and see if it looks right.

**Pull request merged**
