### PR TITLE
Fix  ISOMIP+ viz scripts

### PR DESCRIPTION
**Pull request by xylar**
This merge fixes a few complaints from `xarray` in the ISOMIP+ viz package.

### CODE REVIEW

**Comment by xylar** [comment]
@cbegeman, once you join this repo, I will add you as a reviewer.

**Comment by xylar** [comment]
@cbegeman pointed out and I confirmed that we're seeing the following error during the runs, seemingly related to appending to `timeSeriesStatsGlobal`:
```
PIO: ERROR: Changing the define mode for file (analysis_members/globalStats.0001-01-01_00.00.00.nc) failed. Low-level I/O library API failed. NetCDF: Operation not allowed in data mode (error num=-38), (/usr/projects/climate/SHARED_CLIMATE/software/grizzly/pio/1.10.1/intel-19.0.4/openmpi-2.1.2/scorpio/src/clib/pioc_support.c:3163)
```

**Comment by xylar** [comment]
I'm seeing warnings in the viz:
```
/lustre/scratch4/turquoise/.mdt1/xylar/isomip_plus_Ocean0/ocean/isomip_plus/2km/Ocean0/forward/viz/__main__.py:39: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  ds = xarray.open_mfdataset('{}/timeSeriesStatsMonthly*.nc'.format(folder),
```
This is, indeed, something that needs to be fixed.  We just need to add `combine='nested'` to all the `open_mfdataset()` calls.

**Comment by xylar** [comment]
@cbegeman, I realized that this update is silly.  I already put this tutorial into the documentation, and that is where it should be updated.  I'm going to make a PR for that instead.

**Comment by xylar** [comment]
We still want the fixes to the viz package here.  The rest has been replaced with #653

**Comment by mark-petersen** [comment]
@cbegeman can you confirm that this fixes the problem you encountered?

**Comment by mark-petersen** [comment]
Rebased. This is so small, I'll go ahead and merge with the bunch this morning.

**Pull request merged**
