### PR TITLE
Adds synthetic hurricane to 4km Delaware

### PR DESCRIPTION
**Pull request by pwolfram**
Adds synthetic 4km Delaware case for both non-flooding and flooding (WD: wetting and drying) cases.

### CODE REVIEW

**Comment by pwolfram** [comment]
# Testing 4km case to find wind forcing bug

Case is stable until last part of run, where it ultimately blows up due to improper wind forcing.
```
 Doing timestep 2012-01-12_23:00:00                                                             
 Verifying that cells are not dry...                                                            
 Minimum thickness is 0.100108841907758E-01.                                                    
 Done verifying that cells are wet.                                                             
  -- Reducing field latCell with nElements = 182                                                
  -- Reducing field lonCell with nElements = 182                                                
  -- Reducing field ssh with nElements = 182                                                    
 Doing timestep 2012-01-12_23:00:25                                                             
 Verifying that cells are not dry...                                                            
 Minimum thickness is 0.100108841907758E-01.                                                    
 Done verifying that cells are wet.                                                             
CRITICAL ERROR: ERROR: State validation failed. See block stats files for more information.     
```
![8534720](https://user-images.githubusercontent.com/4295853/86499748-18d40880-bd4a-11ea-8f07-bc1ec2b56b15.png)

## Broken wind forcing
```python
ipython
In [7]: import xarray as xr                                                                                                                                                                                                                                                                                                  

In [8]: ds = xr.open_dataset('atmospheric_forcing.nc')                                                                                                                                                                                                                                                                       

In [9]: ds.windSpeedU.isel(Time=-1)                                                                                                                                                                                                                                                                                          
Out[9]: 
<xarray.DataArray 'windSpeedU' (nCells: 15404)>
array([9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36, 9.96921e+36,
       9.96921e+36])
Dimensions without coordinates: nCells

In [10]: ds.windSpeedU.isel(Time=-2)                                                                                                                                                                                                                                                                                         
Out[10]: 
<xarray.DataArray 'windSpeedU' (nCells: 15404)>
array([-3.588561,  1.057031,  0.461513, ..., -6.030833,  6.671099,  6.515482])
Dimensions without coordinates: nCells
In [11]: ds.xtime[-2:]                                                                                                                                                                                                                                                                                                       
Out[11]: 
<xarray.DataArray 'xtime' (Time: 2)>
array([b'2012-01-12_23:00:00                                             ',
       b'2012-01-13_00:00:00                                             '],
      dtype='|S64')
Dimensions without coordinates: Time

```

There  is a bug in the wind forcing file for the last time slice, which corresponds to the synthetic hurricane forcing generation code.  The images below from paraview also illustrate:
![image](https://user-images.githubusercontent.com/4295853/86499898-cf37ed80-bd4a-11ea-97ae-7f0b46930550.png)

![image](https://user-images.githubusercontent.com/4295853/86499885-bdeee100-bd4a-11ea-8637-a875aca6dcec.png)

**Comment by pwolfram** [comment]
Synthetic hurricane bug documented at https://github.com/MPAS-Dev/MPAS-Model/issues/625

**Comment by pwolfram** [comment]
Code for 2km case in https://github.com/MPAS-Dev/MPAS-Model/pull/491 likely has a bug that is unrelated to the synthetic hurricane storm because failed run here is due to spurious wind forcing in input file as detailed above.  Run in #491 did not fail following `2012-01-12_23:00:00` as happened here but instead failed near start of `01-12`, not end.

**Comment by sbrus89** [comment]
> Code for 2km case in #491 likely has a bug that is unrelated to the synthetic hurricane storm because failed run here is due to spurious wind forcing in input file as detailed above. Run in #491 did not fail following `2012-01-12_23:00:00` as happened here but instead failed near start of `01-12`, not end.

I think this may be due to #648.

**Pull request merged**
