### PR TITLE
Updating COMPASS ocean test cases based on mpas_tools reorg

### PR DESCRIPTION
**Pull request by xylar**
This merge updates COMPASS ocean test cases to make them compatible with https://github.com/MPAS-Dev/MPAS-Tools/pull/314.  This includes:
* Changing `define_base_mesh.py` to `build_base_mesh.py`, which calls `build_spherical_mesh()` explicitly (whereas the old `build_mesh` called the `cellWidthVsLatLon()` from `define_base_mesh`, which created a problematic import of a local module within `build_mesh`).
* Update imports to handle move of `coastal_tools` (other than `signed_distance` functions), `inject_bathymetry`, `inject_meshDensity` and `inject_preserve_floodplain` to `mpas_tools.ocean`

Affected test cases are (check mark indicates they have been updated):
- [x] `Gaussian_hump/USDEQU120cr10rr2/build_mesh/`
- [x] `coastal/Maine/init`
- [x] `coastal/USDEQU120cr10rr2/build_mesh`
- [x] `global_ocean/ARM60to10/init`
- [x] `global_ocean/CA120to3/build_mesh`
- [x] `global_ocean/EC60to30/init`
- [x] `global_ocean/EC60to30wISC/init`
- [x] `global_ocean/HI120to12/build_mesh`
- [x] `global_ocean/QU240/init`
- [x] `global_ocean/QU240wISC/init`
- [x] `global_ocean/SO60to10wISC/init`
- [x] `global_ocean/WC12/init`
- [x] `global_ocean/WC14/init`
- [x] `hurricane/USDEQU120at30cr10rr2/build_mesh`
- [x] `hurricane/USDEQU120at30cr10rr2WD/build_mesh`
- [x] `hurricane/USDEQU120at30cr10rr2WD_veg/build_mesh`
- [x] `hurricane/USDEQU240at60cr20rr4/build_mesh`
- [x] `hurricane/USDEQU240at60cr20rr4WD/build_mesh`
- [x] `hurricane/USDEQU240at60cr20rr4WD_veg/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr1/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr100WD/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr1WD/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr1WD_veg/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr250WD/build_mesh`
- [x] `hurricane/USDEQU60at15cr5rr500WD/build_mesh`
- [x] `tides/USDEQU120at30cr10/build_mesh`

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

My testing for now is only to run the `base_mesh` part of each test case on my laptop.  I am not checking if they are bit-for-bit (in fact, with the change in Earth radius that this PR introduces, I don't expect them to be bit-for-bit).

A check mark in the list above indicates that `base_mesh` ran successfully.

**Comment by xylar** [comment]
## Testing on Grizzly

This won't start until #563 is merged

- [ ] `Gaussian_hump/USDEQU120cr10rr2/build_mesh/`
- [ ] `coastal/Maine/init`
- [ ] `coastal/USDEQU120cr10rr2/build_mesh`
- [ ] `global_ocean/ARM60to10/init`
- [ ] `global_ocean/CA120to3/build_mesh`
- [ ] `global_ocean/EC60to30/init`
- [ ] `global_ocean/EC60to30wISC/init`
- [ ] `global_ocean/HI120to12/build_mesh`
- [ ] `global_ocean/QU240/init`
- [ ] `global_ocean/QU240wISC/init`
- [ ] `global_ocean/SO60to10wISC/init`
- [ ] `global_ocean/WC12/init`
- [ ] `global_ocean/WC14/init`
- [ ] `hurricane/USDEQU120at30cr10rr2/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD_veg/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr100WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr250WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr500WD/build_mesh`
- [ ] `tides/USDEQU120at30cr10/build_mesh`

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, I have a test compass environment, `test_compass_0.1.10` on Grizzly for testing this branch and  MPAS-Dev/MPAS-Tools#314.  The procedure would be very similar to what we have done for #563 and the same tests are likely appropriate.

This new environment includes some new geometric features so you will not be able to sue your old tests as a baseline.  (These new features are included in the release version of `compass_0.1.9`, though they were not in the test version `test_compass_0.1.9` that we used yesterday.)

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, I'm starting to test this now.  Just a heads up.

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, I realized that my tests for this PR are non-bit-for-bit because I changed the Earth radius in MPAS-Dev/MPAS-Tools#314.  I'm going to pull that change out of MPAS-Dev/MPAS-Tools#314 for now and make a new test environment without that change.  Then, we can have a separate PR to MPAS-Tools just for that non-bit-for-bit change before we do the next `mpas_tools`/`compass` release.  Again, just a heads up.

**Comment by xylar** [comment]
I would like to keep `ocean/coastal` off limits to adding new test cases that use `mpas_tools.mesh.creation` until this goes in.  @sbrus89 and @proteanplanet, what are the plans for the remaining development on `ocean/coastal` before you stop using it entirely?  If they don't relate to this PR, you can hard-reset `ocean/coastal` to `ocean/develop` and proceed as far as I'm concerned.

**Comment by xylar** [comment]
@sbrus89 and @mark-petersen, all my testing has now passed bit-for-bit.  I tested all the cases listed above through `initial_state` (or the last step they have if there isn't an `initial_state` step).

I also tested forward mode on the QU240 and QU240wISC runs, comparing the current `ocean/develop` against a test merge of this branch into `ocean/develop` and those were also bit-for-bit.

Getting this tested and merged is somewhat of a priority because it is holding up #668, #669 and #671.  Also, I will do a second PR related to changing the Earth radius.  That one is not bit-for-bit so testing will be trickier, and we should discuss how to do it.

Please let me know what the schedule would be for testing and merging this.  I understand that there are also other high priority items at the moment, but the EC30to60km meshes are needed as soon as possible so they can be tested and approved for the v2 release at the end of this month.

**Review by mark-petersen — APPROVED** [review]
Merged #577 and #680 locally. Ran nightly regression suite with `test_compass_0.1.10`, was bfb with `ocean/develop` on all tests. Then ran with `test2_compass_0.1.10` and init for QU240 was not bfb with previous, as expected.

I then ran EC60to30 and EC60to30wISC. All ran fine. EC60to30 prep-spinup1 was within 1% global kinetic energy after 6 days as previous ocean/develop. EC60to30wISC ran through ssh iterations and test. I cherry-picked #676 on the before and after on all spin-ups.

**Comment by mark-petersen** [comment]
For EC60to30, here is the initial state just before the coastal merge and after #577 and #680. There are minor differences, but it looks reasonable.
initial_state
initial_state

**Review by sbrus89 — APPROVED** [review]
Approved, based on inspection of `hurricane/USDEQU240at60cr20rr4WD` case.

**Comment by mark-petersen** [comment]
Thanks for your work on this @xylar!

**Comment by xylar** [comment]
Thanks very much @sbrus89 and @mark-petersen for the review and for your testing.

**Pull request merged**
