### PR TITLE
New Mesh: EC30to60kmL60E3SMv2r02 and change to 60 layers as default

### PR DESCRIPTION
**Pull request by vanroekel**
This PR bumps the revision number on the new 6030 grid, and includes all improvements to islands, channels, and passages for v2 of the E3SM water cycle campaign.

The default number of vertical layers is also switched to 60.

### CODE REVIEW

**Comment by xylar** [comment]
Looks good so far.  If you make `config_initial_state.xml` a copy rather than a symlink, you can edit it to change the initial condition data set to be the 1900 MetOffice data set you mentioned.

**Comment by xylar** [comment]
> If you make config_initial_state.xml a copy rather than a symlink, you can edit it to change the initial condition data set to be the 1900 MetOffice data set you mentioned.

Oh, right, that's for r04.

**Comment by mark-petersen** [comment]
@vanroekel FYI I was testing the current EC60to30 and the `prep_spin_up1` step was having some trouble crashing. I'm testing with a smaller timestep now.

**Comment by mark-petersen** [comment]
@vanroekel I tried a shorter time step and larger Rayleigh damping, but the EC60to30 still crashes in  `prep_spin_up1`. Did you run that in the last few weeks for your recent low-res test, and did you adjust something to get it started?

**Comment by vanroekel** [comment]
@mark-petersen I don't remember changing anything for pre_spinup1.  I'll try today with your culled mesh and let you know.

**Comment by mark-petersen** [comment]
I'll work on it today too. It's not clear if this is a settings problem or actual bug.

**Comment by vanroekel** [comment]
@mark-petersen when does the 6030 pre_spinup1 crash and what is the error output?  I just started that run and it has run 1 day so far.

**Comment by vanroekel** [comment]
@xylar I think I have the sequence of PRs for the new mesh as close as I can for now.  ping me when you are ready to work on these and I can jump back in.

**Comment by xylar** [comment]
@vanroekel, the plan of swapping the symlinks for 60 and 64 layers isn't going to work quite right.  You also renamed the steps in their respective files in `testing_and_setup/compass/ocean/global_ocean/config_files/`, which is going to break other test cases that use these symlinks.

My suggestion is just to make copies of these files and modify them in the test case itself.

**Comment by vanroekel** [comment]
@xylar good point, it made the other PRs easier and seems much safer here.  I'll make the fix.

**Comment by xylar** [comment]
I tested a rebase of this on #577 and there were no conflicts (unsurprisingly).  I also don't think that PR will change the results here, those are organizational changes that should be bit-for-bit.  So I think this can proceed without worrying about those changes.  Likewise, it shouldn't matter if we use the current `compass` environment (0.1.9)  or the one I'm working on for that PR (0.1.10) because the changes are only organizational.

**Comment by xylar** [comment]
@vanroekel, could you rebase onto the current `ocean/develop` following @mark-petersen's recent merges?  You shouldn't have any conflicts but it will make sure your build is compatible with the latest compass and has the fixes to the plotting script in `initial_state` that were giving me trouble before.

**Comment by vanroekel** [comment]
Of course., done.

**Comment by vanroekel** [comment]
@mark-petersen and @xylar any update on when this will be ready so I can spin up the mesh for WC runs?

**Comment by mark-petersen** [comment]
I will merge #577 and #680 in a bit. Xylar will rebase and check over these mesh PRs, and we can merge tomorrow morning.

**Comment by vanroekel** [comment]
okay great.  Thanks for the update.

**Comment by xylar** [comment]
@vanroekel, I'm getting started on this as soon as I install an update `compass` environment on all our machines.

**Review by xylar — APPROVED** [review]
I merged this with #676 and `ocean/develop` and tested on Grizzly with Intel and SCORPIO.  The spin-up went fine. Results are here:
```
/lustre/scratch4/turquoise/xylar/test_EC30to60kmL60E3SMv2r02/
```
I verified that the e3sm_coupling step ran fine, showing the expected number of layers an mesh name:
```
- ice_shelf_cavities set to False
- author's name autodetected from git config: Xylar Asay-Davis
- author's name specified in config file: xylar@lanl.gov
- date string autodetected from today's date: 200904
- creation date autodetected from today's date: 09/04/2020 06:07:38
- maximum ocean depth autodetected mesh file: 5500.0
- number of vertical levels in the ocean autodetected mesh file: 60
- mesh long name specified in config file: EC30to60kmL60E3SMv2r02
- mesh short name specified in config file: EC30to60E2r02
```

Here are a few images showing the resulting T, S, bottom depth and maxLevelCell as sanity checks:
temperature
salinity
bottomDepth
maxLevelCell

**Comment by xylar** [comment]
I'm rerunning with `gnu` to see if I get the same problems above as @vanroekel.  I'm also moving on to #669

**Comment by mark-petersen** [comment]
tested with gnu 6.4.0 optimized on badger. Results are here:
```
/lustre/scratch3/turquoise/mpeterse/runs/200904_EC30to60kmL60E3SMv2r02_PR668_final/ocean/global_ocean/EC60to30
```
ran through `prep_spin_up1` (10 days) and `simulation` (10 more days).


<details>
<summary> mesh and IC histogram images: </summary> <p>

cellWidthGlobal
initial_state

</details>

**Comment by mark-petersen** [comment]
<details>
<summary> mesh images </summary> <p>

image

image
image
image
</details>

<details>
<summary> T&S after 20 day spinup </summary> <p>

image
image
image
image
</details>

these are at
```
/lustre/scratch3/turquoise/mpeterse/runs/200904_EC30to60kmL60E3SMv2r02_PR668_final/ocean/global_ocean/EC60to30/spin_up/simulation/vtk*
```

**Review by mark-petersen — APPROVED** [review]
Everything looks good from init and spin-up on badger with `gnu 6.4.0` and `compass_0.1.10`

**Comment by xylar** [comment]
After @mark-petersen merges this, I'm going to rebase #669 so the PR is cleaner.  Is that okay, @vanroekel?

**Pull request merged**
