### PR TITLE
add dam break test case

### PR DESCRIPTION
**Pull request by caozd999**
Adds dam break test case for comparison against experimental and ROMS results to ensure that MPAS-O flooding wave is accurate.

### CODE REVIEW

**Comment by pwolfram** [comment]
@caozd999, we do want to submit a PR and you should be able to reopen.  Thanks for taking the initiative to start the PR.

How about cherry-picking `208bf289051d30d20554288a7c658f65648487b6` and `d242282eea8cdd820317dbfd3ff1a5becd9d1a67` from https://github.com/pwolfram/MPAS-Model/commits/sbrus89/time-varying-wind-unsquashed_wetting onto the latest branch of ocean/develop and making sure it works?

**Comment by xylar** [comment]
@pwolfram, I talked with @caozd999 about this this morning.  I agree, cherry-picking only a few necessary commits is the right way to do this.  I'm happy to help with the process as needed.

**Comment by pwolfram** [comment]
@caozd999, does this make sense?  Please go ahead and do this and once you confirm the code builds and runs against your test case I will review.  Please feel free to include your data sources and comparison script in this PR too as there is not a commit for that.  Please let me and @xylar as you have questions about how to go about doing this PR.

**Comment by caozd999** [comment]
@pwolfram @xylar Thanks. I will work on it today.

**Comment by caozd999** [comment]
@xylar and I worked on the cherry-pick d242282eea8cdd820317dbfd3ff1a5becd9d1a67, and we found merge conflicts in `testing_and_setup/compass/ocean/jigsaw_to_MPAS/inject_bathymetry.py` which we don't know how to fix. Could you do the rebase on the ocean/develop on that commit please?

**Comment by xylar** [comment]
@pwolfram, I think the problem is that @mark-petersen has made changes to that file on `ocean/develop` and you made others on the wetting-and-drying branch (among the 198 files you altered there! :-)), and it wasn't at all obvious how to resolve the conflicts.  But it was a really good demo of `git cherry-pick` for @caozd999 to learn from!

**Comment by xylar** [comment]
@pwolfram, I believe @caozd999 could use your help with this one.  Just wanted to ping you both to make sure this doesn't get dropped entirely.

**Comment by pwolfram** [comment]
@xylar, the issue is this requires wetting and drying.  I'll sort this out and we should merge this case under that umbrella.

**Comment by xylar** [comment]
Should this PR be closed since my understanding is that #54 brings in this functionality?

**Comment by pwolfram** [comment]
Yes

**Pull request closed without merging**
