### PR TITLE
Modified lagged_radiation_sw to run on CPUs during an OpenACC run.

### PR DESCRIPTION
**Pull request by Pranay-Reddy-Kommera**
This is the 1st PR submitted in a pool of approximately 12 PRs. 
The code changes include appropriate role checks and data transfers to/from CPU and GPU. The code changes allow the 'lagged_radiation_sw_to_MPAS' subroutine to execute on the CPU while any other dynamics/physics schemes are executing on the GPU. These temporary changes are required to keep track of any intermediate bugs originating as part of the Physics porting efforts. As the physics porting efforts progress, these changes will be removed if the data transfers become redundant.
Code Execution Status:
1. The code compiles and executes successfully on CPU.
2. Code compiles successfully with Dynamics on GPU and Physics on CPU. Code is not executed as the arrays/variables are not yet updated appropriately (will result in NaNs or incorrect answers) in the Physics. The code should be working by the end of all the PRs.

### CODE REVIEW

**Comment by Pranay-Reddy-Kommera** [comment]
@mgduda @raghuraj19 @cponder @supreethms1809 @cenamiller 
I did not knew how to add reviewers, so tagging all of you in the comment to review the code and respond.
@mgduda Do we need to have permission to add reviewers to the PRs. If so and if possible, could you please provide us permission to add reviewers to the PRs.

**Comment by mgduda** [comment]
@Pranay-Reddy-Kommera Let me see if I can figure out how to add permissions for you all to add reviewers to PRs. In the meanwhile, it's easy enough for me to add reviewers as I see new PRs appear.

**Review by cenamiller — APPROVED** [review]

**Review by mgduda — APPROVED** [review]

**Comment by cponder** [comment]
Code-changes look good from my end.
Also I ran the `7.x/benchmark/30km` case with these PRs
```893 895 896 902 903 904 905 906 907 908 909 910 911```
and didn't see any failure issue.

**Review by cponder — APPROVED** [review]

**Review by raghuraj19 — APPROVED** [review]

**Review by supreethms1809 — APPROVED** [review]

**Comment by Pranay-Reddy-Kommera** [comment]
I have reverted 'role_includes' to 'role_is'. Please review the code.

**Review by mgduda — CHANGES_REQUESTED** [review]
@Pranay-Reddy-Kommera With your latest commit, the code doesn't compile:
```
mpif90 -D_MPI -DUSE_PIO2 -DCORE_ATMOSPHERE -DMPAS_NAMELIST_SUFFIX=atmosphere -DMPAS_EXE_NAME=atmosphere_model -DSINGLE_PRECISION -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=v7.0-399-g6019027 -Dmpas  -O3 -m64 -ffree-line-length-none -fconvert=big-endian -ffree-form -c mpas_atmphys_driver_radiation_sw.F -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I/home/duda/local/libs-gnu-11.1.0/include -I./physics_wrf -I.. -I../../framework -I../../external/esmf_time_f90
mpas_atmphys_driver_radiation_sw.F:816:17:

  816 |  if (mpas_cpl%is(ROLE_INTEGRATE)) then
      |                 1
Error: ‘is’ at (1) is not a member of the ‘mpas_coupler_type’ structure
mpas_atmphys_driver_radiation_sw.F:819:4:

  819 |  endif
      |    1
Error: Expecting END SUBROUTINE statement at (1)
mpas_atmphys_driver_radiation_sw.F:821:17:

  821 |  if (mpas_cpl%is(ROLE_INTEGRATE) .or. &
      |                 1
Error: ‘is’ at (1) is not a member of the ‘mpas_coupler_type’ structure
mpas_atmphys_driver_radiation_sw.F:837:4:

  837 |  end if
      |    1
Error: Expecting END SUBROUTINE statement at (1)
mpas_atmphys_driver_radiation_sw.F:839:17:

  839 |  if (mpas_cpl%is(ROLE_INTEGRATE)) then
      |                 1
Error: ‘is’ at (1) is not a member of the ‘mpas_coupler_type’ structure
mpas_atmphys_driver_radiation_sw.F:842:4:

  842 |  endif
      |    1
Error: Expecting END SUBROUTINE statement at (1)
```

**Comment by Pranay-Reddy-Kommera** [comment]
I have fixed the compilation error. It was a typo. I have replaced the 'mpas_cpl%is' with 'mpas_cpl%role_is'.

**Comment by mgduda** [comment]
@Pranay-Reddy-Kommera If you don't mind, I'll squash the last two commits on your branch (c669b2c8 and 1f032b09) and push the result back to your fork to keep the commit history a bit cleaner. Just let me know if you'd prefer I don't modify the commit history of the branch.

**Comment by Pranay-Reddy-Kommera** [comment]
@mgduda I am fine with squashing the last two commits. Please go ahead and modify the commit history of the branch.

**Pull request merged**
