### PR TITLE
Optimization of NOAH LSM Part 1

### PR DESCRIPTION
**Pull request by Pranay-Reddy-Kommera**
This PR contains changes to the `module_sf_noahlsm.F` file. The OpenACC NOAH LSM related subroutines are optimized to improve the performance.

### CODE REVIEW

**Comment by mgduda** [comment]
@Pranay-Reddy-Kommera The description of this PR says "Please do not merge this PR.". If you'd like this PR to be reviewed and merged, could you please update the description?

**Comment by Pranay-Reddy-Kommera** [comment]
@mgduda I have updated the description

**Review by mgduda — CHANGES_REQUESTED** [review]
There are some compilation errors that need to be addressed before we could consider merging this PR.

**Comment by PranayReddyKommera** [comment]
@mgduda I have pushed changes to fix the rank mismatch of STCOUT variable in module_sf_noahlsm.F file

**Review by mgduda — APPROVED** [review]

**Pull request merged**
