### PR TITLE
Rename 60-layer initial state for EC60to30wISC

### PR DESCRIPTION
**Pull request by xylar**
One more fix not picked up in #502

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen, okay my testing is far enough that I'm reasonably sure this is working and can be merged now.  (I'm in day 15 of a 20-day spin-up of EC60to30wISC.)

**Comment by mark-petersen** [comment]
I'll test in a fresh directory this time - that's what caused my last 'false positive'. I'll copy over the base_mesh and culled_mesh to save time.

**Comment by xylar** [comment]
No need to test spin-up like I did but make sure `ssh_adjustment` gets through at least one iteration.

**Comment by mark-petersen** [comment]
On merge commit 433cce8a3, here is the 60 layer EC60to30wISC:
initial_state_EC60to30wISC_60layer
@xylar I ran it all the way through spin-up here:
```
/lustre/scratch4/turquoise/mpeterse/runs/200402_EC60to30wISC/ocean/global_ocean/EC60to30wISC
```
Feel free to use that or redo it.

**Pull request merged**
