### PR TITLE
Switch from Travis-CI to Azure Pipelines

### PR DESCRIPTION
**Pull request by xylar**
We were having difficulty with Travis-CI and Azure Pipelines may be faster and more flexible in any case.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, @mark-petersen and @sbrus89, I'm mostly making you aware of this change to a different CI. Please let me know if you have questions or concerns.  I would like to merge to `develop` soon and then have you merge `develop` to the respective `xxx/develop` branches when the timing is right for E3SM.  I can't really proceed with writing better documentation for `ocean/develop` until that happens.

**Review by mark-petersen — APPROVED** [review]
@xylar thanks for being so forward-thinking about all this. I obviously have a lot to learn. Let's go ahead and merge in this morning with the COMPASS PRs.

**Review by sbrus89 — APPROVED** [review]
@xylar, Thanks for your work on this!

**Comment by mark-petersen** [comment]
merged develop into ocean/develop as well, so this is available.

**Pull request merged**
