### PR TITLE
Update Earth radius to the CIME value

### PR DESCRIPTION
**Pull request by xylar**
Currently, COMPASS uses 3 different Earth radii.  With this merge and a corresponding update to MPAS-Tools, all Earth radii are the CIME value.

This PR addresses MPAS-Dev/MPAS-Model#549 along with https://github.com/MPAS-Dev/MPAS-Tools/pull/341.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, this PR will be rebased once #577 is merged.  This PR is needed before #668, #669, and #671 can go in, so it is also a priority.

**Comment by xylar** [comment]
These changes are not bit-for-bit so I could use some help thinking about how to test them.

**Comment by xylar** [comment]
## Testing on Grizzly

Verification that the test runs to completion:

- [ ] `Gaussian_hump/USDEQU120cr10rr2/build_mesh/`
- [ ] `coastal/Maine/init`
- [ ] `coastal/USDEQU120cr10rr2/build_mesh`
- [ ] `global_ocean/ARM60to10/init`
- [ ] `global_ocean/CA120to3/build_mesh`
- [ ] `global_ocean/EC60to30/init`
- [ ] `global_ocean/EC60to30wISC/init`
- [ ] `global_ocean/HI120to12/build_mesh`
- [ ] `global_ocean/QU240/init`
- [ ] `global_ocean/QU240wISC/init`
- [ ] `global_ocean/SO60to10wISC/init`
- [ ] `global_ocean/WC12/init`
- [ ] `global_ocean/WC14/init`
- [ ] `hurricane/USDEQU120at30cr10rr2/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD_veg/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr500WD/build_mesh`
- [ ] `tides/USDEQU120at30cr10/build_mesh`

**Comment by xylar** [comment]
`global_ocean/SO60to10wISC/init` is failing during SSH adjustment.  I wonder if this might be related to #676.  I'm going to see if it works with a test merge of that PR.

**Review by mark-petersen — APPROVED** [review]
See https://github.com/MPAS-Dev/MPAS-Model/pull/577#pullrequestreview-482218430

**Comment by mark-petersen** [comment]
Yes, I cherry-picked #676 for spin-up steps. I'll get that one on soon.

**Comment by mark-petersen** [comment]
See initial state plots: https://github.com/MPAS-Dev/MPAS-Model/pull/577#issuecomment-686799241

**Review by sbrus89 — APPROVED** [review]
Approved, based on inspection of `hurricane/USDEQU240at60cr20rr4WD` case.

**Comment by xylar** [comment]
Thanks very much @sbrus89 and @mark-petersen for the review.

**Pull request merged**
