### PR TITLE
Added OpenACC directives to Surface Layer model, for GPU excecution. (Superceded by PR #928)

### PR DESCRIPTION
**Pull request by cponder**
Added OpenACC directives from 6.x-openacc version to manage Host <-> GPU memory movement, to enable surface-layer model to run on the GPU.

### CODE REVIEW

**Comment by cponder** [comment]
I don't see any OpenACC in the `6.x-openacc` version of this file:
```src/core_atmosphere/physics/mpas_atmphys_update_surface.F```
I do see it being built. Is this CPU-only code though?

**Comment by raghuraj19** [comment]
Yes, it is on CPU- if it executes any part of microphysics. @Pranay-Reddy-Kommera & @mgduda can comment on it.

**Comment by cponder** [comment]
Corrected the flow between some consecutive OpenACC-parallel blocks.

When I made the first commit, the OpenACC directives were not being enabled in the compile, so I didn't catch this error.

**Comment by mgduda** [comment]
Following a discussion with @raghuraj19, I've added the "Don't merge" label: we need to wait until @Pranay-Reddy-Kommera's PRs have been merge before merging this PR.

@raghuraj19 If you know of any other PRs besides #897 and #898 that need to be merged only after other PRs, just let me know.

**Comment by cponder** [comment]
I'm closing this one. The new PR #928 covers the Host <-> Device updates to be compatible with changes made to the other Physics models.

**Pull request closed without merging**
