### PR TITLE
Fixed config_soma_surface_temperature from 15 to 20 deg C

### PR DESCRIPTION
**Pull request by lizcarlson**
At 15 deg C, the temperature profile attains an unphysical minimum near -5 deg C.

### CODE REVIEW

**Comment by lizcarlson** [comment]
@pwolfram @vanroekel 

I couldn't assign a reviewer (I think I don't have permissions), so hopefully this gets to you both.

Thanks!
Elizabeth

**Comment by vanroekel** [comment]
@lizcarlson I did assign a reviewer but now note that you are trying to commit to master.  You need to change the target branch to ```ocean/develop```.  Please close this PR and open a new one.  I'll assign review once you do.

**Comment by lizcarlson** [comment]
Sounds good


Elizabeth Carlson


NSF Graduate Research Fellow

University of Nebraska-Lincoln
Department of Mathematics
241 Avery Hall
ecarlson10@unl.edu
________________________________

**Comment by xylar** [comment]
@vanroekel and @lizcarlson, you can just edit the PR and change the target branch. No need to close.

**Pull request closed without merging**
