### PR TITLE
Revert all physics schemes to match those in the v7.0 release

### PR DESCRIPTION
**Pull request by mgduda**
This PR reverts all physics schemes to match the v7.0 release version, and
it removes all OpenACC directives from the physics driver modules.

### CODE REVIEW

**Comment by mgduda** [comment]
I initially tried reverting one scheme at a time, but the shared if-tests in the physics drivers (e.g., for Tiedtke and nTiedtke) made it very difficult to separate out changes that were needed by a single scheme versus those shared by multiple schemes. It's not ideal, but in the end, the most expedient approach was to simply make all changes at once.

**Comment by raghuraj19** [comment]
Thanks @mgduda. I did  a quick review. I'll do an indepth review tomorrow. So, the idea is that we re-introduce the coupler conditions as we port the code? Am I understanding this right?

**Comment by cponder** [comment]
These 7.0 versions, are they the same as what's on the tip of the `develop` branch?
That's what we need to be working with.

**Comment by cponder** [comment]
Also, should I expect the code to work if I download it?

**Comment by mgduda** [comment]
@raghuraj19 I think that's correct. I removed conditions like this one from [mpas_atmphys_driver_radiation_lw.F](https://github.com/MPAS-Dev/MPAS-Model/blob/atmosphere/develop-openacc/src/core_atmosphere/physics/mpas_atmphys_driver_radiation_lw.F#L404-L408):
```
 if (mpas_cpl%role_is(ROLE_INTEGRATE)) then
    !$acc update host(latCell, lonCell, aerosols, skintemp, snow, xice, &
    !$acc xland, sfc_albedo, sfc_emiss, cldfrac, o3clim, &
    !$acc o3vmr, m_hybi, m_ps)
 end if
```
It seemed better to me to take an all-or-nothing approach to OpenACC directives in the physics drivers. And, it should be possible to scan through the physics driver code as of commit ada8b32a (just before the changes in this PR begin) to see where these directives were.

**Comment by mgduda** [comment]
@cponder The physics schemes should all match what is on the current `develop` branch; I've done a `diff -r` of the `src/core_atmosphere/physics/physics_wrf` directories from this branch and the `develop` branch to verify this.

Since the branch in this PR is one commit ahead of the `atmosphere/develop-openacc` branch, you don't need to cherry-pick: you can simply checkout the `atmosphere/acc_revert_v7_physics` branch from my fork and give it a try.

**Comment by cponder** [comment]
I could run the full DyCore+Physics simulation by compiling CPU-only.
I *did* see messages like these
```
  * Requested field scalars_amb is deactivated due to packages, or is a scratch variable.
  * Requested field u_amb is deactivated due to packages, or is a scratch variable.
  * Requested field rho_amb is deactivated due to packages, or is a scratch variable.
  * Requested field theta_amb is deactivated due to packages, or is a scratch variable.
  * Requested field lbc_u is deactivated due to packages, or is a scratch variable.
  * Requested field lbc_w is deactivated due to packages, or is a scratch variable.
  * Requested field lbc_rho is deactivated due to packages, or is a scratch variable.
  * Requested field lbc_theta is deactivated due to packages, or is a scratch variable.
```
and these
```
WARNING: Variable qi not in input file.
WARNING: Variable qs not in input file.
WARNING: Variable qg not in input file.
WARNING: Variable bdyMaskCell not in input file.
WARNING: Variable bdyMaskEdge not in input file.
WARNING: Variable bdyMaskVertex not in input file.
WARNING: Variable v_init not in input file.
WARNING: Variable isice_lu not in input file.
WARNING: Variable iswater_lu not in input file.
```
Is this from using input-files intended for MPAS-A 6.x?

**Comment by cponder** [comment]
Running the moist DyCore with OpenACC enabled, I get these errors in the first timestep
```
5: hostptr=0x7f4f150d8cf0,stride=1,size=4721416,eltsize=4,name=array,flags=0x200=present,async=1,threadid=1
5: FATAL ERROR: data in PRESENT clause was not found on device 6: name=array host:0x7f4f150d8cf0
5:  file:/workdir/Source/src/framework/mpas_dmpar.F mpas_dmpar_exch_halo_2d_real_acc line:7392

```

**Comment by cponder** [comment]
I see that these files still deviate between the `develop` and `acc_revert_v7_physics` branches:
```
src/core_atmosphere/physics/mpas_atmphys_driver.F
src/core_atmosphere/physics/mpas_atmphys_driver_radiation_lw.F
src/core_atmosphere/physics/mpas_atmphys_driver_radiation_sw.F
src/core_atmosphere/physics/mpas_atmphys_init.F
src/core_atmosphere/physics/mpas_atmphys_interface.F
src/core_atmosphere/physics/mpas_atmphys_todynamics.F
```
So are these differences just due to the (necessary) inter-coupler changes?

**Comment by mgduda** [comment]
> ```
> WARNING: Variable bdyMaskCell not in input file.
> WARNING: Variable bdyMaskEdge not in input file.
> WARNING: Variable bdyMaskVertex not in input file.
> WARNING: Variable v_init not in input file.
> ```
> 
> Is this from using input-files intended for MPAS-A 6.x?

Yes, I think these messages are a result of using MPAS-A 6.x input files with MPAS-A 7.x.

**Comment by mgduda** [comment]
> I see that these files still deviate between the `develop` and `acc_revert_v7_physics` branches:
> 
> ```
> src/core_atmosphere/physics/mpas_atmphys_driver.F
> src/core_atmosphere/physics/mpas_atmphys_driver_radiation_lw.F
> src/core_atmosphere/physics/mpas_atmphys_driver_radiation_sw.F
> src/core_atmosphere/physics/mpas_atmphys_init.F
> src/core_atmosphere/physics/mpas_atmphys_interface.F
> src/core_atmosphere/physics/mpas_atmphys_todynamics.F
> ```
> 
> So are these differences just due to the (necessary) inter-coupler changes?

I just checked these files, and all of the differences are accounted for by the addition of the coupler.

**Comment by mgduda** [comment]
I've just force-pushed one small change: I removed some redundant (but otherwise harmless) code from `mpas_atmphys_interface.F`.

**Review by cponder — APPROVED** [review]
We need to get this stuff merged in.
One thing I'd have to say, though -- the current contents of the `develop-openacc` branch don't serve any purpose, since they started by applying changes in the wrong order, so there will be a dis-continuity when these new file versions are merged in.
I think it would make more sense to re-name the original
```
develop-openacc  --> naiive_merge
```
and then re-name this branch to `develop-openacc` instead of merging the commits.

**Comment by mgduda** [comment]
> We need to get this stuff merged in.

Let's wait until we get approvals from @raghuraj19 @supreethms1809 and @Pranay-Reddy-Kommera . I'd rather not revisit the issue of v7 physics again if we merge the changes now only to find out that someone else doesn't approve of this PR.

> One thing I'd have to say, though -- the current contents of the `develop-openacc` branch don't serve any purpose, since they started by applying changes in the wrong order, so there will be a dis-continuity when these new file versions are merged in.

Are you referring to the other PRs to the `atmosphere/develop-openacc` branch? Insofar as the changes in other PRs are all mutually orthogonal, I don't think the order in which we merge those PRs should matter.

**Review by Pranay-Reddy-Kommera — APPROVED** [review]

**Review by raghuraj19 — APPROVED** [review]

**Review by supreethms1809 — APPROVED** [review]
@mgduda I am getting a segfault while running the code but as @raghuraj19 and @cponder explained to me, this provides a stage for the next commits to fix those errors. So I am passing the review.

**Comment by mgduda** [comment]
Thanks, everyone, for the reviews.

@supreethms1809 Are the segfaults occurring when running in CPU-only mode?

**Comment by supreethms1809** [comment]
> Thanks, everyone, for the reviews.
> 
> @supreethms1809 Are the segfaults occurring when running in CPU-only mode?

@mgduda The segfault is while running on GPUs with OpenACC enabled.

**Comment by cponder** [comment]
The OpenACC segfaults happen because we don't have
https://github.com/MPAS-Dev/MPAS-Model/pull/891
The branch is useless until we have this #887 and the #891 merged in.

**Comment by supreethms1809** [comment]
@mgduda no segfaults while running on CPUs

**Pull request merged**
