### PR TITLE
Remove landIceMask from diagnostics computation

### PR DESCRIPTION
**Pull request by xylar**
This was removed in #447 but inadvertently got added back in in #457.

It should be the first step toward addressing https://github.com/E3SM-Project/E3SM/issues/3797

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the QU240wISC test case through the forward run on my laptop.  That proves to me that the code compiles and runs with ice-shelf cavities without issues but it does not prove that it addresses E3SM-Project/E3SM#3797.  

@jonbob or @darincomeau, would it be easy for you to cherry-pick this fix and see if it helps?

**Comment by mattdturner** [comment]
@xylar Thanks for taking care of this.  I just re-reviewed all of the changes in #457, and as far as I can tell this appears to be the only place were prior changes were reverted.

Approved via visual inspection.

**Comment by jonbob** [comment]
@xylar - I'll cherry-pick this right now and see if it fixes our problem

**Comment by mark-petersen** [comment]
Thanks, @xylar that is a big help. I looked through the files before and after #457 was merged, and I agree with your assessment. This code was added back in during a complicated rebase.  

We will shoot for merging this in Monday after some testing in E3SM.

**Comment by jonbob** [comment]
@xylar - that did fix the issue with the ECwISC30to60E1r2 mesh. Thank you so much for jumping in

**Comment by xylar** [comment]
@mark-petersen, any chance of getting this in to E3SM today?

**Comment by mark-petersen** [comment]
We will plan to merge this on Monday.

**Pull request merged**
