### PR TITLE
Remove ocean core from COMPASS

### PR DESCRIPTION
**Pull request by xylar**
This merge removes the ocean core from COMPASS, because it has moved to https://github.com/MPAS-Dev/compass

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, I'm not sure when we will be ready to remove the ocean core from COMPASS on MPAS-Model but hopefully soon.  This is the PR to do that when we are ready.

**Comment by sbrus89** [comment]
@xylar, thanks for the heads up.

**Review by mark-petersen — APPROVED** [review]
Yes, this looks right to me. Will try to merge in the coming week.

**Comment by mark-petersen** [comment]
@matthewhoffman do you want to make a similar PR for land ice? We could merge both at the same time, for a single E3SM PR.

**Comment by xylar** [comment]
@mark-petersen, I don't think `landice` is there yet. @matthewhoffman hasn't had a chance to review https://github.com/MPAS-Dev/compass/pull/3 yet.  While it would be tidy to have both branches remove COMPASS at the same time, I don't think it's necessary.

**Comment by mark-petersen** [comment]
OK, thanks. It is not necessary to do remove them together.

**Comment by xylar** [comment]
>  It is not necessary to do remove them together.

Right, as long as each branch only removes the code it "owns", meaning `develop` deletes the framework, we should be fine after a merge back to `develop`.

**Review by sbrus89 — APPROVED** [review]
This looks good to me as well.

**Review by vanroekel — APPROVED** [review]
Does not affect e3sm simulations -  approving for merging

**Pull request merged**
