### PR TITLE
Update ISOMIP+ test case visualization and instructions

### PR DESCRIPTION
**Pull request by xylar**
This merge updates the ISOMIP+ viz to make it a python 3 package.  It also adds detailed instructions for how to setup and run the test case on LANL IC.

I added ffmpeg as a new package to be included in the COMPASS conda environment.  ISOMIP+ viz uses this to make movies.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I have tested the new viz on a 2-year Ocean0 run on both my laptop and Grizzly.  I have worked through the instructions myself but will wait until @cbegeman had also done so before merging, in case there are errors or sources of confusion.

**Comment by mark-petersen** [comment]
@xylar how do you render markdown files? I tried to use a few chrome extensions and didn't get them to work.

**Comment by xylar** [comment]
Thanks @mark-petersen.  My instructions are a bit of a work in progress because of #274.  I think the viz is ready to merge (though it could get some future updates, of course).

I view Markdown files on GitHub itself:
https://github.com/MPAS-Dev/MPAS-Model/blob/0ec3da06d57818990c876e63081ce4a702441846/testing_and_setup/compass/ocean/isomip_plus/README_Ocean0_IC.md

**Comment by mark-petersen** [comment]
Great! The instructions are very nice. There are a few extra back-quote characters (\`) on that page you just linked to.

**Comment by xylar** [comment]
Thanks, fixed.

**Comment by mark-petersen** [comment]
@xylar I'll merge this later this week, as E3SM repo will likely be open next week. You said it's "ready to merge". Did you mean to take off the "Don't merge" tag?

**Comment by xylar** [comment]
As I said, my instructions are waiting on #274 to be merged.  Right now, they refer to a fix that doesn't work and would not be needed with that merge.  So this is not ready to merge until that update happens, unless I make a separate PR for the instructions.

**Comment by mark-petersen** [comment]
Thanks @xylar . I have this one and a few python LIGHT scripts. My plan is to have one E3SM PR for that bunch, followed by the one E3SM PR with just the BGC version update (in case of problems).

Could you change these instructions as if the BGC version update is already committed? I'll merge one immediately after the other, but that ordering is easier for me.

**Comment by xylar** [comment]
@mark-petersen, I have done so.

**Pull request merged**
