### PR TITLE
Change RRS to 80 layer

### PR DESCRIPTION
**Pull request by mark-petersen**
Change RRS init_step2 from the current 100 layer to 80 layer.  This is to document in COMPASS how the RRS meshes were made for E3SM V1.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@vanroekel this is what we talked about last week.  I changed the RRS subdirectories to be *80Layer or *100Layer so they are both labeled.  For example:
```
ocean/global_ocean/RRS18to6/default_100Layer
ocean/global_ocean/RRS18to6/default_80Layer
```
So far, I only changed the `RRS18to6/default_80Layer` and `RRS30to10/default_80Layer` cases.  I tested them, and they look right from the ncdump, so I think the vertical interpolation is working.  Please look and see if you agree:
```
/lustre/scratch3/turquoise/mpeterse/runs/t55j/ocean/global_ocean/RRS18to6/default_80Layer/init_step2/ocean.nc
/lustre/scratch3/turquoise/mpeterse/runs/t55i/ocean/global_ocean/RRS30to10/default_80Layer/init_step2/ocean.nc
```
If it appears right, I will change all the other 80 layer cases.

**Comment by vanroekel** [comment]
@mark-petersen can you tell me what the mesh_generator and mesh_scripts paths should be set to?  COMPASS has obviously changed greatly since last I used it.

**Comment by mark-petersen** [comment]
Whoops, I'm glad you saw that.  I decided to do this instead:
```
mpas_tools = /turquoise/usr/projects/climate/mpeterse/repos/MPAS-Tools/master
```
which gets the whole thing.  I need to delete mesh_generator and mesh_scripts.  You can use this one.  
```
/usr/projects/climate/mpeterse/repos/MPAS/compass_RRS_80_layer/testing_and_setup/compass/general.config.ocean_turq
```
I plan to simplify `general.config.ocean` when I switch to jigsaw.

**Comment by xylar** [comment]
What's the status of this branch?  Anything I can do to help it along?

**Comment by mark-petersen** [comment]
oops.  Forgot about this one.  Ha, too many irons in the fire.

Thanks for pinging me.  I am reviewing compass IC stuff this week, this one dovetails with that.

**Comment by xylar** [comment]
@mark-petersen, this branch seems to have gone stale once again.

**Comment by mark-petersen** [comment]
Rebased. Testing if this can reproduce meshes for E3SM V1 simulations. We simply point to the 80 layer IC files, rather than the 100, for all RRS grids.  We also set minimum depth to 10 for all.

We now have the following for mid-depth from the original temperature IC file:
<details>

```
on turquoise:
cd /usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/initial_condition_database
ncdump -v depth_t PTemp.80Layer.180619.nc|tail -n 22
 depth_t = 0.993393234677903, 3.07045293244878, 5.33629620557846,
    7.80814879521253, 10.5047808156918, 13.4466729954416, 16.656224407675,
    20.15783430704, 23.978108875761, 28.1461090677468, 32.6935138770804,
    37.6548660267861, 43.0678160851579, 48.9734063340488, 55.4163937613438,
    62.4455278655598, 70.113907546584, 78.4794157004418, 87.6050628898448,
    97.5593632128703, 108.416822869683, 120.258412723283, 133.172061864226,
    147.253166414217, 162.605105952852, 179.339717054227, 197.577835820128,
    217.449770926097, 239.095688373216, 262.665968678697, 288.321385471353,
    316.233196064892, 346.582943294648, 379.561966954284, 415.370617720969,
    454.217003430176, 496.315143460495, 541.882494452261, 591.136861471408,
    644.292508452438, 701.55544311341, 763.118090157561, 829.153343697525,
    899.808250561462, 975.197723489157, 1055.39855002323, 1140.44431782027,
    1230.32177952073, 1324.96897612393, 1424.27543257107, 1528.08458586656,
    1636.19837480986, 1748.38360141279, 1864.37957387265, 1983.90643006038,
    2106.67353559866, 2232.38742599897, 2360.75879534975, 2491.50830649352,
    2624.37109471886, 2759.0999344002, 2895.4672166942, 3033.26588026661,
    3172.30949693284, 3312.43171537569, 3453.48524492804, 3595.3405417399,
    3737.88432379804, 3881.01801547626, 4024.65619868597, 4168.72512429006,
    4313.16131301808, 4457.91026766109, 4602.92530798001, 4748.16652588422,
    4893.59985680987, 5039.19626458251, 5184.93102825439, 5330.78312100484,
    5476.73467368888 ;
}
```
</details>

which matches what is expected. Compare to bottom depth for IC file in repo, 80 layer RRS
<details>

```
cori02:oRRS30to10v3$ pwd
/project/projectdirs/acme/inputdata/ocn/mpas-o/oRRS30to10v3
cori02:oRRS30to10v3$ ncdump -v refBottomDepth oRRS30to10v3.171128.nc|tail -n 22
 refBottomDepth = 1.98678646935581, 4.15411939554175, 6.51847301561518,
    9.09782457480988, 11.9117370565737, 14.9816089343096, 18.3308398810405,
    21.9848287330396, 25.9713890184824, 30.3208291170111, 35.0661986371497,
    40.2435334164226, 45.8920987538932, 52.0547139142045, 58.7780736084832,
    66.1129821226365, 74.1148329705315, 82.8439984303522, 92.3661273493374,
    102.752599076403, 114.081046662963, 126.435778783603, 139.908344944848,
    154.597987883586, 170.612224022118, 188.067210086335, 207.088461553922,
    227.811080298273, 250.38029644816, 274.951640909234, 301.691130033472,
    330.775262096312, 362.390624492984, 396.733309415583, 434.007926026355,
    474.426080833997, 518.204206086992, 565.560782817531, 616.712940125286,
    671.872076779591, 731.238809447229, 794.997370867892, 863.309316527158,
    936.307184595767, 1014.08826238255, 1096.70883766392, 1184.17979797662,
    1276.46376106484, 1373.47419118303, 1475.07667395912, 1581.092497774,
    1691.30425184573, 1805.46295097985, 1923.29619676545, 2044.51666335532,
    2168.83040784201, 2295.94444415594, 2425.57314654357, 2557.44346644347,
    2691.29872299424, 2826.90114580615, 2964.03328758224, 3102.49847295099,
    3242.1205209147, 3382.74290983668, 3524.2275800194, 3666.4535034604,
    3809.31514413569, 3952.72088681684, 4096.5915105551, 4240.85873802501,
    4385.46388801116, 4530.35664731102, 4675.493968649, 4820.83908311944,
    4966.3606305003, 5112.03189866471, 5257.83015784407, 5403.73608416561,
    5549.73326321215 ;
}
```
</details>

That vertical grid is identical for these files:
```
oRRS30to10v3.171128.nc
oRRS30to10v3wLI.171109.nc
oRRS18to6v3.171116.nc
```

**Comment by mark-petersen** [comment]
@vanroekel Can you approve by visual inspection using pasted vertical levels in previous comments?  You also agree that we set this flag, right?
```
<option name="config_global_ocean_minimum_depth">10</option>
```

**Comment by mark-petersen** [comment]
We found that the previous file `PTemp.80Layer.180619.nc` had bad values for TEMP. Instead of using the 80-layer files, point to the 100-layer files and add a new link to `layer_depth.80Layer.180619.nc`, which has the original 80-layer depth specification.

**Pull request merged**
