### PR TITLE
Ocean: Remove scratch allocates and calls to get_config

### PR DESCRIPTION
**Pull request by mattdturner**
This PR replaces almost all calls to `mpas_allocate_scratch_field` in the ocean model with straight Fortran allocates.  This is done as part of the MPAS framework rewrite, per @philipwjones .  

This PR also replaces almost all calls to `mpas_pool_get_config` in subroutines with definitions in `ocn_config` via `use ocn_config`.  This addresses #394 , and allows #406 to be closed without being merged.

There are still a few calls to `mpas_allocate_scratch_field` that cannot be replaced until more of the MPAS framework rewrite has been completed (namely removal of `blocks`).

This PR only changes the files in the shared subdirectory, not the mode_forward subdirectory.

### CODE REVIEW

**Comment by mattdturner** [comment]
Testing was done on Cori with the Intel compiler (`ifort (IFORT) 19.0.3.199 20190206`).  Testing was done for both an optimized model and a debug model (with `-O0` added to compilation flags).  The Nightly test suite (with a few tests removed, such as the block tests which FAILed for the baseline) was run for both a baseline and the code in this PR:

**Baseline - optimized**
```
 ** Running case Global Ocean 240km - Init Test
      PASS
 ** Running case Global Ocean 240km - Performance Test
      PASS
 ** Running case Global Ocean 240km - Restart Test
      PASS
 ** Running case Global Ocean 240km - Analysis Test
      PASS
 ** Running case ZISO 20km - Smoke Test
      PASS
 ** Running case ZISO 20km - Smoke Test with frazil
      PASS
 ** Running case Baroclinic Channel 10km - Thread Test
      PASS
 ** Running case Baroclinic Channel 10km - Decomp Test
      PASS
 ** Running case Baroclinic Channel 10km - Restart Test
      PASS
 ** Running case sub-ice-shelf 2D - restart test
      PASS
TEST RUNTIMES:
11:31 Baroclinic_Channel_10km_-_Decomp_Test
11:10 Baroclinic_Channel_10km_-_Restart_Test
06:27 Baroclinic_Channel_10km_-_Thread_Test
16:35 Global_Ocean_240km_-_Analysis_Test
12:22 Global_Ocean_240km_-_Init_Test
05:23 Global_Ocean_240km_-_Performance_Test
16:18 Global_Ocean_240km_-_Restart_Test
13:33 ZISO_20km_-_Smoke_Test
05:18 ZISO_20km_-_Smoke_Test_with_frazil
24:44 sub-ice-shelf_2D_-_restart_test
Total runtime 123:21
```

**Baseline - debug**
```
 ** Running case Global Ocean 240km - Init Test
      PASS
 ** Running case Global Ocean 240km - Performance Test
      PASS
 ** Running case Global Ocean 240km - Restart Test
      PASS
 ** Running case Global Ocean 240km - Analysis Test
      PASS
 ** Running case ZISO 20km - Smoke Test
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test for more information)
 ** Running case ZISO 20km - Smoke Test with frazil
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test_with_frazil for more information)
 ** Running case Baroclinic Channel 10km - Thread Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Thread_Test for more information)
 ** Running case Baroclinic Channel 10km - Decomp Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Decomp_Test for more information)
 ** Running case Baroclinic Channel 10km - Restart Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Restart_Test for more information)
 ** Running case sub-ice-shelf 2D - restart test
   ** FAIL (See case_outputs/sub-ice-shelf_2D_-_restart_test for more information)
TEST RUNTIMES:
01:35 Baroclinic_Channel_10km_-_Decomp_Test
01:28 Baroclinic_Channel_10km_-_Restart_Test
01:40 Baroclinic_Channel_10km_-_Thread_Test
17:41 Global_Ocean_240km_-_Analysis_Test
13:00 Global_Ocean_240km_-_Init_Test
04:17 Global_Ocean_240km_-_Performance_Test
17:45 Global_Ocean_240km_-_Restart_Test
11:48 ZISO_20km_-_Smoke_Test
02:00 ZISO_20km_-_Smoke_Test_with_frazil
01:50 sub-ice-shelf_2D_-_restart_test
Total runtime 73:04
```

**This PR - optimized**
```
 ** Running case Global Ocean 240km - Init Test
      PASS
 ** Running case Global Ocean 240km - Performance Test
   ** FAIL (See case_outputs/Global_Ocean_240km_-_Performance_Test for more information)
 ** Running case Global Ocean 240km - Restart Test
   ** FAIL (See case_outputs/Global_Ocean_240km_-_Restart_Test for more information)
 ** Running case Global Ocean 240km - Analysis Test
   ** FAIL (See case_outputs/Global_Ocean_240km_-_Analysis_Test for more information)
 ** Running case ZISO 20km - Smoke Test
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test for more information)
 ** Running case ZISO 20km - Smoke Test with frazil
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test_with_frazil for more information)
 ** Running case Baroclinic Channel 10km - Thread Test
      PASS
 ** Running case Baroclinic Channel 10km - Decomp Test
      PASS
 ** Running case Baroclinic Channel 10km - Restart Test
      PASS
 ** Running case sub-ice-shelf 2D - restart test
   ** FAIL (See case_outputs/sub-ice-shelf_2D_-_restart_test for more information)
TEST RUNTIMES:
11:31 Baroclinic_Channel_10km_-_Decomp_Test
11:08 Baroclinic_Channel_10km_-_Restart_Test
06:31 Baroclinic_Channel_10km_-_Thread_Test
17:27 Global_Ocean_240km_-_Analysis_Test
12:08 Global_Ocean_240km_-_Init_Test
04:24 Global_Ocean_240km_-_Performance_Test
16:54 Global_Ocean_240km_-_Restart_Test
00:07 ZISO_20km_-_Smoke_Test
00:07 ZISO_20km_-_Smoke_Test_with_frazil
00:31 sub-ice-shelf_2D_-_restart_test
Total runtime 80:48
```

**This PR - debug**
```
 ** Running case Global Ocean 240km - Init Test
      PASS
 ** Running case Global Ocean 240km - Performance Test
      PASS
 ** Running case Global Ocean 240km - Restart Test
      PASS
 ** Running case Global Ocean 240km - Analysis Test
   ** FAIL (See case_outputs/Global_Ocean_240km_-_Analysis_Test for more information)
 ** Running case ZISO 20km - Smoke Test
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test for more information)
 ** Running case ZISO 20km - Smoke Test with frazil
   ** FAIL (See case_outputs/ZISO_20km_-_Smoke_Test_with_frazil for more information)
 ** Running case Baroclinic Channel 10km - Thread Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Thread_Test for more information)
 ** Running case Baroclinic Channel 10km - Decomp Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Decomp_Test for more information)
 ** Running case Baroclinic Channel 10km - Restart Test
   ** FAIL (See case_outputs/Baroclinic_Channel_10km_-_Restart_Test for more information)
 ** Running case sub-ice-shelf 2D - restart test
   ** FAIL (See case_outputs/sub-ice-shelf_2D_-_restart_test for more information)
TEST RUNTIMES:
01:37 Baroclinic_Channel_10km_-_Decomp_Test
01:36 Baroclinic_Channel_10km_-_Restart_Test
01:45 Baroclinic_Channel_10km_-_Thread_Test
19:58 Global_Ocean_240km_-_Analysis_Test
12:37 Global_Ocean_240km_-_Init_Test
04:26 Global_Ocean_240km_-_Performance_Test
18:23 Global_Ocean_240km_-_Restart_Test
00:20 ZISO_20km_-_Smoke_Test
00:19 ZISO_20km_-_Smoke_Test_with_frazil
00:08 sub-ice-shelf_2D_-_restart_test
Total runtime 61:09
```

**Comment by mattdturner** [comment]
The `debug` failures in both baseline and this PR for `ZISO`, `Baroclinic Channel`, and `sub-ice-shelf` all have the following error report:
```
forrtl: severe (408): fort: (7): Attempt to use pointer REDIKAPPA when it is not associated with a target

Image              PC                Routine            Line        Source
ocean_model        0000000003251CE6  Unknown               Unknown  Unknown
ocean_model        0000000001F47AB6  ocn_tendency_mp_o         869  mpas_ocn_tendency.F
ocean_model        0000000001BBB1BB  ocn_time_integrat        1504  mpas_ocn_time_integration_split.F
ocean_model        0000000001B84B98  ocn_time_integrat         110  mpas_ocn_time_integration.F
ocean_model        0000000001B846FD  ocn_forward_mode_         613  mpas_ocn_forward_mode.F
libiomp5.so        00002AAAADCDC9F3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002AAAADC9D5B2  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002AAAADC5DD60  __kmpc_fork_call      Unknown  Unknown
ocean_model        0000000001B8310B  ocn_forward_mode_         611  mpas_ocn_forward_mode.F
ocean_model        0000000001B7AC73  ocn_core_mp_ocn_c         111  mpas_ocn_core.F
ocean_model        0000000000417C74  mpas_subdriver_mp         347  mpas_subdriver.F
ocean_model        0000000000412CA7  MAIN__                     16  mpas.F
ocean_model        0000000000412C12  Unknown               Unknown  Unknown
libc-2.26.so       00002AAAAE208F8A  __libc_start_main     Unknown  Unknown
ocean_model        0000000000412B2A  Unknown               Unknown  Unknown
```

The optimized failures for Global Ocean in this PR are a result of non-bfb results.  However, the fact that the debug tests are bfb suggests that the non-bfb for the optimized tests are a result of additional optimization that can be done by the compiler as a result of the changes in this PR.

**Comment by mattdturner** [comment]
I just rebased to resolve the merge conflicts

**Comment by philipwjones** [comment]
Thanks, I'll check it out.

Tried to test the threading case on Summit but threading with PGI is still broken there. Will try an Intel or gnu build instead. Wanted to use a different machine to make sure the changes worked everywhere...

Phil

TSPA/Correspondence/DUSA PLNT
------
Philip Jones (pwjones@lanl.gov)
Climate, Ocean and Sea Ice Modeling
Los Alamos National Laboratory
T-3 MS B216
P.O. Box 1663
Los Alamos, NM 87545
________________________________

**Comment by mark-petersen** [comment]
@mattdturner I'm rebasing, testing, and merging this week. Since this PR touches so many parts of the code, I plan to repackage this into three smaller PRs:
- analysis_members
- init_mode
- remainder (may split further if there are problems)

I will leave this PR in tact, as the diffs will show the changes remaining against `ocean/develop` branch as I merge the smaller PRs.

Do you mind if I squash your commits on this PR, and then make separate commits for each of those items? 

The code will remain identical, but it allows me to cherry-pick the new commits. There may just be a few lines to separate in `Registry.xml`, but otherwise it should be a clean separation. It's easier for me to do it, since I'm testing at the same time.

**Comment by mark-petersen** [comment]
@mattdturner thanks for the updates. I ran these through the MPAS-Ocean nightly regression suite on grizzly. For a straight test (no comparisons) I get:
1. gnu debug: PASS on all tests
1. gnu optimized: PASS on all tests
1. intel 17 debug: PASS on all tests
1. intel 17 optimized: PASS on all tests except Global_Ocean_240km_-_BGC_Ecosys_Test (dies during run, probably init mode creates a bad file)
1. intel 19 debug: PASS on all tests
1. intel 19 optimized: PASS on all tests


I then compared to commit 82eb7345 on ocean/develop, before these changes (just before PR #539 and #553). I get:
1. gnu optimized: PASS all comparisons, except Global_Ocean_240km_-_Analysis_Test, mismatch in variable tThreshMLD
1. intel 17 optimized: PASS all comparisons, except Global_Ocean_240km_-_BGC_Ecosys_Test fails to run
1. intel 19 optimized: comparisons FAIL on most of the tests.

Since the comparisons vary by compiler, I'm guessing these are differences in optimizations in that intel 19 test. I'll compare debug next.

**Comment by mark-petersen** [comment]
@mattdturner I've been doing more testing. First, I compared the repo between 82eb734 (before PR #539 and #553) to f0865d76f (current head, just after those two PRs). It passes the nightly regression suite and is bfb between before/after on all three compilers, optimized (gnu, intel17, intel19). So it looks like everything is OK with the current head of ocean/develop.

I then reran with the current head of this PR, 4de1b4d. On intel 19, the failed bfb comparison variables are all 1e-13, so that comparison is OK. I'll keep testing on those other couple of problems above.

**Comment by mark-petersen** [comment]
With that last commit I can pass the `Global_Ocean_240km_-_BGC_Ecosys_Test`. The atmospheric pressure from init mode was not specified. Some compilers set it to zero, and some set it to random stuff. So I forced it to be zero.

**Comment by mattdturner** [comment]
@mark-petersen That's great!  Is there any additional testing / debugging that needs to happen in MPAS-O, or can we move on to the E3SM testing now?

**Comment by mark-petersen** [comment]
Yes. I think we can proceed from MPAS-Ocean testing to E3SM testing. I did a bunch of testing already.

Current head of `ocean/develop`  f0865d76f (after PR #539 and #553) in E3SM:
```
passes
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel

fail
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel (but master also fails this one)
```

E3SM with this PR merged in, and 
```
components/mpas-ocean/cime_config/buildnml
-        lines.append('    <var name="thermalExpansionCoeff"/>')
-        lines.append('    <var name="salineContractionCoeff"/>')
```
those were scratch arrays being written out, for some reason. Then the tests show:
```
pass
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
PEM_Ln3_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
PET_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel

fail
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu fail with runtime out of bounds error
PEM_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu fail with runtime out of bounds error
```
This appears to be a problem with gnu but not intel. A few ideas are that we can run with threading off (`./create_test --force-threads 1`) or turn off cvmix, redi, or gm, as those parts are likely candidates.

Considering this, I'm making an E3SM PR for just the init and analysis member parts, so we have smaller parts of the code to alter in each PR.

**Comment by mark-petersen** [comment]
@mattdturner this would give us some information. Stick with this test, as it is fast.
```
./create_test PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_gnu  -q debug --walltime 00:30:00
```
and make sure it fails, but that intel passes. Then run separate tests with gnu, each with these turned off individually:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
117:<config_use_Redi>.false.</config_use_Redi>
132:<config_use_GM>.false.</config_use_GM>
172:<config_use_cvmix>.false.</config_use_cvmix>
```

**Comment by mattdturner** [comment]
I've started that case on Cori.  Hopefully its a quick turnaround to resolve the issue.

**Comment by mark-petersen** [comment]
@jonbob and @philipwjones, we are struggling a bit with this PR, and could use some advice. 

Right now:
- changes pass all MPAS-Ocean tests
- this PR is bfb against ocean/develop on MPAS-Ocean tests for gnu optimized. Diffs are machine precision for intel optimized.
- In E3SM, it passes all tests using the intel compiler, but fails in the run step with gnu compiler on cori - it dies with out of bounds (mpaso.output_debug_block*nc files)
- we turned off gm, redi, and cvmix, and the same thing happened.

This PR only changes MPAS Registry scratch variables to locally allocated scratch variables, so we don't expect major changes. We thought it could even be bfb.

I'm a bit stuck, if you have any thoughts.

@jonbob how do we check bfb answers against a previous E3SM commit? We should check that for the intel compilers.

**Comment by jonbob** [comment]
@mark-petersen - I can see if I can get any more information with the out-of-bounds problem. You can check for BFB-ness against a previous version a couple of different ways -- if it's a system that's tested on, they stash results for just that purpose. Otherwise you can do it the old-fashioned way -- run the same case with and without your changes and compare results. Do you know about the tool cprnc? It compares netcdf files and it very good for determining if something is BFB or not

**Comment by mark-petersen** [comment]
@mattdturner This corresponding E3SM PR: https://github.com/E3SM-Project/E3SM/pull/3597 is now updated with this PR merged into e3sm/testing, so if you take the head of that it is ready for testing.

@jonbob if it's convenient for you to run a few tests on the head of https://github.com/E3SM-Project/E3SM/pull/3597, that would be great.

**Comment by jonbob** [comment]
@mark-petersen - what am I supposed to test for? Are you still having those failures?

**Comment by jonbob** [comment]
@mark-petersen - you never responded to my question about the status of this PR

**Comment by mark-petersen** [comment]
@jonbob I think @mattdturner made some progress on narrowing down the problem. No need for you to test now, thanks.

**Comment by jonbob** [comment]
Isn't this what you're trying to get merged in PR #3717? That PR points here

**Comment by mattdturner** [comment]
I just pushed a new commit that removes the changes from `mode_forward/` and `Registry.xml`.  I need to re-test this in E3SM (going to start that now).

**Comment by mattdturner** [comment]
Ok, I merged this most recent change into E3SM and it passed the following tests:
```
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
```
So it looks like this PR should be good to go.  I'll handle modifications to `mode_forward/` and `Registry.xml` in a future PR...

**Comment by mattdturner** [comment]
I just tested this on Cori for both MPAS standalone and E3SM.  The following tests passed:

**MPAS-O**:
```
Global Ocean - Performance Test
```

**E3SM**:
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
```

I have the full MPAS-O nightly test suite and additional E3SM tests running right now and will update this comment with the PASS/FAIL status of additional tests once they finish.

**Comment by mark-petersen** [comment]
Tested again to be sure, with current head. All pass the nightly regression suite. On comparison with previous on grizzly:
1. gnu debug: all bfb match
2. intel17 debug: all bfb match except bgc_ecosys_test (order 1 to 1e-2)
3. intel19 debug: all bfb match
1. gnu optimized: all bfb match (to zero)
2. intel17 optimized:  bgc_ecosys_test  (order 1 to 1e-2) mismatch. All others are machine precision mismatch
3. intel19 optimized: bgc_ecosys_test  (order 1 to 1e-2) mismatch. All others are machine precision mismatch

**Comment by mark-petersen** [comment]
@mattdturner reposting our slack conversation for later reference:

I think I figured out what was wrong. These variables were still in the Registry:
```
Registry.xml:3366:              <var name="projectedSSH" persistence="scratch" type="real" dimensions="nCells" units=""
```
and others. If your new allocated arrays were just local, it did’t cause a problem. But once you declared them as public variables, like you did at the top of mpas_ocn_diagnostics.F
```
 113    !  real (kind=RKIND), dimension(:), allocatable ::  projectedSSH
```
then there were two variables using the same allocatable namespace. Worse yet, the first is size nCells+1 and the other is nCells.
I did two tests - one where I switched these three back to the old scratch arrays:
```
+      allocate(div_hu(nVertLevels, nCells), &
+               projectedSSH(nCells), &
+               ALE_Thickness(nVertLevels, nCells))
```
in the other test, I simply deleted them from the Registry.xml file (that’s simpler!). Tests are still running. But that other fail always happens at the beginning, so it looks like it gets through. I still get on failure
```
./create_test SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel -q debug --walltime 00:30:00
```
fails, but I think it just ran out of time. Running again with more procs.

If you want, you could try putting your timestep changes back on, and removing all those `persistence="scratch"` variables from the Registry. I bet that was the problem with those as well. Particularly anything declared as public.

**Comment by mattdturner** [comment]
Thanks @mark-petersen for noticing the `Registry.xml` issue.  I've pushed a new commit which removes unused variables from the Registry file.  I've done the following tests:

```
PASS      PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PASS      PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PASS      SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PASS      SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PASS      PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PASS      PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PASS      SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
PASS      SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
```

Note that `SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu` constantly failed before this commit.

**Pull request merged**
