### PR TITLE
Cleaned up names in rk4 time stepping for clarity

### PR DESCRIPTION
**Pull request by mwatwood-cu**
Changed appropriate locations in subroutines with variables named rkWeight to rkSubstepWeight to clarify the process of the rk4 time stepping

### CODE REVIEW

**Comment by mark-petersen** [comment]
@mwatwood-cu Thanks for the PR. It's good to make the code more clear when we see this type of confusing notation.

**Comment by xylar** [comment]
@mwatwood-cu, we use camel case for nearly all of our variable names.  Could you change `rk_substep_weight` to `rkSubstepWeight`?  I agree that the change makes the code clearer.

**Comment by mwatwood-cu** [comment]
@xylar done!

**Comment by mark-petersen** [comment]
Passes RK4 test, as expected.

**Pull request merged**
