### PR TITLE
Fix path to docs in Travis CI

### PR DESCRIPTION
**Pull request by xylar**
Replace space (not backslash) with underscore in the path.

Documentation for "latest coastal" and "lastest ocean" is being
placed in a directory that is not very convenient to reference.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, I noticed that recent merges put documentation here:
http://mpas-dev.github.io/MPAS-Model/latest%20coastal/
and here:
http://mpas-dev.github.io/MPAS-Model/latest%20ocean/

I made a small mistake and the space should have been replaced with an underscore.  I'm mostly asking for your review to confirm that you think this change will fix the problem, since it's not very easy to test.

**Comment by xylar** [comment]
This fix won't propagate to ocean/develop or ocean/coastal for awhile so we'll just have to live with the bad path for awhile.

**Comment by mark-petersen** [comment]
@mgduda @matthewhoffman @akturner: FYI, for PRs to develop that only involve Travis CI and documentation, I will not ask for your approval, as we are still getting the kinks out.

**Comment by xylar** [comment]
@mark-petersen, the space comes from this file:
https://github.com/xylar/MPAS-Model/blob/fix_docs_ci/travis_ci/get_docs_version.bash
It is intentional.  However, I want to replace the space with an underscore in the URL because a %20 is an ugly thing to have in a URL even if it works.  Mere when you're ready.

**Pull request merged**
