### PR TITLE
Use appropriate units for core_atmosphere file I/O

### PR DESCRIPTION
**Pull request by jjguerrette**
This PR supports interfacing MPAS with the JEDI data assimilation framework.

The atmospheric core is updated to use the MPAS framework subroutines mpas_new_unit and mpas_release_unit for defining appropriate file units for I/O that do not conflict with other units already used throughout MPAS or in a surrounding program when MPAS is used as a library.

This code has been tested within JEDI with code that will be submitted in several other pull requests. This PR depends on the code changes in #106 , and should be considered after that merge is completed. There should be no impact to non-JEDI applications, but I have no method to test that fact at this time.

### CODE REVIEW

**Comment by mgduda** [comment]
@jjguerrette I believe the relevant I/O changes from PR #106 have been merged as PR #309. If that is the case, could you rebase this PR so that it only has the atmosphere-specific commit or commits referenced in the description of this PR?

**Comment by jjguerrette** [comment]
@mgduda Because I had merged develop into this branch a while back, it made rebasing difficult.  It was easiest for me (with little rebase experience) to checkout 7b3e69ed2bcc657a1885c0f4b006bd897cf6cbc0, then rebase to remove irrelevant commits, then merge develop once again.  That new branch is diverged from this one.  Is it OK to close this PR, then reopen with the new branch (same name)?

**Comment by mgduda** [comment]
@jjguerrette No problem at all if it's easier to just create a new PR.

**Comment by jjguerrette** [comment]
Reopened as #743

**Pull request closed without merging**
