### PR TITLE
Fixed config_soma_surface_temperature from 15 to 20 deg C

### PR DESCRIPTION
**Pull request by lizcarlson**
At 15 deg C the initial temperature profile attains an unphysical minimum near -5 deg C

@pwolfram @vanroekel

### CODE REVIEW

**Comment by pwolfram** [comment]
@lizcarlson, can you please provide some plots or additional details?  For instance, was there a typo in the write-up from the SOMA paper or is this a typo in the code?

**Comment by vanroekel** [comment]
@pwolfram this is a code typo.  The change makes this consistent with your paper, but there is also a typo in the paper too that is corrected in the soma code (alpha is off by an order of magnitude).

**Comment by lizcarlson** [comment]
This is a typo in the code.  A plot of the correct temperature profile with the correct shift of 20 is given here:
https://www.wolframalpha.com/input/?i=%281%2F%28.25%29%29*%28%281-0.05%29*5*tanh%28x%2F300%29%2B0.05*5*%28x%2F%282400%2B100%29%29%29%2B20
The original profile with the shift of 15 is given here:
https://www.wolframalpha.com/input/?i=%281%2F%28.25%29%29*%28%281-0.05%29*5*tanh%28x%2F300%29%2B0.05*5*%28x%2F%282400%2B100%29%29%29%2B15

There is also a typo in the SOMA paper on the choice of alpha value in Appendix A; it's negative and off by an order of magnitude.

**Comment by mark-petersen** [comment]
@lizcarlson thanks for making a correction.

@pwolfram, please approve. It looks like a correction to a mistake in the SOMA repo flags relative to your paper.

**Comment by lizcarlson** [comment]
@mark-petersen  @pwolfram  Of course!  I did want to let you know I meant to do this for the config files as well under the testing_and_setup directory but haven't gotten around to it yet.  Hopefully I will get those in by the end of this week for approval.

Best,
Elizabeth

**Comment by pwolfram** [comment]
@lizcarlson, does this mean that there are some changes you need before we can merge this in?  I can wait to review until you submit these if you want.

**Comment by lizcarlson** [comment]
Good point, I will post another comment on here tagging @pwolfram when I update those config flags in the setup directory and have it ready for merging here, that way we only have to do one merge.

**Comment by pwolfram** [comment]
Thanks @lizcarlson, sounds good.

**Comment by lizcarlson** [comment]
@pwolfram this should finally be ready for merging; this branch is an old develop branch (no AOT DA), so hopefully it will be easy to merge

**Comment by mark-petersen** [comment]
Rebased on ocean/develop. @pwolfram this is a simple change from 15 to 20C IC on soma. Please approve if you agree.

**Comment by mark-petersen** [comment]
@lizcarlson it doesn't matter for this one, but you usually make PRs from a new branch name on your fork, not from the master branch on your own fork.

**Pull request merged**
