### PR TITLE
Reorganize ocean mesh initialization

### PR DESCRIPTION
**Pull request by philipwjones**
The changes here push all ocean mesh initialization very early in the initialization sequence (just after file reads) so that all mesh module variables are available to later module initialization routines. In addition, all mesh initialization has been consolidated into the meshCreate routine and the relevant routines moved into the ocn_mesh module. The exceptions are the advection weights and rbf interpolation variables which may be relocated later, so the mesh update routine in initialization is still necessary to capture these. Also moved edgeArea weights from diagnostics into the mesh and removed from registry (now just an internal mesh module variable).

Changes are bit-for-bit.

### CODE REVIEW

**Comment by philipwjones** [comment]
Tested in forward mode using QU240 on Summit. Have not tested the related changes in analysis mode driver.

**Comment by mattdturner** [comment]
This failed to compile with GNU because of the redundant `use ocn_mesh` lines within the diagnostics code.  I pushed a commit to remove those extra lines.  It is now BFB w/ Intel Debug and GNU Debug (I need to test optimized for both).

**Comment by mattdturner** [comment]
E3SM testing:
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_gnu
PET_Ln9.T62_oQU240.GMPAS-IAF.anvil_intel
PET_Ln3.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.anvil_gnu
PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.anvil_gnu
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_intel
PEM_Ln9_D.T62_oQU240.GMPAS-IAF.anvil_gnu

PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel.C
  - PASS PEM_Ln9.ne30_oECv3.A_WCYCL1850S.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/intel
/master:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel.C
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chrysalis_intel BASELINE /lcrc/group/e3sm/baselines/chrys/
intel/master:
```

**Comment by mattdturner** [comment]
@philipwjones does ` src/core_ocean/mode_forward/mpas_ocn_time_integration_rk4.F ` need to be updated with this PR as well?

**Comment by philipwjones** [comment]
@mattdturner No, the RK4 routine doesn't have an init so wasn't impacted by the init changes I made to the others.

**Comment by mattdturner** [comment]
Rebased.  The PR is still BFB for Intel (optimized + debug).  Hoping to get this merged this week.

**Review by mattdturner — APPROVED** [review]

**Review by mark-petersen — APPROVED** [review]
This looks good, based on visual inspection and Matt's testing. I also rebased on origin/master and compiled MPAS-Ocean standalone.

**Comment by mattdturner** [comment]
Merged into E3SM https://github.com/E3SM-Project/E3SM/pull/4307.  Closing this PR

**Pull request closed without merging**
