### PR TITLE
Add critical land blockages to global_ocean tests

### PR DESCRIPTION
**Pull request by xylar**
Adds support for transects that *must* be land to the new global ocean setup in COMPASS

### CODE REVIEW

**Comment by xylar** [comment]
These changes will only work along with:
https://github.com/MPAS-Dev/geometric_features/pull/103
and
https://github.com/MPAS-Dev/MPAS-Tools/pull/247

**Comment by xylar** [comment]
## Testing

So far, I have only tested on a QU240 mesh and that's a bit of a hacky test because I don't have Jigsaw yet so I just copied the mesh for a global_ocean_V1 test case.

Here is the masking I see:

land_mask_qu240

At this resolution, it's pretty hideous but the land mask has been thickened a bit around the Peninsula (unnecessarily in this case) to make sure there's no through-flow.

**Comment by xylar** [comment]
@mark-petersen, could you try  this with the EC60to30 setup, since you're ready to do the full Jigsaw workflow?  Then, we could try CONUS if that works.

**Comment by mark-petersen** [comment]
This is a mega-test, where I test multiple components at once for the EC60to30 mesh:
https://github.com/MPAS-Dev/geometric_features/pull/49
MPAS-Dev/geometric_features#103
MPAS-Dev/MPAS-Tools#247
with this one.  On badger, I used:
```
  46: -o ocean -c global_ocean -r EC60to30 -t init
cd 
![screen shot 2019-03-05 at 5 25 42 pm](https://user-images.githubusercontent.com/4036816/53846848-bd361700-3f6b-11e9-8525-f7b376aa3996.png)
/usr/projects/climate/mpeterse/repos/model/pr_test/testing_and_setup/compass
./setup_testcase.py -f general.config.ocean_ba_xylar_mesh_test --work_dir /lustre/scratch4/turquoise/mpeterse/runs/190305_test_xylar_mesh_culling -n 46
```
I ran all the way through init and part of spin-up.  Everything went through.

On these images, we have left to right EC60to30 from 
1. Mesh used in E3SM V1 campaign, named oEC60to30V3
2. Jigsaw-created mesh from current repo, before all these PRs.
3. Jigsaw-created, with all these PRs.

Colors show bottom depth.
screen shot 2019-03-05 at 5 13 40 pm
screen shot 2019-03-05 at 5 16 06 pm
screen shot 2019-03-05 at 5 17 57 pm
screen shot 2019-03-05 at 5 19 24 pm

These images show that the new features work, or at least don't cause harm.  Note that Nares Strait is open on upper left.  Thank you @xylar for your dedicated effort on this.

**Comment by mark-petersen** [comment]
It's also very nice to look at the mask files, as they show what cells were removed or forced in, and why. Here is the file 
```
critical_passages_mask.nc
	int transectCellMasks(nCells, nTransects) ;
```
screen shot 2019-03-05 at 5 34 40 pm
screen shot 2019-03-05 at 5 37 38 pm
screen shot 2019-03-05 at 5 41 40 pm

While this file shows the cells that are removed because otherwise sea ice can't flow through:
```
land_mask_final.nc
	int regionCellMasks(nCells, nRegions) ;
```
screen shot 2019-03-05 at 5 44 53 pm

**Comment by mark-petersen** [comment]
If anyone wants to explore these files and make more plots, be my guest.

Grab this tar file:
```
/lustre/scratch4/turquoise/mpeterse/runs/190305_test_xylar_mesh_culling/ocean/global_ocean/EC60to30/init/tar_file/EC60to30_test_xylar_mesh_culling_190305.tar
```
or see the directory here:
```
/lustre/scratch4/turquoise/mpeterse/runs/190305_test_xylar_mesh_culling/ocean/global_ocean/EC60to30/init/initial_state
```

**Comment by xylar** [comment]
The screenshots in this PR should not be studied in too much detail, as the land mask is corrupted, see: https://github.com/MPAS-Dev/MPAS-Model/issues/176

**Pull request merged**
