### PR TITLE
Remove link to missing jigsaw Matlab script

### LINKED ISSUE #431: hurricane test cases link to non-existent jigsaw_driver.m
The test cases:
```
ocean/hurricane/USDEQU120at30cr10rr2/
ocean/hurricane/USDEQU60at15cr5rr1/
```
link to a non-existent Matlab driver script that we no longer support:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/USDEQU120at30cr10rr2/build_mesh/config_base_mesh.xml#L5
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/USDEQU60at15cr5rr1/build_mesh/config_base_mesh.xml#L5
These should be removed.

### PR DESCRIPTION
**Pull request by xylar**
Near as I can tell, this script is not used and the test case works without it.

closes #431

### CODE REVIEW

**Comment by xylar** [comment]
@sbrus89, should this go to `ocean/coastal` or is `ocean/develop` the right place?

**Comment by pwolfram** [comment]
Ocean/coastal please Xylar.  Phil

**Comment by xylar** [comment]
@pwolfram, done.

**Comment by xylar** [comment]
@mark-petersen, this is just clean-up and should be merged as soon as convenient.

**Pull request merged**
