### PR TITLE
Fix python 3 in BGC and CVMix makedep.py

### PR DESCRIPTION
**Pull request by xylar**
This is needed for E3SM builds of `maint-1.0` with python 3.

### CODE REVIEW

**Comment by xylar** [comment]
This PR should be merged after these two:
https://github.com/E3SM-Project/CVMix-src/pull/1
https://github.com/E3SM-Project/Ocean-BGC/pull/3

Each of those PRs starts with a new `maint-1.0` branch that is the same commit or tag currently expected in `e3sm/maint-1.0` and cherry-picks commits necessary to fix python 3 support for building CVMix and Ocean-BGC, respectively.

It is meant to help address E3SM-Project/E3SM#3304

**Comment by xylar** [comment]
## Testing

I did a successful test build on my laptop with GNU compilers. I pointed `get_BGC.sh` and `get_cvmix.sh` to my forks instead of E3SM-Project for the test, since the `maint-1.0` branches haven't been updated yet.

**Comment by xylar** [comment]
Done!  Thanks for the reviews, @mark-petersen.  Could you make the PR to update the E3SM submodule for maint-1.0?  I have less experience there.

**Comment by mark-petersen** [comment]
Thanks, @xylar. Please see https://github.com/E3SM-Project/E3SM/pull/3308

**Pull request merged**
