### PR TITLE
Updates build process by automating submodules

### PR DESCRIPTION
**Pull request by pwolfram**
Automatically downloads submodule code bases and has an auto-timeout to prevent a hang.

### CODE REVIEW

**Comment by pwolfram** [comment]
Will close #500

**Comment by philipwjones** [comment]
Unfortunately, this didn't work as expected in the failure mode. Tried on NERSC where I usually get a pwd prompt. First it suppressed the pwd prompt itself, so it's not clear that it's expecting a pwd entry for the key. Then after timing out, it just errors out with no message and doesn't proceed to the useful next step where it would have output the usual submodule error message.   

When it was successful (eg on Summit), it worked fine. So it's just the failure mode that fails.

**Comment by pwolfram** [comment]
@philipwjones, thanks for testing!  Not sure I completely understand how you want it to behave.  The goals I'm hearing need to be accomplished are:

 - [ ]  pwd prompt passes through 
 - [ ] better error message following time-out (including prior submodule error message)
 - [ ] verify failure mode capabilities (above) on NERSC

Is this consistent with what you'd expect or desire it to do?

**Comment by xylar** [comment]
> verify failure mode capabilities (above) on NERSC

@pwolfram, my guess is that @philipwjones just happens to have his GitHub account configured on NERSC in a way that it prompts for a password, not that this is an issue specific to NERSC.  That is, you testing on NERSC might not reveal this issue if your GitHub account isn't configured to prompt for a password there.

Other than that, it looks like your check list is right.  My request in addition to that from https://github.com/MPAS-Dev/MPAS-Model/issues/500#issuecomment-607764771 still holds.  It seems really important to me that the make process triggers the calls to `git submodule` within the first few seconds of the `make` process.  As a user, I typically start a make and go do something else while it builds.  If I were to have to come back later, enter a password, and go off again before the build finished, that would be really annoying (just as annoying as the current process).

**Comment by philipwjones** [comment]
@pwolfram  Yes the checklist is correct. A couple of quick points. The password prompt is not a github password but the password to unlock the ssh key file. Second, the appropriate error message would get triggered if the timeout didn’t error, but control just passed on to the next if block. 

@xylar ’s request is likely not possible unless you created an artificial dependence in the top level makefile. All the framework and other primary dependencies will always take precedence before it can get to this core-level makefile.

**Comment by xylar** [comment]
> @xylar ’s request is likely not possible unless you created an artificial dependence in the top level makefile. All the framework and other primary dependencies will always take precedence before it can get to this core-level makefile.

@philipwjones, okay, thanks for letting me know.  I'll let that request go, since that sounds like too much trouble.

**Comment by pwolfram** [comment]
What is everyones' thoughts on the value of this PR?  If the consensus is it is of limited value I will close.  I'm thinking it may not be worth everyones' trouble.

**Pull request closed without merging**
