### PR TITLE
Add sediment transport analysis member

### PR DESCRIPTION
**Pull request by caozd999**
This PR adds sediment transport analysis member (Phase I) to the model, with the following variables computed:
- sediment settling velocity
- sediment erosion flux
- sediment bedload transport flux
- suspended sediment concentration in water column

### CODE REVIEW

**Comment by pwolfram** [comment]
Thanks @caozd999, will review and work with you on this next week.  @mark-petersen, please let me know how involved you'd like to be for now.  This work is currently built in an analysis member and eventually will need to be transitioned to an answer-changing capability as it affects the ocean density.  Thanks!

**Comment by mark-petersen** [comment]
@caozd999, thanks for your contribution. We will need a design document, which can be a simple write-up of your method, equations, and testing. 

Please also state on this PR how you tested this, and how you can make that test case available to others for future verification. Make sure to test with multiple compilers (typically gnu and intel) in both debug and optimized mode.

**Comment by caozd999** [comment]
@mark-petersen Ok, I will work on that to complete a full pull request.

**Comment by pwolfram** [comment]
@caozd999, is what is being asked clear?  Please ask questions of us to clarify goals on this first PR you are leading. 

For example, I'd pull out the specific parts of your existing design documents to address the additions here.  Showing that this works can be accommodated by having a PR with tests and plots for each of the capabilities.  Doing this in an "analysis" step that makes a png or pdf, like we did with the dam break case, is a good idea for instance.

**Comment by caozd999** [comment]
@pwolfram Yes I understand that this PR should include test cases for the functions it claims. I finished the design document and collected several test cases, now I need put all them within this PR to make them available.

**Comment by mark-petersen** [comment]
@caozd999, please do the following:

1. Test this rebased branch with your standard test case for the sediment transport analysis member.
2. Upload your design doc to this PR.
3. Tell me what flags to change in order to test this PR.

**Comment by mark-petersen** [comment]
To put the test back into the compass soma case:
```
--- a/testing_and_setup/compass/ocean/soma/4km/3layer/config_forward.xml
+++ b/testing_and_setup/compass/ocean/soma/4km/3layer/config_forward.xml
@@ -15,7 +15,8 @@

        <namelist name="namelist.ocean" mode="forward">
                <template file="soma_template.xml" path_base="script_configuration_dir"/>
                <option name="config_dt">'00:06:00'</option>
+              <template file="sediment_transport.xml" path_base="script_core_dir" path="templates/analysis_members"/>
                <option name="config_run_duration">'0000_00:01:30'</option>
                <option name="config_mom_del4">4.0e8</option>
                <option name="config_btr_dt">'0000_00:00:10'</option>
@@ -40,7 +41,8 @@
                <template file="mixed_layer_depths.xml" path_base="script_core_dir" path="templates/analysis_members"/>
                <template file="lagrangian_particle_tracking.xml" path_base="script_core_dir" path="templates/analysis_members"/>
                <template file="soma_template.xml" path_base="script_configuration_dir"/>
                <stream name="output">
+             <template file="sediment_transport.xml" path_base="script_core_dir" path="templates/analysis_members"/>
                         <attribute name="output_interval">0000_00:01:30</attribute>
                 </stream>
        </streams>
```

**Comment by mark-petersen** [comment]
Ran QU240 with both new analysis members on, running every step. Tested with gnu in debug. Runs without error. Time for AMs is small, 
```
    timer_name                                            total       calls        min            max            avg      pct_tot   pct_par     par_eff
2  time integration                                   10.69949         3        3.42868        3.79648        3.55855    65.38      65.38       1.00
3   compute_sedimentFluxIndex                          0.00354         3        0.00094        0.00136        0.00106     0.02       5.16       0.90
3   compute_sedimentTransport                          0.06423         3        0.01959        0.02241        0.02063     0.39      93.43       0.96
```

**Comment by mark-petersen** [comment]
Also tested QU240 with intel and debug, and both analysis members on. No error messages. Passes nightly regression suite, where new analysis members are off.

**Comment by caozd999** [comment]
Design document
[SedimentTransportDesignDocument_2019.pdf](https://github.com/MPAS-Dev/MPAS-Model/files/3918096/SedimentTransportDesignDocument_2019.pdf)

**Pull request merged**
