### PR TITLE
New Mesh: WC14to60kmL60E3SMv2r04

### PR DESCRIPTION
**Pull request by xylar**
Design discussion Water Cycle mesh, 14 km high resolution region:
> MPAS North America and Arctic Focused Water Cycle mesh for E3SM version 2, with a focused 14-km resolution around North America and 60 vertical levels

This iteration of the `WC14` mesh has geometric features changes from MPAS-Dev/geometric_features#147 that improve the representation of England, Scotland, Italy and Hawaii.

### CODE REVIEW

**Comment by xylar** [comment]
I am working on spinning this up on LANL IC at:
```
/lustre/scratch4/turquoise/xylar/spin_up_WC14to60kmL60E3SMv2r04/ocean/global_ocean/WC14
```
@proteanplanet, it should soon be far enough along shortly for you to work your magic on the initial condition.   I will let you all know when spin-up is complete.

**Comment by xylar** [comment]
Spin-up of the WC14 initial condition is done.  But, as I mentioned on https://github.com/MPAS-Dev/geometric_features/pull/147, I think Hawaii probably doesn't look like we want it to and further revision may be needed.

**Comment by vanroekel** [comment]
@xylar and @proteanplanet I would prefer to wait on this PR but certainly leave open for discussion, until we have a chance to sort out the r3 mesh and 64 vs 60 layers.  The changes in this PR seem unlikely to affect WC simulations significantly.

**Comment by xylar** [comment]
> The changes in this PR seem unlikely to affect WC simulations significantly.

I completely agree.  @proteanplanet argued that these features could matter for tides but WC isn't going to be including tides.

**Comment by xylar** [comment]
Everyone who has been asked to review, w'ere holding off on that for now.  @vanroekel or I will flag you when we get a bit further along.

**Comment by xylar** [comment]
I'm going to close this but keep the branch for reference.  We could revive this sometime in the (possibly distant) future.

**Pull request closed without merging**
