### PR TITLE
Added Parallel processing support with prereq for manage_regression_s…

### PR DESCRIPTION
**Pull request by jamilgafur**
…uite

Incorporated two arguments for parallel support -lp (local_parallel) and -N (Nodes) to
allow for parallel stream processing of regression suites. Default of N is 1 (one); first
processes all tests labeled prereq and then processed all other tests.

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

Enter a description of this PR. This should include why this PR was created, and what it does.

Testing and relations to other Pull Requests should be added as subsequent comments.

See the below examples for more information.
https://github.com/MPAS-Dev/MPAS/pull/930
https://github.com/MPAS-Dev/MPAS/pull/931

### CODE REVIEW

**Comment by jamilgafur** [comment]
@vanroekel

**Comment by vanroekel** [comment]
@jamilgafur there are still a bunch of merge conflicts.  Could you look through and see if you have any signature of the conflicts?  e.g. grep for HEAD again in the files listed here?

**Comment by vanroekel** [comment]
@xylar or @mark-petersen -- @jamilgafur and I did a rebase onto ocean/develop, but the commit history is still really wild.  Do you have any git suggestions on what we should do?

**Comment by xylar** [comment]
@jamilgafur and @vanroekel, it doesn't seem like the rebase was done correctly.  There are hundreds of files modified in the one commit you have.

Also, it seems you are rebasing onto @jamilgafur's version of ocean/develop, not MPAS-Dev/MPAS-Model/ocean/develop, but that's a minor thing.

Also also, I think you may be modifying files directly in the `testing_and_setup/compass` directory, in which case they need to be merged into `develop`, not `ocean_develop`.

My suggestion would be to copy the files you actually meant to modify to a temporary location (or tar them up or something like that), then reset to MPAS-Dev/MPAS-Model/ocean/develop, then copy back or untar the files, then redo the commit.

**Comment by vanroekel** [comment]
Thanks for the suggestion @xylar we'll close this PR and try your suggestion (including a PR into develop instead).

**Comment by jamilgafur** [comment]
I will fail miserably or it will work fine. Either way, I am on it!

**Comment by xylar** [comment]
@vanroekel and @jamilgafur, if there are files in the `testing_and_setup/ocean` directory that have changed, they need to go into `ocean/develop`.  I think that's not the case but wanted to make sure.  Is #593 the new PR?  If so, we're good.

**Comment by vanroekel** [comment]
yes #593 is the replacement to this PR.

**Pull request closed without merging**
