### PR TITLE
Minor updates and clean-up to 'gfortran' build target

### PR DESCRIPTION
**Pull request by mgduda**
This PR introduces several minor updates and clean-up changes to the 'gfortran' build target:
1) Remove the `-m64` flag, which is architecture-specific
2) Change `-O3` to `-g` in the definition of `CXXFLAGS_DEBUG`
3) Enable all available run-time checks with `-fcheck=all` for debug builds

### CODE REVIEW

**Comment by mgduda** [comment]
Note: I've targeted the `hotfix-v7.1` branch because I'd like the `-m64` fix to appear in the v7.1 release so that the MPAS-Atmosphere core will build out-of-the-box with the GNU compilers on AArch64 systems.

**Comment by mark-petersen** [comment]
Local merge into ocean/develop. Compiled with gnu 5.3. Passes nightly regression suite using debug.

@philipwjones @mattdturner or @amametjanov Do you have any comments on changing these gnu flags? It's for stand-alone only, as E3SM uses cmake files.

**Comment by philipwjones** [comment]
@mark-petersen - no comment from me, I'm fine with these.

**Review by matthewhoffman — APPROVED** [review]
@mgduda , these changes look good.  Thanks for updating this build target.

**Review by mark-petersen — APPROVED** [review]

**Comment by mattdturner** [comment]
I also have no comments.  These changes look fine to me

**Comment by mgduda** [comment]
@amametjanov If you wanted more time to consider these changes, just let me know. Otherwise, I'll try to merge it in the next couple of days.

**Comment by amametjanov** [comment]
Yes, I also don't see any issues. E3SM uses `-fcheck=bounds` instead of `-fcheck=all` for debug FFLAGS, but I don't recall any difficulties with the more inclusive `-fcheck=all`.

**Pull request merged**
