### PR TITLE
Adds boundary tidal forcing capability

### PR DESCRIPTION
**Pull request by pwolfram**
This allows restoring of the layerThickness to correspond to relaxation toward a tidally-enforced free-surface boundary condition.  Note, this is tested for RK4.  Split explicit was not as stable.

This solves for a layer thickness tendency of the form

M*(tidal_boundary - ssh) / tidal_tau * layerThickness/sum_k(layerThickness)

where

* M is a boundary condition mask for application of the tidal boundary
* tidal_boundary is the value of the tide to be applied on the boundary
* ssh is the sea surface height
* tidal_tau is the time scale corresponding to application of the tendency
* layerThickness is the iCell,k varying layerThickness variable
* sum_k(layerThickness) is the depth-averaged layerThickness (total water thickness)

The tendency is used to apply tidal forcing to the prognostic equations corresponding to a mask designating the location of the applied tidal boundary.

### CODE REVIEW

**Comment by pwolfram** [comment]
# Testing
A 25km long test case is included that makes a comparison in an analysis step against the forced tidal signal vs the actual MPAS-O free surface:

Screen Shot 2019-04-12 at 4 18 29 PM

**Comment by pwolfram** [comment]
Tested locally and on IC at `/lustre/scratch4/turquoise/pwolfram/PR_tests/MPAS-Model_tidal_forcing`.

**Comment by pwolfram** [comment]
@caozd999, here is the test case with tidal forcing you need for your sediment transport work as we discussed.

**Comment by mark-petersen** [comment]
Passes nightly regression, bfb with ocean/develop. Of course, that does not exercise the new code. @pwolfram or @caozd999, please compile with DEBUG=true and run with your standard test case to create the new initial condition for tidal forcing and run the forward model with 
`config_use_tidal_forcing=.true.`
That should catch any typos or simple bugs.

**Comment by pwolfram** [comment]
@mark-petersen, thank you.  I've compiled and run the case with DEBUG=true and it produces the output as expected.

**Pull request merged**
