### PR TITLE
Fix framework field deallocation errors for XL compiler

### PR DESCRIPTION
**Pull request by amametjanov**
This merge addresses several sources of pool and field deallocation errors
that arise when MPAS is built with the XL 16 compilers.

Additional discussion is at https://github.com/MPAS-Dev/MPAS-Model/pull/367#pullrequestreview-348288849.

Fixes MPAS-Dev/MPAS-Model#481

[bit-for-bit]

### CODE REVIEW

**Comment by mark-petersen** [comment]
@mgduda do you have any comments on this one?

**Comment by mgduda** [comment]
Let me take another look in the next couple of days. I had been working independently to address Issue #481 back in April. It looks like what I had done is a bit different from the approach taken in this PR, and I want to convince myself that the approaches are equivalent before approving (or to determine why what I was doing was wrong).

**Comment by mark-petersen** [comment]
@mgduda if we could merge this in the next few days, that would be helpful.

**Comment by mgduda** [comment]
@amametjanov @mark-petersen I have some changes in progress that should fix the issue with the XL compilers while avoiding the memory leak I mentioned in my review. The next few days are somewhat busy, but I could probably finish the changes by 18 June. I'm not sure whether it would be easier to push additional changes to this PR, or to just create a new PR. I'm open to suggestions.

**Comment by mark-petersen** [comment]
@mgduda thanks for looking into this. We are hoping to merge the develop branch to all our cores on Monday. If you have time to update this before then, we will stick with this PR. Otherwise, we can merge this one and then make a correction on a new PR.

**Comment by mgduda** [comment]
@amametjanov Do you have any objection to my pushing of additional commits to your `framework/nullify-field-pointers` branch?

**Comment by amametjanov** [comment]
Not at all, please go ahead.

**Comment by mgduda** [comment]
@amametjanov @mark-petersen I've taken a slightly different approach to fixing the deallocation errors when using the XL compilers. I need to clean up the commit messages and do more testing, but if either of you have a few minutes, would you be able to give the [framework/fix_xl_deallocate_errors](https://github.com/mgduda/MPAS-Model/tree/framework/fix_xl_deallocate_errors) branch from my fork a try on Summit? If that branch works for you, I can try to formulate it as an addition to the changes in this PR. Since we've spent so much time on this issue, I do think having a detailed description of the changes in the commit history will be helpful to anyone looking through the code in future.

**Comment by mgduda** [comment]
@mark-petersen @amametjanov Since you mentioned merging the `develop` branch to all core-specific branches on Monday (6/22, I assume), I just wanted to check whether you had been able to test the [framework/fix_xl_deallocate_errors](https://github.com/mgduda/MPAS-Model/tree/framework/fix_xl_deallocate_errors) branch in my fork, which I think should fix the issues seen on Summit without introducing any memory leaks.

**Comment by amametjanov** [comment]
I ran `SMS_P12x2.ne4_oQU240.A_WCYCL1850` on Summit+IBM compiler and it built and ran without errors with the new 6 commits from the branch (on top of e3sm-master). 

@mgduda please go ahead with the updates. Thanks.

**Comment by mgduda** [comment]
@amametjanov It got a bit messy trying to rebase my changes onto c02d215, and doing so also invalidated some of the line numbers that I referenced in error messages in my commit messages, so the easiest approach seem to be to simply push my branch to `framework/nullify-field-pointers` on your fork. I do appreciate that this wasn't a very polite thing to do, so if you have any objections at all (and please don't hesitate to raise those objections!), I can restore commit c02d215 and try again with a rebase. In case @mark-petersen is eager to merge this PR, though, this seemed like the less risky approach in the end.

**Comment by amametjanov** [comment]
That's okay. I keep running into this error with multiple repo clones: sooner=better.
I think github stores the Jan 28 commit, in case it needs to be looked up.

**Comment by mark-petersen** [comment]
@mgduda thanks for your timely assistance. I tested these last commits with our tests that exercise this part of the code, and I get bit-for-bit match with the previous. 

@mgduda if you could just approve the PR now, I'll go ahead and merge.

**Comment by mark-petersen** [comment]
Never mind - I refreshed my page and it shows approved now. Thanks!

**Pull request merged**
