### PR TITLE
Fix and Update Code Layout section in README

### PR DESCRIPTION
**Pull request by MiCurry**
`testing_and_setup` is at the same directory level as the `src` directory, so move `testing_and_setup` to be at the same level within the code layout section within the README.

### CODE REVIEW

**Comment by davegill** [comment]
@MiCurry 
Miles,
Title: allignment -> alignment

**Comment by mgduda** [comment]
@MiCurry Can you also make the first comment be a description of the changes, which we will use as the merge commit message?

**Comment by MiCurry** [comment]
@mgduda. The first PR comment message has been updated. Should I update the commit message body as well?

> Since `testing_and_setup` is at the same level as `src`, should the layout actually look like below?
> 
> ```
>         MPAS-Model
>         ├── src
>         │   ├── registry -- Code for building Registry.xml parser (Shared)
>         │   ├── driver -- Main driver for MPAS in stand-alone mode (Shared)
>         │   ├── external -- External software for MPAS (Shared)
>         │   ├── framework -- MPAS Framework (Includes DDT Descriptions, and shared routines. Shared)
>         │   ├── operators -- MPAS Opeartors (Includes Operators for MPAS meshes. Shared)
>         │   ├── inc -- Empty directory for include files that Registry generates (Shared)
>         │   └── core_* -- Individual model cores.
>         └── testing_and_setup -- tools for setting up configurations and tests cases (Shared)
> ```

@mgduda I'm not sure if I see what you mean. Is this not the same as the proposed changes?

**Comment by mgduda** [comment]
The proposed changes look like the following:
```
        MPAS-Model
        ├── src
        │   ├── registry -- Code for building Registry.xml parser (Shared)
        │   ├── driver -- Main driver for MPAS in stand-alone mode (Shared)
        │   ├── external -- External software for MPAS (Shared)
        │   ├── framework -- MPAS Framework (Includes DDT Descriptions, and shared routines. Shared)
        │   ├── operators -- MPAS Opeartors (Includes Operators for MPAS meshes. Shared)
        │   ├── inc -- Empty directory for include files that Registry generates (Shared)
        │   └── core_* -- Individual model cores.
        └────── testing_and_setup -- tools for setting up configurations and tests cases (Shared)
```
and I'd argue that they should look like:
```
        MPAS-Model
        ├── src
        │   ├── registry -- Code for building Registry.xml parser (Shared)
        │   ├── driver -- Main driver for MPAS in stand-alone mode (Shared)
        │   ├── external -- External software for MPAS (Shared)
        │   ├── framework -- MPAS Framework (Includes DDT Descriptions, and shared routines. Shared)
        │   ├── operators -- MPAS Opeartors (Includes Operators for MPAS meshes. Shared)
        │   ├── inc -- Empty directory for include files that Registry generates (Shared)
        │   └── core_* -- Individual model cores.
        └── testing_and_setup -- tools for setting up configurations and tests cases (Shared)
```
But maybe my understanding of these sorts of diagrams is mistaken?

**Comment by mgduda** [comment]
@MiCurry If we're updating the Code Layout section of the `README.md` file, we could also:
1. Move the `inc` directory under each core_* directory
2. Move the `registry` directory under `src/tools`, and add `input_gen` under `src/tools`
3. Add the `default_inputs` directory at the top-level

**Comment by MiCurry** [comment]
@mgduda I just pushed a new update with the changes you suggested.

**Comment by mgduda** [comment]
@MiCurry It looks like we still have `src/registry`. I think the `registry` subdirectory should exist only as `src/tools/registry`.

**Comment by MiCurry** [comment]
`/src/registry/ ` has been removed! I think we're all up to date now!

For what it's worth, as a new user/contributor, this code layout really help me gain an understanding of the layout of MPAS. I think more software projects need to do this!

**Pull request merged**
