### PR TITLE
Remove COMPASS from CI and Docs

### PR DESCRIPTION
**Pull request by xylar**
This merge removes COMPASS tests from Azure CI and from the MPAS-Model documentation produced by Azure (http://mpas-dev.github.io/MPAS-Model/latest/)

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @matthewhoffman, since this is a PR to `develop` related to moving COMPASS to https://github.com/MPAS-Dev/compass, I figured I would get your approval before I remove the docs and testing that has been moved over, just in case.

**Review by mark-petersen — APPROVED** [review]
I agree we need to move compass documentation to the compass repo. Thanks.

**Comment by mark-petersen** [comment]
Will try to merge this in soon on an off day.

**Review by matthewhoffman — APPROVED** [review]
Sounds good to me.  I never fully understood how CI is set up, so I'm approving based on the fact that it is only removing files I am not familiar with. :)

**Comment by xylar** [comment]
> I never fully understood how CI is set up

@matthewhoffman, I'm assuming you're happy to keep it that way, but I'm happy to explain it to you anytime you like.

**Comment by xylar** [comment]
@mark-petersen, I'm not sure why you added @vanroekel as a reviewer.  I have removed him.  I don't think this is really in his wheelhouse and I don't think he was aware he was added.  (@vanroekel, you are welcome to comment but I think `develop` isn't really a branch you keep too much track of.)

**Comment by xylar** [comment]
I'm going to go ahead and merge this.  I think it's just collecting dust.

**Comment by xylar** [comment]
@mark-petersen, I would like to have `develop` merged into `ocean/develop` to bring in these changes when there is a convenient chance to do that.  I could do it as a PR if that makes it easier for E3SM.

There is a merge conflict because 2 files removed here have been modified in `ocean/develop`: https://github.com/MPAS-Dev/MPAS-Model/pull/653.  These files should just be removed as part of the merge.

**Pull request merged**
