### PR TITLE
Update COMPASS ocean API for python 3 and using conda packages

### LINKED ISSUE #132: Update all python scripts to support python 3
Python 2 is going away and we need to start supporting python 3 before we run into trouble.

### LINKED ISSUE #166: Dependencies of a proposed compass conda environment
Packages:
- [ ] mpas_mesh_tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/248):
  - [x] mesh conversion tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/243)
  - [ ] `mark_horns_for_culling.py` (?) (https://github.com/MPAS-Dev/MPAS-Tools/pull/249)
  - [x] planar hex (https://github.com/MPAS-Dev/MPAS-Tools/pull/246)
  - [ ] 4 scripts from landice mesh tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/249): 
    - [ ] `create_landice_grid_from_generic_MPAS_grid.py`
    - [ ] `define_cullMask.py`
    - [ ] `interpolate_to_mpasli_grid.py`
    - [ ] `mark_domain_boundaries_dirichlet.py`
  - [ ] planar mesh transformation tools
    - [ ] `translate_planar_grid.py`
    - [ ] ...
  - [ ] ...
- [ ] geometric_features (https://github.com/MPAS-Dev/geometric_features/pull/102)
- [x] metis
- [x] jigsaw (https://github.com/xylar/staged-recipes/tree/jigsaw/recipes/jigsaw)
- [ ] jigsaw-geo-matlab?
- [ ] ...

### LINKED ISSUE #213: COMPASS python3 transition
Python 2 support is fading across the community and our COMPASS scripts are not python 3 compliant.

Is it worth updating COMPASS to be entirely python 3 supporting?

### LINKED ISSUE #220: Missing script referenced in COMPASS Ocean
A script, `mesh_comparison.py` is referenced in COMPASS's new `globa_ocean` test cases:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/config_files/config_mesh_metrics.xml#L7

This file is pointing to `MPAS-Tools/mesh_tools/mesh_comparison.py`, but there doesn't seem to be any such file:
https://github.com/MPAS-Dev/MPAS-Tools/tree/master/mesh_tools

A little sleuthing suggests it's here:
https://github.com/sbrus89/MPAS-Tools/blob/jigsaw_mesh_creation/mesh_tools/mesh_comparison.py
but hasn't been merged and I didn't see a PR.

@sbrus89, is the solution to add this tool?  Or to remove reference to it from COMPASS for now?

### PR DESCRIPTION
**Pull request by xylar**
A large number of updates to the COMPASS ocean API including:
* using the geometric_features conda package (https://github.com/MPAS-Dev/geometric_features/pull/102)
* using the mpas_tools conda package (https://github.com/MPAS-Dev/MPAS-Tools/pull/248)
* updating the jigsaw_to_MPAS scripts to work as a python package and to support python 3
* update `global_ocean` scripts to python 3 and to use these new packages

NOTE: This merge removes the capability to create the global meshes used in E3SM version 1, (2017-2018), where the base meshes were created with Doug Jacobsen’s tool.  The global mesh creation remaining after this commit only uses the Jigsaw tool.

In order to recreate meshes and initial conditions used in E3SM version 1, use repositories as of
March 1, 2019:
1. MPAS-Model commit:42029f218175d893cf25e19a26d9b43382a44d54
2. MPAS-Tools commit:6d0fa3a24e879a1a5b6149d9fbfe80fa021489dc
3. geometric_features tag:E3SMv3grids 76709be

closes #220
closes #213 
closes #132 
closes #166

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I set up an environment on my linux laptop as follows:
```
conda create -n compass_py3.7 -c conda-forge -c xylar python=3.7 geometric_features mpas_tools \
    jigsaw metis pyflann scikit-image basemap
conda activate compass_py3.7
```
Note: I have uploaded test versions of `geometric_features` and `mpas_tools` to the `xylar` anaconda channel.  These will be deleted as soon as the packages are approved and available on `conda-forge` instead.

COMPASS ocean test cases that have been tested and found to run successfully in this environment:
- [ ]  40: -o ocean -c baroclinic_channel -r 10km -t decomp_test
- [ ]  41: -o ocean -c baroclinic_channel -r 10km -t default
- [ ]  42: -o ocean -c baroclinic_channel -r 10km -t restart_test
- [ ]  43: -o ocean -c baroclinic_channel -r 10km -t threads_test
- [ ]  44: -o ocean -c global_ocean -r EC60to30 -t init
- [ ]  45: -o ocean -c global_ocean -r EC60to30 -t spin_up
- [ ]  46: -o ocean -c global_ocean -r NAEC60to30cr8 -t init
- [ ]  47: -o ocean -c global_ocean -r NAEC60to30cr8 -t spin_up
- [ ]  48: -o ocean -c global_ocean -r QU240 -t init
- [ ]  49: -o ocean -c global_ocean -r QU240 -t test
- [ ]  50: -o ocean -c global_ocean -r QU60 -t init
- [ ]  51: -o ocean -c global_ocean -r QU60 -t spin_up
- [ ]  52: -o ocean -c global_ocean -r SOQU60to15 -t init
- [ ]  53: -o ocean -c global_ocean -r SOQU60to15 -t spin_up
- [ ]  54: -o ocean -c global_ocean -r USDEQU120cr10rr1 -t init
- [ ]  55: -o ocean -c global_ocean -r USDEQU300cr20rr3 -t init
- [ ]  56: -o ocean -c internal_waves -r 5km -t default
- [ ]  57: -o ocean -c internal_waves -r 5km -t ten-day
- [ ]  58: -o ocean -c isomip -r 10km -t expt1.01
- [ ]  59: -o ocean -c isomip -r 10km -t expt2.01
- [ ]  60: -o ocean -c isomip_plus -r 2km -t Ocean0
- [ ]  61: -o ocean -c isomip_plus -r 2km -t Ocean1
- [ ]  62: -o ocean -c isomip_plus -r 2km -t Ocean2
- [ ]  63: -o ocean -c isomip_plus -r 5km -t Ocean0
- [ ]  64: -o ocean -c isomip_plus -r 5km -t Ocean1
- [ ]  65: -o ocean -c isomip_plus -r 5km -t Ocean2
- [ ]  66: -o ocean -c lock_exchange -r 0.5km -t default
- [ ]  67: -o ocean -c lock_exchange -r 16km -t default
- [ ]  68: -o ocean -c overflow -r 10km -t default
- [ ]  69: -o ocean -c periodic_planar -r 20km -t default_light
- [ ]  70: -o ocean -c periodic_planar -r 20km -t region_reset_light_test
- [ ]  71: -o ocean -c periodic_planar -r 20km -t time_reset_light_test
- [ ]  72: -o ocean -c sea_mount -r 6.7km -t default
- [ ]  73: -o ocean -c single_column_model -r planar -t cvmix_test
- [ ]  74: -o ocean -c single_column_model -r sphere -t cvmix_test
- [ ]  75: -o ocean -c soma -r 16km -t 3layer
- [ ]  76: -o ocean -c soma -r 16km -t default
- [ ]  77: -o ocean -c soma -r 16km -t surface_restoring
- [ ]  78: -o ocean -c soma -r 32km -t 3layer
- [ ]  79: -o ocean -c soma -r 32km -t default
- [ ]  80: -o ocean -c soma -r 32km -t surface_restoring
- [ ]  81: -o ocean -c soma -r 32km -t time_varying_wind
- [ ]  82: -o ocean -c soma -r 4km -t 32to4km
- [ ]  83: -o ocean -c soma -r 4km -t 3layer
- [ ]  84: -o ocean -c soma -r 4km -t default
- [ ]  85: -o ocean -c soma -r 4km -t surface_restoring
- [ ]  86: -o ocean -c soma -r 8km -t 32to8km
- [ ]  87: -o ocean -c soma -r 8km -t 3layer
- [ ]  88: -o ocean -c soma -r 8km -t default
- [ ]  89: -o ocean -c soma -r 8km -t surface_restoring
- [ ]  90: -o ocean -c sub_ice_shelf_2D -r 5km -t Haney_number_init
- [ ]  91: -o ocean -c sub_ice_shelf_2D -r 5km -t Haney_number_iterative_init
- [ ]  92: -o ocean -c sub_ice_shelf_2D -r 5km -t default
- [ ]  93: -o ocean -c sub_ice_shelf_2D -r 5km -t iterative_init
- [ ]  94: -o ocean -c sub_ice_shelf_2D -r 5km -t restart_test
- [ ]  95: -o ocean -c sub_ice_shelf_2D -r 5km -t with_frazil
- [ ]  96: -o ocean -c ziso -r 10km -t default
- [ ]  97: -o ocean -c ziso -r 2.5km -t default
- [ ]  98: -o ocean -c ziso -r 20km -t default
- [ ]  99: -o ocean -c ziso -r 20km -t with_frazil
- [ ]  100: -o ocean -c ziso -r 5km -t default

**Comment by xylar** [comment]
Building MPAS with python 3 will require updating to the latest releases of CVMix and Ocean-BGC after this PR is merged:
https://github.com/E3SM-Project/Ocean-BGC/pull/1 
and releases of CVMix and Ocean-BGC have been made with this fix included.

**Comment by xylar** [comment]
## Failed tests

The following is a list of tests that failed (but for reasons I believe are unrelated to this PR):
* `-o ocean -c global_ocean -r EC60to30 -t spin_up` during `simulation` because of CFL violation: 
```
CFLNumberGlobal = 0.0917271835580922, 0.122637831833784, 0.150533786272102, 
    0.17555059144412, 0.197662099329266, 0.217073518294376, 
    0.234323872726046, 0.250136386921142, 0.264790486294835, 
    0.27825253635325, 0.290323188086416, 0.301051958089178, 
    0.310209832190098, 0.3176288821503, 0.32330034866235, 0.328730874921286, 
    0.340932315339754, 0.39929006348568, 0.818147632488227, 1.93089241771095, 
    3.78167130632891, 9.49790843196592, 0.358590340863955
```

**Comment by xylar** [comment]
@caozd999, could you change permissions on the 2 files above that you own (in `/usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/mesh_database` on LANL IC) so I can read them?  Probably, they should belong to the `climate` group.  Check also for other files there than you own.

**Comment by caozd999** [comment]
@xylar, how is it now?

**Comment by xylar** [comment]
@caozd999, the 2.5 km ZISO test case now runs but crashes with a memory issue.  I think it's just running on too few nodes/processors.  Would you be able to update the default settings for that test case so it runs without running out of memory?  Or is that something for @pwolfram?

**Comment by caozd999** [comment]
I think it is something to do with @pwolfram.

**Comment by xylar** [comment]
@pwolfram, I tried increasing the `ziso` 2.5 km run to 144 cores (4 nodes) on Grizzly and I'm still running out of memory.  Is it seeding particles in proportion to the number of cores so that adding more cores doesn't solve the memory problem?

In any case, I'm going to make a separate issue for this since it's not related to this PR.

**Comment by xylar** [comment]
I have now either successfully tested all test cases (55/61) or with this branch or created issues (#233, #234 and #235) to get issues that I think are unrelated to this PR addressed (6/61).  I believe this branch is now ready for @mark-petersen to test and merge when ready.

**Comment by mark-petersen** [comment]
FYI, mega-merge above is bfb with ocean/develop on gnu and intel. Also tested with debug, and passes in E3SM:
```
PASS SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu RUN time=147
PASS SMS_D_Ln9.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel RUN time=397
PASS ERS_Ld9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu COMPARE_base_rest
PASS PEM_Ln9.ne30_oECv3wLI.A_WCYCL1850-DIB-ISMF_CMIP6.cori-knl_gnu COMPARE_base_modpes
PASS PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu COMPARE_base_single_thread
```
@xylar you can feel comfortable rebasing this PR on 
`test_ocean_develop_merges_190508`.  I'll merge all those others later today.

**Comment by xylar** [comment]
Waiting on #222

**Comment by mark-petersen** [comment]
Merged #222. Ready to roll.

**Comment by xylar** [comment]
I tested as many of the test cases as I could, particularly the 6 that were added by the 4 most recent merges to `ocean/develop`.  I solved any issues related to this PR that I found and added an issue for anything remaining.

**Comment by mark-petersen** [comment]
@xylar My day is booked. I won't have time to recreate the nightly test suite for this today. My preference is to merge this in, make the E3SM PR for mpas-source update today rather than delay that, and add the nightly test suite and EC60to30 spinup tomorrow, when I have time.

I just merged develop into ocean/develop. Please confirm when this PR is rebased and in a final state for merging. I'll run one last test and merge.

**Comment by xylar** [comment]
Okay, I'll live with that solution.  I think a new test suite needs to be a pretty high priority once you're back.

**Comment by xylar** [comment]
Okay, it's rebased.  Please do some last tests and merge when ready.

**Comment by mark-petersen** [comment]
@xylar thanks for your tremendous effort. This is a big accomplishment. 

I tested the merged commit, all is OK. Will now make E3SM PR and then update nightly test suite.

**Comment by xylar** [comment]
Thanks very much for shepherding this through, @mark-petersen!

**Pull request merged**
