### PR TITLE
Add radiation stress forcing and sloped beach test case

### PR DESCRIPTION
**Pull request by sbrus89**
- Radiation stress gradients are calculated on edges from cell-centered
   values (test still needed for spherical mesh).

- Sloped beach test case configuration from Chou et al., Computers & Geosciences, 58 (2015) and Sheng and Liu, JGR-Oceans ,116 (2011).

 - Test case imposes an analytical radiation stress forcing  (time-ramped) based on wave theory and integrates to steady-state.

### CODE REVIEW

**Comment by sbrus89** [comment]
Here are some of the details of the test case:

Domain and depth:
h

Wave height:
hb

Sxx radiation stress:
Sxx

x-derivative of Sxx (forcing term)
dSxxdx

**Comment by sbrus89** [comment]
This is the comparison of the exact and MPAS-O solutions after 2.58 days:
(Note that the MPAS-O solution hasn't quite reached steady-state due to a RK4 memory leak error #350)

ssh_comparison

**Comment by sbrus89** [comment]
Here is a link to the design document detailing the test case:

https://www.overleaf.com/16978538hkfrwtcmkgvy

**Comment by mark-petersen** [comment]
@sbrus89 please compile in debug mode, and run both your init mode and forward mode exercising all this code. Test with both gnu and intel. Look at any run-time warnings. That can catch uninitialized and unused variables.

**Comment by pwolfram** [comment]
@sbrus89, how is this different than #541 ?  Are you breaking this into sub parts of the work for simplicity?

**Comment by mark-petersen** [comment]
@sbrus89 I'm looking back at the old PRs, trying to merge these in. This looks like a good test case, with successful results. The current steps are:
1. Remove compass files, make separate PR into new [compass repo](https://github.com/MPAS-Dev/compass) 
2. Rebase on ocean/develop, make this PR into ocean/develop

Do you have time to rebase and test in the next few weeks?

**Comment by mark-petersen** [comment]
I see you added `don't merge` in Sept 2019. The other option is to close the PR. 

We are trying to merge or close all the open PRs in the next two weeks.  Please help us assess: is the radiation stress forcing useful for coastal modeling in general, or was it created just for this test case? Are there remaining issues with this code or test case?

**Comment by sbrus89** [comment]
@mark-petersen, I think it's best to close this since we're going to go with Stokes drift coupling rather than using radiation stress.

**Pull request closed without merging**
