### PR TITLE
Added build support for Summit at OLCF and OpenACC for GPU acceleration

### PR DESCRIPTION
**Pull request by philipwjones**
This change adds a pgi-summit entry to the top level Makefile and adds an OPENACC option
similar to the OpenMP option to enable GPU acceleration for OpenACC decorated code.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@mgduda @mattdturner @akturner 
This simply adds a DOE machine to the makefile configuration and an OpenACC flag, similar to the OpenMP flag.

Could you please comment or approve this week?

**Comment by mark-petersen** [comment]
@philipwjones are there accompanying changes to the cmake build system required here? Are you altering this for stand-alone only right now, or do you want to run within E3SM for pgi-summit and OpenACC?

**Comment by philipwjones** [comment]
Yes. The target and compiler flags are set elsewhere for the Cmake build, so I think the only change in our repo is to set the MPAS_OPENACC ifdef (like for OpenMP) but I didn't know that the equivalent of build_threaded is in the E3SM build. So maybe go ahead with a standalone mod only unless @jonbob or @jgfouca can let us know what the correct OpenACC mods are in e3sm (if there are any?)

**Comment by mark-petersen** [comment]
Changed base to develop, since this is top level makefile. @philipwjones you will see this in e3sm when we merge develop into e3sm/develop, in the next week or two.

**Pull request merged**
