### PR TITLE
Add COMPASS step for remapping prescribed ISMF

### PR DESCRIPTION
**Pull request by xylar**
The data is from the Rignot et al. (2013) data set (not publicly available).

### CODE REVIEW

**Comment by xylar** [comment]
This work is based off of #468 and should ideally be rebased after that is merged.

**Comment by mark-petersen** [comment]
Please rebase later today or tomorrow.

**Comment by xylar** [comment]
I think we decided we weren't bothering with this one just yet, right?

**Comment by mark-petersen** [comment]
Sure. We can put it lower on the list.

**Comment by xylar** [comment]
I went ahead and rebased onto #433 and there were no conflicts.

**Comment by mark-petersen** [comment]
@xylar could you rebase this again? There were some conflicts on some python import lines that I was unsure of.

**Comment by xylar** [comment]
I rebased and there was no conflict.

**Comment by mark-petersen** [comment]
@xylar, can you describe the case, computer, and python package you tested with, and what the directory `init/e3sm_coupling/prescribed_ismf` contained when you were done?
I tried on grizzly on a compute node using `QU240wISC` and package `compass_0.1.2`. I first run the init step. Then I get this:
```
cd e3sm_coupling/
./run.py
****** prescribed_ismf ******
running: mpirun -np 36 /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.2/bin/ESMF_RegridWeightGen --source /tmp/tmpar9c01qz/src_mesh.nc --destination /tmp/tmpar9c01qz/dst_mesh.nc --weight ./map_5600.0x5600.0km_1.0km_Antarctic_stereo_to_oQU240wISC.nc --method conserve --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped
Operating system error: Cannot allocate memory
Allocation would exceed memory limit
```
But this is a brand new functionality. So if it worked for you, I'm happy to merge it and work out the kinks for this grizzly set-up later.

**Comment by pwolfram** [comment]
@mark-petersen, sometimes a user takes up all the memory on the compute node.  I've had this issue before, sure is frustrating.

**Comment by mark-petersen** [comment]
@pwolfram Are you thinking of a login node? I should be the only one on that compute node. There must be some problem with the size of the files it is loading.

**Comment by pwolfram** [comment]
Sorry @mark-petersen , I was thinking head node -- I agree that the file might be too big.

**Comment by xylar** [comment]
@mark-petersen, I believe you are running with the serial version of `compass`.  If that's the case, you will do horrible things if you try to run `ESMF_RegridWeightGen` with `mpirun`.  It might work but it will just be running 36 independent processes trying to write the same file.  You need to set `nprocs` to 1 until we can get the parallel environment working again (https://github.com/MPAS-Dev/MPAS-Model/pull/480).  This problem should be with any mapping files you're creating, not just this case, by the way.

**Pull request merged**
