### PR TITLE
Ocean/coastal update (force push from ocean/develop)

### PR DESCRIPTION
**Pull request by pwolfram**
This is just a reset of ocean/coastal using ocean/develop following #384 as recommended by @mark-petersen.  This is not strictly needed but is to document the force-push of `ocean/develop` onto `ocean/coastal`.

### CODE REVIEW

**Comment by xylar** [comment]
How do you do a pull request of a force push? I thought a PR was always a merge.

**Comment by pwolfram** [comment]
@xylar, it was just a direct push, not a force-push.  I'll edit the above description accordingly because the force-push wasn't needed.

**Comment by pwolfram** [comment]
Thanks!

**Comment by xylar** [comment]
I think @mark-petersen has in mind to do a hard reset so ocean/coastal points to the exact same hash as ocean/develop.  I would think that would require a force push but I could be wrong.

**Comment by pwolfram** [comment]
I think we have that, unless I've missed something.  Are you seeing something different @xylar?

```bash
└─▪ git fetch --all
...
Fetching pwolfram
...
   6fe9af3..7053845  ocean/coastal -> MPAS-Dev/ocean/coastal
   559c823..7053845  ocean/develop -> MPAS-Dev/ocean/develop
...

**Comment by mark-petersen** [comment]
Yes, this all looks right. `ocean/coastal` is now identical to `ocean/develop`. This is a little cleaner than doing a back-merge.

**Comment by pwolfram** [comment]
We also have a record of what we did, which is key.  It is possible this has broken something, but at least we have a landing page and record of when it went wrong (and potentially how in terms of a commit range).

**Comment by xylar** [comment]
Okay, like I said, I just didn't know that was possible.

**Pull request merged**
