### PR TITLE
Change block tests to partition tests for QU240 RK4 and SE

### PR DESCRIPTION
**Pull request by xylar**
As of #496, MPAS-Ocean no longer supports multiple blocks.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@xylar, the previous block tests also served as a test for different domain partitions. So I simply changed these two tests to function again with partitions (4 vs 8).

**Review by mark-petersen — APPROVED** [review]
Tested nightly regression suite with gnu on grizzly. Partition test with SE and RK4 work fine.

**Comment by mark-petersen** [comment]
@xylar If you agree with this, I'll merge.

**Review by xylar — COMMENTED** [review]
I can't approve my own PR but I ran with the changes you made, @mark-petersen, and it works fine.

Probably a cleaner procedure in the future would be to just open a new PR, since this branch contains only changes that you made, is now incorrectly named, and I am not able to review it.

**Comment by xylar** [comment]
I ran the two modified tests on my laptop with Gnu and they work as expected.

**Comment by mark-petersen** [comment]
Yeah, looking back at this now, it would have been cleaner with two PRs. I'll keep that in mind on future ones.

**Pull request merged**
