### PR TITLE
Implementation of manage_externals

### PR DESCRIPTION
**Pull request by ldfowler58**
This PR introduces the use of the manage_externals tool to access the github repository NCAR/MMM-physics.git, and
download the directory physics_mmm. NCAR/MMM-physics.git contains physics parameterizations shared by MPAS, WRF, and CM1. Modules follow CCPP coding standards.

Testing of all changes made in this PR was done using the develop branch (commit 61f0bd0dab2adbc25bdbf9cc) on the NSF NCAR supercomputer derecho using intel/2023.2.1 and gcc/13.2.0:

* Added CCPP compliance for all the modules contained in MMM-physics produce bit for bit reproducilbity of the physics_mmm develop branch with O3 optimization, except for mp_wsm6.F90 with both the intel and gcc compilers.

* Bit for bit reproducibility of the physics_mmm develop branch is achieved with no optimization (-g) and O1 optimization.

### CODE REVIEW

**Comment by mgduda** [comment]
It looks like this PR branch has quite a few additional commits at the beginning. Are these needed, or is it just the last few commits that we want?

I would suggest we omit the `test` directory from `manage_externals`, and we should definitely include the `LICENSE.txt` file (and maybe also the `version.txt` file).

If I can help in reworking the branch, just let me know!

**Review by mgduda — APPROVED** [review]

**Comment by ldfowler58** [comment]
I removed the ./test directory and added the files LICENSE.txt and version.txt files. The commit is at the top of all commits. Can you please move that commit close to 7cf34a2e8bc8, as you suggested in your previous email. I reworked everything using the branch that was originally committed (50134e0173). Thanks.

**Comment by mgduda** [comment]
@ldfowler58 No problem -- I've just rebased the branch to squash what was the last commit into 7cf34a2e.

**Review by mgduda — APPROVED** [review]

**Comment by mgduda** [comment]
Just one final change: I'm going to remove these files/directories from `manage_externals` as well:
* .dir_locals.el
* .github/ISSUE_TEMPLATE.md
* .github/PULL_REQUEST_TEMPLATE.md
* .github/workflows/bumpversion.yml
*  .github/workflows/tests.yml
* .travis.yml

**Comment by ldfowler58** [comment]
Many thanks for your help.

**Comment by mgduda** [comment]
@favba I think you're right -- the https://github.com/NCAR/MMM-physics repository is still private, but the intent is definitely to make this public. I should have checked the permissions on that repository before I approved and merged this PR. We'll get this sorted out soon!

**Comment by ldfowler58** [comment]
Thank you for pointing out that the https://github.com/NCAR/MMM-physics repository is still private. We did change the permission to make the repository public and you should be be able to download it when you compile MPAS-Model. Let us know if you still have issues, of course!

**Comment by favba** [comment]
Thank you guys! I can confirm the repo is available and I'm able to compile the develop branch again!

**Pull request merged**
