### PR TITLE
Add cloud fraction and cloud height diagnostics

### PR DESCRIPTION
**Pull request by jamiebresch**
TYPE: enhancement

KEYWORDS: diag, cloud fraction, cloud height

DESCRIPTION OF CHANGES:
Add low/mid/high/total cloud fraction and cloud top/base height diagnostics.
Activated by adding in stream_list.atmosphere.diagnostics the following variables:
cldfrac_low_UPP
cldfrac_mid_UPP
cldfrac_high_UPP
cldfrac_tot_UPP
cldfrac_low_UM
cldfrac_mid_UM
cldfrac_high_UM
cldfrac_tot_UM_max
cldfrac_tot_UM_rand
cldht_top_UM
cldht_base_UM

LIST OF MODIFIED FILES:
M src/core_atmosphere/diagnostics/Registry_convective.xml
M src/core_atmosphere/diagnostics/convective_diagnostics.F

### CODE REVIEW

**Comment by mgduda** [comment]
I've only started to look through the code changes, so there may be dependencies of the new cloud diagnostics on other fields already computed in the convective diagnostics module, but would it be worth considering to implement these new diagnostic fields in their own diagnostics module?

**Comment by jamiebresch** [comment]
> I've only started to look through the code changes, so there may be dependencies of the new cloud diagnostics on other fields already computed in the convective diagnostics module, but would it be worth considering to implement these new diagnostic fields in their own diagnostics module?

There is no real dependency on other fields in the convective diagnostics module. I was taking advantage of the existing infrastructure and I felt that cloud diagnostics fit in the convective diagnostics. I'm not sure if it's worth creating a separate cloud diagnostics module. I can conform to the preferred way of implementation.

**Comment by mgduda** [comment]
@jamiebresch Are the cloud fraction and cloud height diagnostics something that you're still interested in pursuing in another PR?

**Comment by jamiebresch** [comment]
Oh sorry for the confusion. I accidentally deleted my branch.

**Pull request closed without merging**
