### PR TITLE
Improve comments in shallow water core

### PR DESCRIPTION
**Pull request by mark-petersen**
This PR changes comments only. Hopefully this documentation will be helpful to others.

### CODE REVIEW

**Comment by mgduda** [comment]
@mark-petersen Mostly for my own curiosity, what's the motivation for adding comments to the SW core? Are you or collaborators using it for testing or teaching purposes?

**Comment by mark-petersen** [comment]
@mgduda, I am working with two new post-docs, @scalandr and @gcapodag. Both of their projects were more convenient to start in the shallow water core. As we were working through the code, the commenting was terse, so I was adding this for their benefit at the time. Hopefully it is helpful to others as well, if we take the time to commit it.

**Comment by mgduda** [comment]
@mark-petersen Apologies for dropping out of the conversation for so long. The comments look really useful, so I'd be supportive of re-opening this PR and merging it if that sounds alright to you.

**Comment by mark-petersen** [comment]
Great! Since I have not worked on MPAS-Dev in over a year, I'll let you approve and merge as you wish.

**Review by mgduda — APPROVED** [review]

**Pull request merged**
