### PR TITLE
Fix several broken COMPASS test cases

### LINKED ISSUE #517: Relative links to analysis not compatible with COMPASS work directory
Several test cases refer to relative paths to analysis that is not linked properly when the test case is set up with the `--work_dir` flag.  These test cases are:
```
 53: -o ocean -c drying_slope -r hybrid -t 1km
 54: -o ocean -c drying_slope -r hybrid -t 250m
 57: -o ocean -c drying_slope -r sigma -t 1km
 58: -o ocean -c drying_slope -r sigma -t 250m
 59: -o ocean -c drying_slope -r zstar -t 1km
 60: -o ocean -c drying_slope -r zstar -t 250m
 131: -o ocean -c surface_waves -r direct -t 1km
 132: -o ocean -c surface_waves -r thickness_source -t 1km
```
As an example from https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/drying_slope/hybrid/1km/config_analysis.xml#L3-L5:
```
  <add_link source="../../../analysis/comparison.py" dest="comparison.py"/>
  <add_link source="../../../analysis/movie.py" dest="movie.py"/>
  <add_link source="../../../analysis/data" dest="data"/>
```

Since `analysis` is not a test case itself (it has no `config_driver.xml`), it does not get copied to the work directory.  These links therefore need to be provided in this way instead:
```
  <add_link source_path="script_configuration_dir" source="analysis/comparison.py" dest="comparison.py"/>
  <add_link source_path="script_configuration_dir" source="analysis/movie.py" dest="movie.py"/>
  <add_link source_path="script_configuration_dir" source="analysis/data" dest="data"/>
```

### PR DESCRIPTION
**Pull request by xylar**
Several ocean test cases were not setting up successfully from COMPASS.  Some of these are due to recent changes, while others are due to the test cases not being updated as the switch was made from the old JIGSAW-Matlab interface to the new conda environment with jigsawpy.  With this merge, all available ocean test cases should set up successfully in COMPASS, while those that are broken have been moved into a `broken` subdirectory so the COMPASS tools no longer detect them.

Test cases that have been fixed:
```
 40: -o ocean -c Gaussian_hump -r USDEQU120cr10rr2 -t build_mesh
 49: -o ocean -c coastal -r Maine -t init
 50: -o ocean -c coastal -r USDEQU120cr10rr2 -t build_mesh
 85: -o ocean -c hurricane -r USDEQU120at30cr10rr2 -t build_mesh
 87: -o ocean -c hurricane -r USDEQU60at15cr5rr1 -t build_mesh

 53: -o ocean -c drying_slope -r hybrid -t 1km
 54: -o ocean -c drying_slope -r hybrid -t 250m
 57: -o ocean -c drying_slope -r sigma -t 1km
 58: -o ocean -c drying_slope -r sigma -t 250m
 59: -o ocean -c drying_slope -r zstar -t 1km
 60: -o ocean -c drying_slope -r zstar -t 250m
 131: -o ocean -c surface_waves -r direct -t 1km
 132: -o ocean -c surface_waves -r thickness_source -t 1km
```

Tests that have been marked as "broken":
* `soma/8km/32to8km` --> `soma/8km/broken/32to8km/`
* `soma/4km/32to4km` --> `soma/4km/broken/32to4km/`

closes #517

### CODE REVIEW

**Comment by xylar** [comment]
This PR is a temporary fix to #233 in that it "disables" these test cases.

**Comment by xylar** [comment]
Doing a little detective work, it looks like `surface_waves/thickness_source/1km` was fixed 11 months ago in https://github.com/MPAS-Dev/MPAS-Model/pull/229 but then broken again as part of https://github.com/MPAS-Dev/MPAS-Model/pull/284.

**Comment by xylar** [comment]
@pwolfram, could you approve this PR just saying that you're okay with me moving those 2 test cases to broken that we already discussed, and let me know if you're good with the metis/gpmetis fix to `surface_waves/thickness_source/1km`?

**Comment by pwolfram** [comment]
To clarify, as I understand it, the issue breaking things in #284 was use of `./metis` vs `gpmetis`.

**Comment by xylar** [comment]
Correct, and the attempt to get `metis` from the config file.

**Pull request merged**
