### PR TITLE
Updates to the USNAEC60to30cr10 mesh and coastal_tools.py

### PR DESCRIPTION
**Pull request by sbrus89**
- USNAEC60to30cr10 mesh:

   * Reduce coastal resolution to 8km
   * Rename to USNAEC60to30cr8
   * Compute the cell width function in stages.
   * Add the Caribbean and Bering Sea
   * Add Hawaii
   * Remove resolution in Northern Alaska
   * Remove resolution in St. Lawence Bay
   * Prevent high resolution from crossing into the Pacific in near
     Panama

 - coastal_tools.py

   * Bug fix for computing distance across antimeridian line
   * Add exclude boxes for regions to not apply the cell width function

### CODE REVIEW

**Comment by pwolfram** [comment]
@sbrus89, does this error look familiar?

```
Step 1. Build cellWidth array as function of latitude and longitude
***Gulf Coast***
Background grid dimensions: 1800 3600
Regional bathymetry data shape: (1681, 4321)
Extracting coastline
Done
Regional bathymetry data shape: (961, 721)
Extracting coastline
Done
Regional bathymetry data shape: (481, 1201)
Extracting coastline
Done
Traceback (most recent call last):
  File "./build_mesh.py", line 28, in <module>
    cellWidth, lon, lat = define_base_mesh.cellWidthVsLatLon()
  File "./define_base_mesh.py", line 35, in cellWidthVsLatLon
    cell_width,lon,lat = ct.coastal_refined_mesh(params,cell_width,lon,lat)
  File "/lustre/scratch4/turquoise/.mdt1/pwolfram/PR_tests/MPAS-Model/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py", line 245, in coastal_refined_mesh
    call_count)
  File "/lustre/scratch4/turquoise/.mdt1/pwolfram/PR_tests/MPAS-Model/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py", line 388, in extract_coastlines
    lon, lat, zdata, plot_box)
  File "/lustre/scratch4/turquoise/.mdt1/pwolfram/PR_tests/MPAS-Model/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py", line 639, in get_data_inside_box
    z_region = data[lat_idx, lon_idx]
  File "netCDF4/_netCDF4.pyx", line 3999, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 4072, in netCDF4._netCDF4.Variable._toma
  File "netCDF4/_netCDF4.pyx", line 4258, in netCDF4._netCDF4.Variable._check_safecast
  File "/usr/projects/climate/pwolfram/anaconda2/e3sm_unified_1.1.2_py2_nox/lib/python2.7/site-packages/netCDF4/utils.py", line 23, in _safecast
    def _safecast(a,b):
KeyboardInterrupt
Finding distance
Done
6.12098789215  seconds

***East Coast***
Regional bathymetry data shape: (4656, 4657)
Extracting coastline
Done
Finding distance
Done
9.15724515915  seconds

***Caribbean***
Regional bathymetry data shape: (2762, 7229)
Extracting coastline
Done
Finding distance
Done
6.24799489975  seconds

```

Any advice you have on this error would be appreciated.  My branch is `PRmergeCandidate`.

**Comment by pwolfram** [comment]
@sbrus89, the error disappears with an update of `netCDF4`, please ignore the previous comment.

**Comment by sbrus89** [comment]
Whew. I was just looking into it.

**Comment by pwolfram** [comment]
Sorry for the false alarm... it seemed pretty strange but I'm glad it wasn't real.  This is the one downside to conda-- sometimes the libraries get corrupted and need reinstalled.

**Comment by pwolfram** [comment]
We may want to do something about this, however:
```
/usr/projects/climate/pwolfram/anaconda2/e3sm_unified_1.1.2_py2_nox/lib/python2.7/site-packages/matplotlib/pyplot.py:537: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
```

A lot of figures are being built but not closed.  Thoughts?  In the worst case we can fix this in a clean-up PR, but I think this is related to just this mesh generation case `USNAEC60to30cr8`.  It is probably best to clean it up now, however.

**Comment by sbrus89** [comment]
Probably better to take care of it right now.

**Comment by pwolfram** [comment]
Thanks @sbrus89!

**Pull request merged**
