### PR TITLE
Fix eighteen broken coastal test cases

### PR DESCRIPTION
**Pull request by xylar**
This merge removes the `e3sm_coupling` step from the `coastal/Maine` test case.  It is not configured properly and is not needed.

It also fixes links to `cull_mesh.py` in two `USDEQU120cr10rr2` tests.

### CODE REVIEW

**Comment by mark-petersen** [comment]
@sbrus89 could you approve? Visual inspection is probably fine here.

**Comment by xylar** [comment]
> I don't have time to test, but if it works for you @xylar go ahead and merge 

> Visual inspection is probably fine here.

I'm concerned that this attitude is becoming pervasive in COMPASS.  As a result, tests are frequently broken like here and it makes them impossible to use as a baseline.  As it is, I have to test several dozen test cases in #563 to make sure that work has not done any harm.  Each broken test case adds considerable additional work to that process, including PRs like this one to fix them.

As I have complained in the past, it becomes very difficult to maintain the COMPASS infrastructure if the test cases are not exercised on a regular basis and that job cannot fall exclusively to me.

**Comment by xylar** [comment]
> I don't have time to test

This one irks me especially.  I do not have time to fix these tests (they are not mine!) but I took the time anyway and I will take the time to test them each twice more than I would have had to if they worked.

**Comment by xylar** [comment]
## Testing

Tests that now run successfully:
- [x] `Gaussian_hump/USDEQU120cr10rr2/build_mesh/`
- [ ] `coastal/Maine/init`
- [x] `coastal/USDEQU120cr10rr2/build_mesh`
- [x] `global_ocean/CA120to3/build_mesh`
- [x] `global_ocean/HI120to12/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD/build_mesh`
- [ ] `hurricane/USDEQU120at30cr10rr2WD_veg/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD/build_mesh`
- [ ] `hurricane/USDEQU240at60cr20rr4WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr100WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr1WD_veg/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr250WD/build_mesh`
- [ ] `hurricane/USDEQU60at15cr5rr500WD/build_mesh`
- [ ] `tides/USDEQU120at30cr10/build_mesh`

**Comment by xylar** [comment]
@sbrus89, while there are 2 tests of mine still running, I think this is ready for you to review.  My preference would be for you to set up and re-run these tests yourself and make sure you also see them working.  If that's not possible, let's chat about how to review these fixes meaningfully with more than just a glance at the code changes.

**Comment by sbrus89** [comment]
@xylar, thanks very much for your help maintaining these. I will take a look. Can we possibly do this PR into `ocean/coastal`? Some of these issues may have already been cleaned up there.

**Comment by sbrus89** [comment]
@xylar, nevermind... obviously, #485 has already been merged.

**Comment by xylar** [comment]
> Some of these issues may have already been cleaned up there.

I think these issues should have been dealt with in #485.  I am not happy that I didn't get a chance to do this level of testing before approving that PR and I will not make that mistake again.  Since we are considering `ocean/coastal` to be "closed" for the moment, I'd like to make the PR into `ocean/develop`.

**Comment by xylar** [comment]
FYI, my testing is in:
```
/lustre/scratch4/turquoise/xylar/test_fix_broken/
```

**Comment by xylar** [comment]
The `hurricane/USDEQU60at15cr5rr100WD/build_mesh/culled_mesh` step is taking more than 6 hours.  We really need to improve our tools!

**Comment by mark-petersen** [comment]
See #563. Tested with that one, passed nightly regression suite with compass 0.1.9. Also passed QU240wISC and USDEQU240at60cr20rr4/build_mesh on grizzly.

@sbrus89 I'll merge with your approval.

**Comment by xylar** [comment]
This one is fine to merge before `compass_0.1.9` is created.

**Pull request merged**
